// AUTO-GENERATED by tools/gen_fpga_burn.py — boot image 'counter'
// Do not edit. Source: tb/mem/counter.mem (7 words)
dmem[0] = 32'h18000000;
dmem[1] = 32'h1008000A;
dmem[2] = 32'h10040000;
dmem[3] = 32'h10042001;
dmem[4] = 32'h03802200;
dmem[5] = 32'h40BFFFFD;
dmem[6] = 32'h7F800000;
