/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_8x1
(
    input [2:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    output reg out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module alu_1b_final (
  input [7:0] OPCODE,
  input A,
  input B,
  input C,
  input Asel,
  input Bsel,
  input A_inv,
  input B_inv,
  output MUX_OUT,
  output G,
  output P
);
  wire [2:0] s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire B_eff;
  wire A_eff;
  assign A_eff = ((Asel & A) ^ A_inv);
  assign B_eff = ((Bsel & B) ^ B_inv);
  assign s1 = OPCODE[0];
  assign s2 = OPCODE[1];
  assign s3 = OPCODE[2];
  assign s4 = OPCODE[3];
  assign s5 = OPCODE[4];
  assign s6 = OPCODE[5];
  assign s7 = OPCODE[6];
  assign s8 = OPCODE[7];
  assign s0[0] = C;
  assign s0[1] = B_eff;
  assign s0[2] = A_eff;
  assign G = (A_eff & B_eff);
  assign P = (A_eff | B_eff);
  Mux_8x1 Mux_8x1_i0 (
    .sel( s0 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .in_2( s3 ),
    .in_3( s4 ),
    .in_4( s5 ),
    .in_5( s6 ),
    .in_6( s7 ),
    .in_7( s8 ),
    .out( MUX_OUT )
  );
endmodule

// quad 2-line to 1-line data selectors/multiplexers
module \74157  (
  input S, // select
  input A1,
  input A2,
  input A3,
  input A4,
  input B1,
  input B2,
  input B3,
  input B4,
  input G, // strobe
  input VCC,
  input GND,
  output Y1,
  output Y2,
  output Y3,
  output Y4
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  assign s1[0] = B1;
  assign s1[1] = B2;
  assign s1[2] = B3;
  assign s1[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( S ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( G ),
    .in_0( s2 ),
    .in_1( 4'b0 ),
    .out( s3 )
  );
  assign Y1 = s3[0];
  assign Y2 = s3[1];
  assign Y3 = s3[2];
  assign Y4 = s3[3];
endmodule

// quad 2-input AND gate
module \7408  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = (\1A  & \1B );
  assign \2Y  = (\2A  & \2B );
  assign \3Y  = (\3A  & \3B );
  assign \4Y  = (\4A  & \4B );
endmodule

// look-ahead carry generator
module \74182  (
  input C_n,
  input \~G0 ,
  input \~P0 ,
  input \~G1 ,
  input \~P1 ,
  input \~G2 ,
  input \~P2 ,
  input \~G3 ,
  input \~P3 ,
  input VCC,
  input GND,
  output \~P ,
  output \~G ,
  output \C_{n+z} ,
  output \C_{n+y} ,
  output \C_{n+x} 
);
  wire s0;
  assign \~P  = (\~P0  | \~P1  | \~P2  | \~P3 );
  assign \~G  = ((\~G0  & \~G1  & \~G2  & \~G3 ) | (\~P1  & \~G3  & \~G2  & \~G1 ) | (\~P2  & \~G3  & \~G2 ) | (\~P3  & \~G3 ));
  assign s0 = ~ C_n;
  assign \C_{n+z}  = ~ ((\~G2  & \~G1  & \~G0  & s0) | (\~P0  & \~G2  & \~G1  & \~G0 ) | (\~P1  & \~G2  & \~G1 ) | (\~P2  & \~G2 ));
  assign \C_{n+y}  = ~ ((\~G1  & \~G0  & s0) | (\~P0  & \~G1  & \~G0 ) | (\~P1  & \~G1 ));
  assign \C_{n+x}  = ~ ((\~G0  & s0) | (\~P0  & \~G0 ));
endmodule

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule

// octal buffer/line driver, inverted
module \74540  (
  input \~OE1 ,
  input \~OE2 ,
  input \0D ,
  input \1D ,
  input \2D ,
  input \3D ,
  input \4D ,
  input \5D ,
  input \6D ,
  input \7D ,
  input VCC,
  input GND,
  output \0O ,
  output \1O ,
  output \2O ,
  output \3O ,
  output \4O ,
  output \5O ,
  output \6O ,
  output \7O 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  assign s1 = ~ (\~OE1  | \~OE2 );
  assign s0 = ~ \0D ;
  assign s2 = ~ \1D ;
  assign s3 = ~ \2D ;
  assign s4 = ~ \3D ;
  assign s5 = ~ \4D ;
  assign s6 = ~ \5D ;
  assign s7 = ~ \6D ;
  assign s8 = ~ \7D ;
  Driver Driver_i0 (
    .in( s0 ),
    .sel( s1 ),
    .out( \0O  )
  );
  Driver Driver_i1 (
    .in( s2 ),
    .sel( s1 ),
    .out( \1O  )
  );
  Driver Driver_i2 (
    .in( s3 ),
    .sel( s1 ),
    .out( \2O  )
  );
  Driver Driver_i3 (
    .in( s4 ),
    .sel( s1 ),
    .out( \3O  )
  );
  Driver Driver_i4 (
    .in( s5 ),
    .sel( s1 ),
    .out( \4O  )
  );
  Driver Driver_i5 (
    .in( s6 ),
    .sel( s1 ),
    .out( \5O  )
  );
  Driver Driver_i6 (
    .in( s7 ),
    .sel( s1 ),
    .out( \6O  )
  );
  Driver Driver_i7 (
    .in( s8 ),
    .sel( s1 ),
    .out( \7O  )
  );
endmodule

// quad 2-input OR gate
module \7432  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = (\1A  | \1B );
  assign \2Y  = (\2A  | \2B );
  assign \3Y  = (\3A  | \3B );
  assign \4Y  = (\4A  | \4B );
endmodule

module alu_8b_final (
  input [7:0] opcode,
  input [4:0] control,
  input [7:0] A,
  input [7:0] B,
  input [7:0] C,
  input \nz-in ,
  input cin,
  output [7:0] out,
  output vout,
  output zout,
  output \nz-out ,
  output n,
  output cout
);
  wire a0;
  wire b0;
  wire ceff0;
  wire asel;
  wire bsel;
  wire ainv;
  wire binv;
  wire out0;
  wire g0;
  wire p0;
  wire a1;
  wire b1;
  wire ceff1;
  wire out1;
  wire g1;
  wire p1;
  wire a2;
  wire b2;
  wire ceff2;
  wire out2;
  wire g2;
  wire p2;
  wire a3;
  wire b3;
  wire ceff3;
  wire out3;
  wire g3;
  wire p3;
  wire a4;
  wire b4;
  wire ceff4;
  wire out4;
  wire g4;
  wire p4;
  wire a5;
  wire b5;
  wire ceff5;
  wire out5;
  wire g5;
  wire p5;
  wire a6;
  wire b6;
  wire ceff6;
  wire out6;
  wire g6;
  wire p6;
  wire a7;
  wire b7;
  wire ceff7;
  wire n_temp;
  wire g7;
  wire p7;
  wire csel;
  wire c0;
  wire c1;
  wire c2;
  wire c3;
  wire c4;
  wire c5;
  wire c6;
  wire c7;
  wire cin1;
  wire cin2;
  wire cin3;
  wire cin4;
  wire cin5;
  wire cin6;
  wire cin7;
  wire cout_temp;
  wire zout_temp;
  wire c0xp0;
  wire s0;
  wire c4xp1;
  wire s1;
  wire s2;
  wire s3;
  wire g1_b;
  wire p1_b;
  wire g0_b;
  wire p0_b;
  wire g3_b;
  wire p3_b;
  wire \p-out-0 ;
  wire \g-out-0 ;
  wire g2_b;
  wire p2_b;
  wire g5_b;
  wire p5_b;
  wire g4_b;
  wire p4_b;
  wire g7_b;
  wire p7_b;
  wire \p-out-1 ;
  wire \g-out-1 ;
  wire g6_b;
  wire p6_b;
  assign asel = control[0];
  assign ainv = control[1];
  assign bsel = control[2];
  assign binv = control[3];
  assign csel = control[4];
  assign a0 = A[0];
  assign a1 = A[1];
  assign a2 = A[2];
  assign a3 = A[3];
  assign a4 = A[4];
  assign a5 = A[5];
  assign a6 = A[6];
  assign a7 = A[7];
  assign b0 = B[0];
  assign b1 = B[1];
  assign b2 = B[2];
  assign b3 = B[3];
  assign b4 = B[4];
  assign b5 = B[5];
  assign b6 = B[6];
  assign b7 = B[7];
  assign c0 = C[0];
  assign c1 = C[1];
  assign c2 = C[2];
  assign c3 = C[3];
  assign c4 = C[4];
  assign c5 = C[5];
  assign c6 = C[6];
  assign c7 = C[7];
  alu_1b_final alu_1b_final_i0 (
    .OPCODE( opcode ),
    .A( a0 ),
    .B( b0 ),
    .C( ceff0 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out0 ),
    .G( g0 ),
    .P( p0 )
  );
  alu_1b_final alu_1b_final_i1 (
    .OPCODE( opcode ),
    .A( a1 ),
    .B( b1 ),
    .C( ceff1 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out1 ),
    .G( g1 ),
    .P( p1 )
  );
  alu_1b_final alu_1b_final_i2 (
    .OPCODE( opcode ),
    .A( a2 ),
    .B( b2 ),
    .C( ceff2 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out2 ),
    .G( g2 ),
    .P( p2 )
  );
  alu_1b_final alu_1b_final_i3 (
    .OPCODE( opcode ),
    .A( a3 ),
    .B( b3 ),
    .C( ceff3 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out3 ),
    .G( g3 ),
    .P( p3 )
  );
  alu_1b_final alu_1b_final_i4 (
    .OPCODE( opcode ),
    .A( a4 ),
    .B( b4 ),
    .C( ceff4 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out4 ),
    .G( g4 ),
    .P( p4 )
  );
  alu_1b_final alu_1b_final_i5 (
    .OPCODE( opcode ),
    .A( a5 ),
    .B( b5 ),
    .C( ceff5 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out5 ),
    .G( g5 ),
    .P( p5 )
  );
  alu_1b_final alu_1b_final_i6 (
    .OPCODE( opcode ),
    .A( a6 ),
    .B( b6 ),
    .C( ceff6 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out6 ),
    .G( g6 ),
    .P( p6 )
  );
  alu_1b_final alu_1b_final_i7 (
    .OPCODE( opcode ),
    .A( a7 ),
    .B( b7 ),
    .C( ceff7 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( n_temp ),
    .G( g7 ),
    .P( p7 )
  );
  \74157  \74157_i8 (
    .S( csel ),
    .A1( cin ),
    .B1( c0 ),
    .A2( cin1 ),
    .B2( c1 ),
    .GND( 1'b0 ),
    .B3( c2 ),
    .A3( cin2 ),
    .B4( c3 ),
    .A4( cin3 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( ceff0 ),
    .Y2( ceff1 ),
    .Y3( ceff2 ),
    .Y4( ceff3 )
  );
  \74157  \74157_i9 (
    .S( csel ),
    .A1( cin4 ),
    .B1( c4 ),
    .A2( cin5 ),
    .B2( c5 ),
    .GND( 1'b0 ),
    .B3( c6 ),
    .A3( cin6 ),
    .B4( c7 ),
    .A4( cin7 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( ceff4 ),
    .Y2( ceff5 ),
    .Y3( ceff6 ),
    .Y4( ceff7 )
  );
  assign \nz-out  = (~ zout_temp | \nz-in );
  \7408  \7408_i10 (
    .\1A ( s2 ),
    .\1B ( cin ),
    .\2A ( s3 ),
    .\2B ( cin4 ),
    .GND( 1'b0 ),
    .\3A ( 1'b0 ),
    .\3B ( 1'b0 ),
    .\4A ( 1'b0 ),
    .\4B ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( c0xp0 ),
    .\2Y ( c4xp1 )
  );
  \74182  \74182_i11 (
    .\~G1 ( g1_b ),
    .\~P1 ( p1_b ),
    .\~G0 ( g0_b ),
    .\~P0 ( p0_b ),
    .\~G3 ( g3_b ),
    .\~P3 ( p3_b ),
    .GND( 1'b0 ),
    .C_n( cin ),
    .\~G2 ( g2_b ),
    .\~P2 ( p2_b ),
    .VCC( 1'b1 ),
    .\~P ( \p-out-0  ),
    .\C_{n+z} ( cin3 ),
    .\~G ( \g-out-0  ),
    .\C_{n+y} ( cin2 ),
    .\C_{n+x} ( cin1 )
  );
  assign out[0] = out0;
  assign out[1] = out1;
  assign out[2] = out2;
  assign out[3] = out3;
  assign out[4] = out4;
  assign out[5] = out5;
  assign out[6] = out6;
  assign out[7] = n_temp;
  assign zout_temp = (~ (out0 | out1 | out2 | out3) & ~ (out4 | out5 | out6 | n_temp));
  \74540  \74540_i12 (
    .\~OE1 ( 1'b0 ),
    .\0D ( p0 ),
    .\1D ( p1 ),
    .\2D ( p2 ),
    .\3D ( p3 ),
    .\4D ( g0 ),
    .\5D ( g1 ),
    .\6D ( g2 ),
    .\7D ( g3 ),
    .GND( 1'b0 ),
    .\~OE2 ( 1'b0 ),
    .VCC( 1'b1 ),
    .\7O ( g3_b ),
    .\6O ( g2_b ),
    .\5O ( g1_b ),
    .\4O ( g0_b ),
    .\3O ( p3_b ),
    .\2O ( p2_b ),
    .\1O ( p1_b ),
    .\0O ( p0_b )
  );
  \74540  \74540_i13 (
    .\~OE1 ( 1'b0 ),
    .\0D ( p4 ),
    .\1D ( p5 ),
    .\2D ( p6 ),
    .\3D ( p7 ),
    .\4D ( g4 ),
    .\5D ( g5 ),
    .\6D ( g6 ),
    .\7D ( g7 ),
    .GND( 1'b0 ),
    .\~OE2 ( 1'b0 ),
    .VCC( 1'b1 ),
    .\7O ( g7_b ),
    .\6O ( g6_b ),
    .\5O ( g5_b ),
    .\4O ( g4_b ),
    .\3O ( p7_b ),
    .\2O ( p6_b ),
    .\1O ( p5_b ),
    .\0O ( p4_b )
  );
  assign s2 = ~ \p-out-0 ;
  assign s0 = ~ \g-out-0 ;
  \7432  \7432_i14 (
    .\1A ( c0xp0 ),
    .\1B ( s0 ),
    .\2A ( c4xp1 ),
    .\2B ( s1 ),
    .GND( 1'b0 ),
    .\3A ( 1'b0 ),
    .\3B ( 1'b0 ),
    .\4A ( 1'b0 ),
    .\4B ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( cin4 ),
    .\2Y ( cout_temp )
  );
  \74182  \74182_i15 (
    .\~G1 ( g5_b ),
    .\~P1 ( p5_b ),
    .\~G0 ( g4_b ),
    .\~P0 ( p4_b ),
    .\~G3 ( g7_b ),
    .\~P3 ( p7_b ),
    .GND( 1'b0 ),
    .C_n( cin4 ),
    .\~G2 ( g6_b ),
    .\~P2 ( p6_b ),
    .VCC( 1'b1 ),
    .\~P ( \p-out-1  ),
    .\C_{n+z} ( cin7 ),
    .\~G ( \g-out-1  ),
    .\C_{n+y} ( cin6 ),
    .\C_{n+x} ( cin5 )
  );
  assign vout = (cin7 ^ cout_temp);
  assign s3 = ~ \p-out-1 ;
  assign s1 = ~ \g-out-1 ;
  assign zout = zout_temp;
  assign n = n_temp;
  assign cout = cout_temp;
endmodule

module \alu-32b-final  (
  input [31:0] A,
  input nz0,
  input [31:0] B,
  input [7:0] Opcode,
  input [4:0] control,
  input [31:0] REG_C,
  input \cin-sel ,
  input FLAG_C,
  output vout,
  output zout,
  output nzout,
  output nout,
  output [31:0] Out,
  output cout
);
  wire [7:0] \a0-7 ;
  wire [7:0] \b0-7 ;
  wire [7:0] \c0-7 ;
  wire cin0;
  wire [7:0] \out0-7 ;
  wire nz1;
  wire c7;
  wire [7:0] \a16-23 ;
  wire [7:0] \b16-23 ;
  wire [7:0] \c16-23 ;
  wire c15;
  wire [7:0] \out16-23 ;
  wire nz2;
  wire c23;
  wire [7:0] \a8-15 ;
  wire [7:0] \b8-15 ;
  wire [7:0] \c8-15 ;
  wire [7:0] \out8-15 ;
  wire nz3;
  wire [7:0] \a24-31 ;
  wire [7:0] \b24-31 ;
  wire [7:0] \c24-31 ;
  wire [7:0] \out24-31 ;
  wire nzout_temp;
  wire [31:0] ceff;
  wire asel;
  wire ainv;
  wire bsel;
  wire binv;
  wire csel;
  wire [31:0] FLAG_C32;
  wire [31:0] \const1-32 ;
  wire [31:0] s0;
  wire [6:0] gnd7;
  assign gnd7[0] = 1'b0;
  assign gnd7[1] = 1'b0;
  assign gnd7[2] = 1'b0;
  assign gnd7[3] = 1'b0;
  assign gnd7[4] = 1'b0;
  assign gnd7[5] = 1'b0;
  assign gnd7[6] = 1'b0;
  assign \a0-7  = A[7:0];
  assign \a8-15  = A[15:8];
  assign \a16-23  = A[23:16];
  assign \a24-31  = A[31:24];
  assign \b0-7  = B[7:0];
  assign \b8-15  = B[15:8];
  assign \b16-23  = B[23:16];
  assign \b24-31  = B[31:24];
  assign asel = control[0];
  assign ainv = control[1];
  assign bsel = control[2];
  assign binv = control[3];
  assign csel = control[4];
  assign \const1-32 [0] = 1'b1;
  assign \const1-32 [7:1] = gnd7;
  assign \const1-32 [14:8] = gnd7;
  assign \const1-32 [21:15] = gnd7;
  assign \const1-32 [28:22] = gnd7;
  assign \const1-32 [29] = 1'b0;
  assign \const1-32 [30] = 1'b0;
  assign \const1-32 [31] = 1'b0;
  assign FLAG_C32[0] = FLAG_C;
  assign FLAG_C32[7:1] = gnd7;
  assign FLAG_C32[14:8] = gnd7;
  assign FLAG_C32[21:15] = gnd7;
  assign FLAG_C32[28:22] = gnd7;
  assign FLAG_C32[29] = 1'b0;
  assign FLAG_C32[30] = 1'b0;
  assign FLAG_C32[31] = 1'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i0 (
    .sel( \cin-sel  ),
    .in_0( FLAG_C32 ),
    .in_1( \const1-32  ),
    .out( s0 )
  );
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i1 (
    .sel( csel ),
    .in_0( s0 ),
    .in_1( REG_C ),
    .out( ceff )
  );
  assign \c0-7  = ceff[7:0];
  assign \c8-15  = ceff[15:8];
  assign \c16-23  = ceff[23:16];
  assign \c24-31  = ceff[31:24];
  assign cin0 = \c0-7 [0];
  // Cell 0
  alu_8b_final alu_8b_final_i2 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a0-7  ),
    .B( \b0-7  ),
    .C( \c0-7  ),
    .\nz-in ( nz0 ),
    .cin( cin0 ),
    .out( \out0-7  ),
    .\nz-out ( nz1 ),
    .cout( c7 )
  );
  // Cell 2
  alu_8b_final alu_8b_final_i3 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a16-23  ),
    .B( \b16-23  ),
    .C( \c16-23  ),
    .\nz-in ( nz1 ),
    .cin( c15 ),
    .out( \out16-23  ),
    .\nz-out ( nz2 ),
    .cout( c23 )
  );
  // Cell 1
  alu_8b_final alu_8b_final_i4 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a8-15  ),
    .B( \b8-15  ),
    .C( \c8-15  ),
    .\nz-in ( nz2 ),
    .cin( c7 ),
    .out( \out8-15  ),
    .\nz-out ( nz3 ),
    .cout( c15 )
  );
  // Cell 3
  alu_8b_final alu_8b_final_i5 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a24-31  ),
    .B( \b24-31  ),
    .C( \c24-31  ),
    .\nz-in ( nz3 ),
    .cin( c23 ),
    .out( \out24-31  ),
    .vout( vout ),
    .\nz-out ( nzout_temp ),
    .n( nout ),
    .cout( cout )
  );
  assign Out[7:0] = \out0-7 ;
  assign Out[15:8] = \out8-15 ;
  assign Out[23:16] = \out16-23 ;
  assign Out[31:24] = \out24-31 ;
  assign zout = ~ nzout_temp;
  assign nzout = nzout_temp;
endmodule
