/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module \bus-arbitration  (
  input FETCH,
  input [23:0] PC_OUT,
  input [23:0] IR_ADDR,
  input [23:0] reg_a,
  input MEM_RD_IN,
  input \addr_sel_bus-arb ,
  output [23:0] ADDR_BUS,
  output MEM_RD_OUT
);
  wire [23:0] in_mux_out;
  assign MEM_RD_OUT = (MEM_RD_IN | FETCH);
  Mux_2x1_NBits #(
    .Bits(24)
  )
  Mux_2x1_NBits_i0 (
    .sel( \addr_sel_bus-arb  ),
    .in_0( IR_ADDR ),
    .in_1( reg_a ),
    .out( in_mux_out )
  );
  Mux_2x1_NBits #(
    .Bits(24)
  )
  Mux_2x1_NBits_i1 (
    .sel( FETCH ),
    .in_0( PC_OUT ),
    .in_1( in_mux_out ),
    .out( ADDR_BUS )
  );
endmodule
