/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

// dual D-flip-flop
module \7474  (
  input \~1SD ,
  input \1D ,
  input \1CP ,
  input \~1RD ,
  input \~2SD ,
  input \2D ,
  input \2CP ,
  input \~2RD ,
  input VCC,
  input GND,
  output \1Q ,
  output \~1Q ,
  output \2Q ,
  output \~2Q 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s0 = ~ \~1SD ;
  assign s1 = ~ \~1RD ;
  assign s3 = ~ \~2SD ;
  assign s4 = ~ \~2RD ;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( s0 ),
    .D( \1D  ),
    .C( \1CP  ),
    .Clr( s1 ),
    .Q( \1Q  ),
    .\~Q ( s2 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( s3 ),
    .D( \2D  ),
    .C( \2CP  ),
    .Clr( s4 ),
    .Q( \2Q  ),
    .\~Q ( s5 )
  );
  assign \~1Q  = (s2 | (~ \~1SD  & ~ \~1RD ));
  assign \~2Q  = (s5 | (~ \~2SD  & ~ \~2RD ));
endmodule

module \flag-reg  (
  input ZERO_IN,
  input CARRY_IN,
  input NEGATIVE_IN,
  input OVERFLOW_IN,
  input FLAG_WE,
  input CLK,
  input EXEC,
  output FLAG_Z,
  output FLAG_C,
  output FLAG_N,
  output FLAG_O
);
  wire CLK_GATED;
  wire FLAG_Z_N;
  wire FLAG_C_N;
  wire FLAG_NN;
  wire FLAG_O_N;
  assign CLK_GATED = (CLK & EXEC & FLAG_WE);
  \7474  \7474_i0 (
    .\~1RD ( 1'b1 ),
    .\1D ( ZERO_IN ),
    .\1CP ( CLK_GATED ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( CLK_GATED ),
    .\2D ( CARRY_IN ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAG_Z ),
    .\~1Q ( FLAG_Z_N ),
    .\~2Q ( FLAG_C_N ),
    .\2Q ( FLAG_C )
  );
  \7474  \7474_i1 (
    .\~1RD ( 1'b1 ),
    .\1D ( NEGATIVE_IN ),
    .\1CP ( CLK_GATED ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( CLK_GATED ),
    .\2D ( OVERFLOW_IN ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAG_N ),
    .\~1Q ( FLAG_NN ),
    .\~2Q ( FLAG_O_N ),
    .\2Q ( FLAG_O )
  );
endmodule
