/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module io_controller (
  input [23:0] mem_addr,
  input c_wr,
  input [15:0] kb_data,
  input [31:0] mem_data_out,
  output [31:0] io_data_in,
  output ram_cs,
  output vram_we,
  output [15:0] vram_addr,
  output [15:0] vram_data,
  output term_we,
  output [15:0] term_data
);
  wire comp2_eq;
  wire \comp3_> ;
  wire comp3_eq;
  wire comp4_eq;
  wire \comp4_< ;
  wire [31:0] c_kb_in;
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i0 (
    .a( mem_addr ),
    .b( 24'b100000000000000000000000 ),
    .\< ( ram_cs )
  );
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i1 (
    .a( mem_addr ),
    .b( 24'b100000000000000000010000 ),
    .\= ( comp2_eq )
  );
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i2 (
    .a( mem_addr ),
    .b( 24'b111100000000000000000000 ),
    .\> ( \comp3_>  ),
    .\= ( comp3_eq )
  );
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i3 (
    .a( mem_addr ),
    .b( 24'b100000000000000000010100 ),
    .\= ( comp4_eq ),
    .\< ( \comp4_<  )
  );
  assign c_kb_in[15:0] = kb_data;
  assign c_kb_in[31:16] = 16'b0;
  assign term_data = mem_data_out[15:0];
  assign vram_addr = mem_addr[15:0];
  assign vram_data = mem_data_out[15:0];
  assign term_we = (comp2_eq & c_wr);
  assign vram_we = ((\comp3_>  | comp3_eq) & c_wr);
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i4 (
    .sel( comp4_eq ),
    .in_0( 32'b0 ),
    .in_1( c_kb_in ),
    .out( io_data_in )
  );
endmodule
