/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module DriverInvBus#(
    parameter Bits = 2
)
(
    input [(Bits-1):0] in,
    input sel,
    output [(Bits-1):0] out
);
    assign out = (sel == 1'b0)? in : {Bits{1'bz}};
endmodule

// octal positive-edge-triggered flip-flops, different pinout compared to 74374
module \74574  (
  input \~OC ,
  input CLK,
  input D0,
  input D1,
  input D2,
  input D3,
  input D4,
  input D5,
  input D6,
  input D7,
  input VCC,
  input GND,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7
);
  wire [7:0] s0;
  wire [7:0] s1;
  wire [7:0] s2;
  assign s0[0] = D0;
  assign s0[1] = D1;
  assign s0[2] = D2;
  assign s0[3] = D3;
  assign s0[4] = D4;
  assign s0[5] = D5;
  assign s0[6] = D6;
  assign s0[7] = D7;
  DIG_D_FF_Nbit #(
    .Bits(8),
    .Default(0)
  )
  DIG_D_FF_Nbit_i0 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 )
  );
  DriverInvBus #(
    .Bits(8)
  )
  DriverInvBus_i1 (
    .in( s1 ),
    .sel( \~OC  ),
    .out( s2 )
  );
  assign Q0 = s2[0];
  assign Q1 = s2[1];
  assign Q2 = s2[2];
  assign Q3 = s2[3];
  assign Q4 = s2[4];
  assign Q5 = s2[5];
  assign Q6 = s2[6];
  assign Q7 = s2[7];
endmodule

module ir (
  input CLK,
  input LOAD,
  input [31:0] DATA_IN,
  output [7:0] OPCODE,
  output [7:0] ADDR_A,
  output [7:0] ADDR_B,
  output [7:0] ADDR_W,
  output [23:0] ADDR_ABS,
  output [23:0] OFFSET,
  output [31:0] IR_BUS,
  output [2:0] COND,
  output MUX1_SEL,
  output MUX2_SEL
);
  wire IR_IN_0;
  wire IR_IN_1;
  wire IR_IN_2;
  wire IR_IN_3;
  wire IR_IN_4;
  wire IR_IN_5;
  wire IR_IN_6;
  wire IR_IN_7;
  wire CLK_GATED;
  wire IR_7;
  wire IR_6;
  wire IR_5;
  wire IR_4;
  wire IR_3;
  wire IR_2;
  wire IR_1;
  wire IR_0;
  wire IR_IN_8;
  wire IR_IN_9;
  wire IR_IN_10;
  wire IR_IN_11;
  wire IR_IN_12;
  wire IR_IN_13;
  wire IR_IN_14;
  wire IR_IN_15;
  wire IR_15;
  wire IR_14;
  wire IR_13;
  wire IR_12;
  wire IR_11;
  wire IR_10;
  wire IR_9;
  wire IR_8;
  wire IR_IN_16;
  wire IR_IN_17;
  wire IR_IN_18;
  wire IR_IN_19;
  wire IR_IN_20;
  wire IR_IN_21;
  wire IR_IN_22;
  wire IR_IN_23;
  wire IR_23;
  wire IR_22;
  wire IR_21;
  wire IR_20;
  wire IR_19;
  wire IR_18;
  wire IR_17;
  wire IR_16;
  wire IR_IN_24;
  wire IR_IN_25;
  wire IR_IN_26;
  wire IR_IN_27;
  wire IR_IN_28;
  wire IR_IN_29;
  wire IR_IN_30;
  wire IR_IN_31;
  wire IR_31;
  wire IR_30;
  wire IR_29;
  wire IR_28;
  wire IR_27;
  wire IR_26;
  wire IR_25;
  wire IR_24;
  wire [31:0] IR_BUS_temp;
  wire [23:0] OFFSET_temp;
  wire [7:0] OPCODE_temp;
  assign CLK_GATED = (CLK & LOAD);
  assign IR_IN_0 = DATA_IN[0];
  assign IR_IN_1 = DATA_IN[1];
  assign IR_IN_2 = DATA_IN[2];
  assign IR_IN_3 = DATA_IN[3];
  assign IR_IN_4 = DATA_IN[4];
  assign IR_IN_5 = DATA_IN[5];
  assign IR_IN_6 = DATA_IN[6];
  assign IR_IN_7 = DATA_IN[7];
  assign IR_IN_8 = DATA_IN[8];
  assign IR_IN_9 = DATA_IN[9];
  assign IR_IN_10 = DATA_IN[10];
  assign IR_IN_11 = DATA_IN[11];
  assign IR_IN_12 = DATA_IN[12];
  assign IR_IN_13 = DATA_IN[13];
  assign IR_IN_14 = DATA_IN[14];
  assign IR_IN_15 = DATA_IN[15];
  assign IR_IN_16 = DATA_IN[16];
  assign IR_IN_17 = DATA_IN[17];
  assign IR_IN_18 = DATA_IN[18];
  assign IR_IN_19 = DATA_IN[19];
  assign IR_IN_20 = DATA_IN[20];
  assign IR_IN_21 = DATA_IN[21];
  assign IR_IN_22 = DATA_IN[22];
  assign IR_IN_23 = DATA_IN[23];
  assign IR_IN_24 = DATA_IN[24];
  assign IR_IN_25 = DATA_IN[25];
  assign IR_IN_26 = DATA_IN[26];
  assign IR_IN_27 = DATA_IN[27];
  assign IR_IN_28 = DATA_IN[28];
  assign IR_IN_29 = DATA_IN[29];
  assign IR_IN_30 = DATA_IN[30];
  assign IR_IN_31 = DATA_IN[31];
  \74574  \74574_i0 (
    .\~OC ( 1'b0 ),
    .D0( IR_IN_0 ),
    .D1( IR_IN_1 ),
    .D2( IR_IN_2 ),
    .D3( IR_IN_3 ),
    .D4( IR_IN_4 ),
    .D5( IR_IN_5 ),
    .D6( IR_IN_6 ),
    .D7( IR_IN_7 ),
    .GND( 1'b0 ),
    .CLK( CLK_GATED ),
    .VCC( 1'b1 ),
    .Q7( IR_7 ),
    .Q6( IR_6 ),
    .Q5( IR_5 ),
    .Q4( IR_4 ),
    .Q3( IR_3 ),
    .Q2( IR_2 ),
    .Q1( IR_1 ),
    .Q0( IR_0 )
  );
  \74574  \74574_i1 (
    .\~OC ( 1'b0 ),
    .D0( IR_IN_8 ),
    .D1( IR_IN_9 ),
    .D2( IR_IN_10 ),
    .D3( IR_IN_11 ),
    .D4( IR_IN_12 ),
    .D5( IR_IN_13 ),
    .D6( IR_IN_14 ),
    .D7( IR_IN_15 ),
    .GND( 1'b0 ),
    .CLK( CLK_GATED ),
    .VCC( 1'b1 ),
    .Q7( IR_15 ),
    .Q6( IR_14 ),
    .Q5( IR_13 ),
    .Q4( IR_12 ),
    .Q3( IR_11 ),
    .Q2( IR_10 ),
    .Q1( IR_9 ),
    .Q0( IR_8 )
  );
  \74574  \74574_i2 (
    .\~OC ( 1'b0 ),
    .D0( IR_IN_16 ),
    .D1( IR_IN_17 ),
    .D2( IR_IN_18 ),
    .D3( IR_IN_19 ),
    .D4( IR_IN_20 ),
    .D5( IR_IN_21 ),
    .D6( IR_IN_22 ),
    .D7( IR_IN_23 ),
    .GND( 1'b0 ),
    .CLK( CLK_GATED ),
    .VCC( 1'b1 ),
    .Q7( IR_23 ),
    .Q6( IR_22 ),
    .Q5( IR_21 ),
    .Q4( IR_20 ),
    .Q3( IR_19 ),
    .Q2( IR_18 ),
    .Q1( IR_17 ),
    .Q0( IR_16 )
  );
  \74574  \74574_i3 (
    .\~OC ( 1'b0 ),
    .D0( IR_IN_24 ),
    .D1( IR_IN_25 ),
    .D2( IR_IN_26 ),
    .D3( IR_IN_27 ),
    .D4( IR_IN_28 ),
    .D5( IR_IN_29 ),
    .D6( IR_IN_30 ),
    .D7( IR_IN_31 ),
    .GND( 1'b0 ),
    .CLK( CLK_GATED ),
    .VCC( 1'b1 ),
    .Q7( IR_31 ),
    .Q6( IR_30 ),
    .Q5( IR_29 ),
    .Q4( IR_28 ),
    .Q3( IR_27 ),
    .Q2( IR_26 ),
    .Q1( IR_25 ),
    .Q0( IR_24 )
  );
  assign IR_BUS_temp[0] = IR_0;
  assign IR_BUS_temp[1] = IR_1;
  assign IR_BUS_temp[2] = IR_2;
  assign IR_BUS_temp[3] = IR_3;
  assign IR_BUS_temp[4] = IR_4;
  assign IR_BUS_temp[5] = IR_5;
  assign IR_BUS_temp[6] = IR_6;
  assign IR_BUS_temp[7] = IR_7;
  assign IR_BUS_temp[8] = IR_8;
  assign IR_BUS_temp[9] = IR_9;
  assign IR_BUS_temp[10] = IR_10;
  assign IR_BUS_temp[11] = IR_11;
  assign IR_BUS_temp[12] = IR_12;
  assign IR_BUS_temp[13] = IR_13;
  assign IR_BUS_temp[14] = IR_14;
  assign IR_BUS_temp[15] = IR_15;
  assign IR_BUS_temp[16] = IR_16;
  assign IR_BUS_temp[17] = IR_17;
  assign IR_BUS_temp[18] = IR_18;
  assign IR_BUS_temp[19] = IR_19;
  assign IR_BUS_temp[20] = IR_20;
  assign IR_BUS_temp[21] = IR_21;
  assign IR_BUS_temp[22] = IR_22;
  assign IR_BUS_temp[23] = IR_23;
  assign IR_BUS_temp[24] = IR_24;
  assign IR_BUS_temp[25] = IR_25;
  assign IR_BUS_temp[26] = IR_26;
  assign IR_BUS_temp[27] = IR_27;
  assign IR_BUS_temp[28] = IR_28;
  assign IR_BUS_temp[29] = IR_29;
  assign IR_BUS_temp[30] = IR_30;
  assign IR_BUS_temp[31] = IR_31;
  assign OFFSET_temp = IR_BUS_temp[23:0];
  assign OPCODE_temp = IR_BUS_temp[31:24];
  assign ADDR_A = IR_BUS_temp[23:16];
  assign ADDR_W = IR_BUS_temp[7:0];
  assign ADDR_B = IR_BUS_temp[15:8];
  assign COND = OPCODE_temp[2:0];
  assign MUX1_SEL = OPCODE_temp[0];
  assign MUX2_SEL = OPCODE_temp[1];
  assign OPCODE = OPCODE_temp;
  assign ADDR_ABS = OFFSET_temp;
  assign OFFSET = OFFSET_temp;
  assign IR_BUS = IR_BUS_temp;
endmodule
