/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module ir2 (
  input CLK,
  input LOAD,
  input [31:0] DATA_IN,
  output [7:0] OPCODE,
  output [7:0] ADDR_A,
  output [7:0] ADDR_B,
  output [7:0] ADDR_W,
  output [23:0] ADDR_ABS,
  output [23:0] OFFSET,
  output [31:0] IR_BUS,
  output [2:0] COND,
  output MUX1_SEL,
  output MUX2_SEL
);
  wire [31:0] IR_BUS_temp;
  wire [23:0] OFFSET_temp;
  wire [7:0] OPCODE_temp;
  // ir
  DIG_Register_BUS #(
    .Bits(32)
  )
  DIG_Register_BUS_i0 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( LOAD ),
    .Q( IR_BUS_temp )
  );
  assign OFFSET_temp = IR_BUS_temp[23:0];
  assign OPCODE_temp = IR_BUS_temp[31:24];
  assign ADDR_A = IR_BUS_temp[23:16];
  assign ADDR_W = IR_BUS_temp[7:0];
  assign ADDR_B = IR_BUS_temp[15:8];
  assign COND = OPCODE_temp[2:0];
  assign MUX1_SEL = OPCODE_temp[0];
  assign MUX2_SEL = OPCODE_temp[1];
  assign OPCODE = OPCODE_temp;
  assign ADDR_ABS = OFFSET_temp;
  assign OFFSET = OFFSET_temp;
  assign IR_BUS = IR_BUS_temp;
endmodule
