/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



// hex synchronous counter
module \74163  (
  input \~PE ,
  input \~SR ,
  input CP,
  input CET,
  input CEP,
  input P0,
  input P1,
  input P2,
  input P3,
  input VCC,
  input GND,
  output TC,
  output Q0,
  output Q1,
  output Q2,
  output Q3
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire s3;
  wire s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [3:0] s7;
  assign s4 = (CEP & CET);
  assign s6[0] = P0;
  assign s6[1] = P1;
  assign s6[2] = P2;
  assign s6[3] = P3;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( s4 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .out( s5 )
  );
  assign TC = (s3 & CET);
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( \~PE  ),
    .in_0( s6 ),
    .in_1( s5 ),
    .out( s7 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( \~SR  ),
    .in_0( 4'b0 ),
    .in_1( s7 ),
    .out( s0 )
  );
  // Q
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i3 (
    .D( s0 ),
    .C( CP ),
    .Q( s1 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i4 (
    .a( s1 ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s2 ),
    .c_o( s3 )
  );
  assign Q0 = s1[0];
  assign Q1 = s1[1];
  assign Q2 = s1[2];
  assign Q3 = s1[3];
endmodule

module sequencer (
  input reset,
  input [1:0] cycles,
  input CLK,
  output FETCH,
  output EXECUTE,
  output MEM_WAIT
);
  wire RESET_N;
  wire \~clk ;
  wire UNUSED_Q3;
  wire UNUSED_Q2;
  wire SEQ_Q1;
  wire SEQ_Q0;
  wire SEQ_TC;
  wire SEQ_Q0_N;
  wire SEQ_Q1_N;
  assign \~clk  = ~ CLK;
  \74163  \74163_i0 (
    .\~SR ( RESET_N ),
    .CP( \~clk  ),
    .P0( 1'b0 ),
    .P1( 1'b0 ),
    .P2( 1'b0 ),
    .P3( 1'b0 ),
    .CEP( 1'b1 ),
    .GND( 1'b0 ),
    .\~PE ( 1'b1 ),
    .CET( 1'b1 ),
    .VCC( 1'b1 ),
    .Q3( UNUSED_Q3 ),
    .Q2( UNUSED_Q2 ),
    .Q1( SEQ_Q1 ),
    .Q0( SEQ_Q0 ),
    .TC( SEQ_TC )
  );
  assign RESET_N = (~ (~ reset) & ~ (~ (SEQ_Q0 ^ cycles[0]) & ~ (SEQ_Q1 ^ cycles[1])));
  assign SEQ_Q0_N = ~ SEQ_Q0;
  assign SEQ_Q1_N = ~ SEQ_Q1;
  assign FETCH = (SEQ_Q0_N & SEQ_Q1_N);
  assign EXECUTE = (SEQ_Q0 & SEQ_Q1_N);
  assign MEM_WAIT = (SEQ_Q0_N & SEQ_Q1);
endmodule

// hex inverter
module \7404  (
  input \1A ,
  input \2A ,
  input \3A ,
  input \4A ,
  input \5A ,
  input \6A ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y ,
  output \5Y ,
  output \6Y 
);
  assign \1Y  = ~ \1A ;
  assign \2Y  = ~ \2A ;
  assign \3Y  = ~ \3A ;
  assign \4Y  = ~ \4A ;
  assign \5Y  = ~ \5A ;
  assign \6Y  = ~ \6A ;
endmodule

module Mux_8x1
(
    input [2:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    output reg out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


// 3-line to 8-line data selectors/multiplexers
module \74151  (
  input A,
  input C,
  input B,
  input S,
  input D0,
  input D1,
  input D2,
  input D3,
  input D4,
  input D5,
  input D6,
  input D7,
  input VCC,
  input GND,
  output Y,
  output W
);
  wire [2:0] s0;
  wire s1;
  wire Y_temp;
  assign s0[0] = A;
  assign s0[1] = B;
  assign s0[2] = C;
  Mux_8x1 Mux_8x1_i0 (
    .sel( s0 ),
    .in_0( D0 ),
    .in_1( D1 ),
    .in_2( D2 ),
    .in_3( D3 ),
    .in_4( D4 ),
    .in_5( D5 ),
    .in_6( D6 ),
    .in_7( D7 ),
    .out( s1 )
  );
  assign Y_temp = (~ S & s1);
  assign W = ~ Y_temp;
  assign Y = Y_temp;
endmodule

module sc_branch (
  input FLAG_N,
  input FLAG_C,
  input FLAG_Z,
  input FLAG_O,
  input [2:0] COND,
  input BRANCH_EN,
  output COND_RESULT
);
  wire MUX_Y;
  wire COND_2;
  wire COND_1;
  wire COND_0;
  wire MUX_D7;
  wire \3Y ;
  wire \2Y ;
  wire \1Y ;
  \7404  \7404_i0 (
    .\1A ( FLAG_Z ),
    .\2A ( FLAG_C ),
    .\3A ( FLAG_N ),
    .GND( 1'b0 ),
    .\4A ( FLAG_O ),
    .\5A ( 1'b0 ),
    .\6A ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( \1Y  ),
    .\2Y ( \2Y  ),
    .\3Y ( \3Y  ),
    .\4Y ( MUX_D7 )
  );
  assign COND_0 = COND[0];
  assign COND_1 = COND[1];
  assign COND_2 = COND[2];
  // U1
  \74151  \74151_i1 (
    .D3( FLAG_O ),
    .D2( FLAG_N ),
    .D1( FLAG_C ),
    .D0( FLAG_Z ),
    .S( 1'b0 ),
    .GND( 1'b0 ),
    .C( COND_2 ),
    .B( COND_1 ),
    .A( COND_0 ),
    .D7( MUX_D7 ),
    .D6( \3Y  ),
    .D5( \2Y  ),
    .D4( \1Y  ),
    .VCC( 1'b1 ),
    .Y( MUX_Y )
  );
  assign COND_RESULT = (MUX_Y & BRANCH_EN);
endmodule

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

// dual D-flip-flop
module \7474  (
  input \~1SD ,
  input \1D ,
  input \1CP ,
  input \~1RD ,
  input \~2SD ,
  input \2D ,
  input \2CP ,
  input \~2RD ,
  input VCC,
  input GND,
  output \1Q ,
  output \~1Q ,
  output \2Q ,
  output \~2Q 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s0 = ~ \~1SD ;
  assign s1 = ~ \~1RD ;
  assign s3 = ~ \~2SD ;
  assign s4 = ~ \~2RD ;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( s0 ),
    .D( \1D  ),
    .C( \1CP  ),
    .Clr( s1 ),
    .Q( \1Q  ),
    .\~Q ( s2 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( s3 ),
    .D( \2D  ),
    .C( \2CP  ),
    .Clr( s4 ),
    .Q( \2Q  ),
    .\~Q ( s5 )
  );
  assign \~1Q  = (s2 | (~ \~1SD  & ~ \~1RD ));
  assign \~2Q  = (s5 | (~ \~2SD  & ~ \~2RD ));
endmodule

module sc_control_flags (
  input INT_EN_IN,
  input HALT_IN,
  input INT_REQ,
  input INT_VEC_0,
  input INT_VEC_1,
  input INT_VEC_2,
  input CLK,
  output [23:0] INT_VECTOR,
  output INT_EN,
  output HALTED,
  output INT_GATE,
  output CLK_GATED
);
  wire INT_EN_temp;
  wire HALTED_temp;
  \7474  \7474_i0 (
    .\~1RD ( 1'b1 ),
    .\1D ( INT_EN_IN ),
    .\1CP ( CLK ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( CLK ),
    .\2D ( HALT_IN ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( INT_EN_temp ),
    .\2Q ( HALTED_temp )
  );
  assign INT_VECTOR[0] = 1'b0;
  assign INT_VECTOR[1] = 1'b0;
  assign INT_VECTOR[2] = 1'b0;
  assign INT_VECTOR[3] = INT_VEC_0;
  assign INT_VECTOR[4] = INT_VEC_1;
  assign INT_VECTOR[5] = INT_VEC_2;
  assign INT_VECTOR[6] = 1'b0;
  assign INT_VECTOR[7] = 1'b0;
  assign INT_VECTOR[8] = 1'b0;
  assign INT_VECTOR[9] = 1'b0;
  assign INT_VECTOR[10] = 1'b0;
  assign INT_VECTOR[11] = 1'b0;
  assign INT_VECTOR[12] = 1'b0;
  assign INT_VECTOR[13] = 1'b0;
  assign INT_VECTOR[14] = 1'b0;
  assign INT_VECTOR[15] = 1'b0;
  assign INT_VECTOR[16] = 1'b0;
  assign INT_VECTOR[17] = 1'b0;
  assign INT_VECTOR[18] = 1'b0;
  assign INT_VECTOR[19] = 1'b0;
  assign INT_VECTOR[20] = 1'b0;
  assign INT_VECTOR[21] = 1'b0;
  assign INT_VECTOR[22] = 1'b0;
  assign INT_VECTOR[23] = 1'b0;
  assign INT_GATE = (INT_REQ & INT_EN_temp);
  assign CLK_GATED = (CLK & ~ HALTED_temp);
  assign INT_EN = INT_EN_temp;
  assign HALTED = HALTED_temp;
endmodule

module sc_flags_save (
  input INT_GATE,
  input FLAG_N,
  input FLAG_C,
  input FLAG_Z,
  input FLAG_O,
  output [3:0] FLAGS_SAVE
);
  wire FLAGS_SAVE_Z;
  wire FLAGS_SAVE_C;
  wire FLAGS_SAVE_N;
  wire FLAGS_SAVE_O;
  \7474  \7474_i0 (
    .\~1RD ( 1'b1 ),
    .\1D ( FLAG_Z ),
    .\1CP ( INT_GATE ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( INT_GATE ),
    .\2D ( FLAG_C ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAGS_SAVE_Z ),
    .\2Q ( FLAGS_SAVE_C )
  );
  \7474  \7474_i1 (
    .\~1RD ( 1'b1 ),
    .\1D ( FLAG_N ),
    .\1CP ( INT_GATE ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( INT_GATE ),
    .\2D ( FLAG_O ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAGS_SAVE_N ),
    .\2Q ( FLAGS_SAVE_O )
  );
  assign FLAGS_SAVE[0] = FLAGS_SAVE_Z;
  assign FLAGS_SAVE[1] = FLAGS_SAVE_C;
  assign FLAGS_SAVE[2] = FLAGS_SAVE_N;
  assign FLAGS_SAVE[3] = FLAGS_SAVE_O;
endmodule

module sc_pc_counter (
  input \~SR ,
  input clk,
  input \~PE ,
  input [23:0] D,
  input \pc-en ,
  output [23:0] Q
);
  wire D_0;
  wire D_1;
  wire D_2;
  wire D_3;
  wire Q_3;
  wire Q_2;
  wire Q_1;
  wire Q_0;
  wire tc1;
  wire D_4;
  wire D_5;
  wire D_6;
  wire D_7;
  wire Q_7;
  wire Q_6;
  wire Q_5;
  wire Q_4;
  wire tc2;
  wire D_8;
  wire D_9;
  wire D_10;
  wire D_11;
  wire Q_11;
  wire Q_10;
  wire Q_9;
  wire Q_8;
  wire tc3;
  wire D_12;
  wire D_13;
  wire D_14;
  wire D_15;
  wire Q_15;
  wire Q_14;
  wire Q_13;
  wire Q_12;
  wire tc4;
  wire D_16;
  wire D_17;
  wire D_18;
  wire D_19;
  wire Q_19;
  wire Q_18;
  wire Q_17;
  wire Q_16;
  wire tc5;
  wire D_20;
  wire D_21;
  wire D_22;
  wire D_23;
  wire Q_23;
  wire Q_22;
  wire Q_21;
  wire Q_20;
  assign D_0 = D[0];
  assign D_1 = D[1];
  assign D_2 = D[2];
  assign D_3 = D[3];
  assign D_4 = D[4];
  assign D_5 = D[5];
  assign D_6 = D[6];
  assign D_7 = D[7];
  assign D_8 = D[8];
  assign D_9 = D[9];
  assign D_10 = D[10];
  assign D_11 = D[11];
  assign D_12 = D[12];
  assign D_13 = D[13];
  assign D_14 = D[14];
  assign D_15 = D[15];
  assign D_16 = D[16];
  assign D_17 = D[17];
  assign D_18 = D[18];
  assign D_19 = D[19];
  assign D_20 = D[20];
  assign D_21 = D[21];
  assign D_22 = D[22];
  assign D_23 = D[23];
  // U1
  \74163  \74163_i0 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_0 ),
    .P1( D_1 ),
    .P2( D_2 ),
    .P3( D_3 ),
    .CEP( \pc-en  ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( \pc-en  ),
    .VCC( 1'b1 ),
    .Q3( Q_3 ),
    .Q2( Q_2 ),
    .Q1( Q_1 ),
    .Q0( Q_0 ),
    .TC( tc1 )
  );
  // U2
  \74163  \74163_i1 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_4 ),
    .P1( D_5 ),
    .P2( D_6 ),
    .P3( D_7 ),
    .CEP( tc1 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc1 ),
    .VCC( 1'b1 ),
    .Q3( Q_7 ),
    .Q2( Q_6 ),
    .Q1( Q_5 ),
    .Q0( Q_4 ),
    .TC( tc2 )
  );
  // U3
  \74163  \74163_i2 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_8 ),
    .P1( D_9 ),
    .P2( D_10 ),
    .P3( D_11 ),
    .CEP( tc2 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc2 ),
    .VCC( 1'b1 ),
    .Q3( Q_11 ),
    .Q2( Q_10 ),
    .Q1( Q_9 ),
    .Q0( Q_8 ),
    .TC( tc3 )
  );
  // U4
  \74163  \74163_i3 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_12 ),
    .P1( D_13 ),
    .P2( D_14 ),
    .P3( D_15 ),
    .CEP( tc3 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc3 ),
    .VCC( 1'b1 ),
    .Q3( Q_15 ),
    .Q2( Q_14 ),
    .Q1( Q_13 ),
    .Q0( Q_12 ),
    .TC( tc4 )
  );
  // U5
  \74163  \74163_i4 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_16 ),
    .P1( D_17 ),
    .P2( D_18 ),
    .P3( D_19 ),
    .CEP( tc4 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc4 ),
    .VCC( 1'b1 ),
    .Q3( Q_19 ),
    .Q2( Q_18 ),
    .Q1( Q_17 ),
    .Q0( Q_16 ),
    .TC( tc5 )
  );
  // U6
  \74163  \74163_i5 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_20 ),
    .P1( D_21 ),
    .P2( D_22 ),
    .P3( D_23 ),
    .CEP( tc5 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc5 ),
    .VCC( 1'b1 ),
    .Q3( Q_23 ),
    .Q2( Q_22 ),
    .Q1( Q_21 ),
    .Q0( Q_20 )
  );
  assign Q[0] = Q_0;
  assign Q[1] = Q_1;
  assign Q[2] = Q_2;
  assign Q[3] = Q_3;
  assign Q[4] = Q_4;
  assign Q[5] = Q_5;
  assign Q[6] = Q_6;
  assign Q[7] = Q_7;
  assign Q[8] = Q_8;
  assign Q[9] = Q_9;
  assign Q[10] = Q_10;
  assign Q[11] = Q_11;
  assign Q[12] = Q_12;
  assign Q[13] = Q_13;
  assign Q[14] = Q_14;
  assign Q[15] = Q_15;
  assign Q[16] = Q_16;
  assign Q[17] = Q_17;
  assign Q[18] = Q_18;
  assign Q[19] = Q_19;
  assign Q[20] = Q_20;
  assign Q[21] = Q_21;
  assign Q[22] = Q_22;
  assign Q[23] = Q_23;
endmodule

// 4-bit binary full adder, alternative pinning
module \74283  (
  input C0,
  input B1,
  input B2,
  input B3,
  input B4,
  input A1,
  input A2,
  input A3,
  input A4,
  input VCC,
  input GND,
  output S1,
  output S2,
  output S3,
  output S4,
  output C4
);
  wire [3:0] s0;
  wire [3:0] s5;
  wire [3:0] s6;
  assign s5[0] = B1;
  assign s5[1] = B2;
  assign s5[2] = B3;
  assign s5[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i0 (
    .a( s0 ),
    .b( s5 ),
    .c_i( C0 ),
    .s( s6 ),
    .c_o( C4 )
  );
  assign S1 = s6[0];
  assign S2 = s6[1];
  assign S3 = s6[2];
  assign S4 = s6[3];
endmodule

module sc_adder24 (
  input [23:0] B,
  input [23:0] A,
  output [23:0] S
);
  wire A_0;
  wire A_1;
  wire A_2;
  wire A_3;
  wire A_4;
  wire A_5;
  wire A_6;
  wire A_7;
  wire A_8;
  wire A_9;
  wire A_10;
  wire A_11;
  wire A_12;
  wire A_13;
  wire A_14;
  wire A_15;
  wire A_16;
  wire A_17;
  wire A_18;
  wire A_19;
  wire A_20;
  wire A_21;
  wire A_22;
  wire A_23;
  wire S_1;
  wire B_1;
  wire S_0;
  wire B_0;
  wire C_1;
  wire S_3;
  wire B_3;
  wire S_2;
  wire B_2;
  wire S_5;
  wire B_5;
  wire S_4;
  wire B_4;
  wire C_2;
  wire S_7;
  wire B_7;
  wire S_6;
  wire B_6;
  wire S_9;
  wire B_9;
  wire S_8;
  wire B_8;
  wire C_3;
  wire S_11;
  wire B_11;
  wire S_10;
  wire B_10;
  wire S_13;
  wire B_13;
  wire S_12;
  wire B_12;
  wire C_4;
  wire S_15;
  wire B_15;
  wire S_14;
  wire B_14;
  wire S_17;
  wire B_17;
  wire S_16;
  wire B_16;
  wire C_5;
  wire S_19;
  wire B_19;
  wire S_18;
  wire B_18;
  wire S_21;
  wire B_21;
  wire S_20;
  wire B_20;
  wire S_23;
  wire B_23;
  wire S_22;
  wire B_22;
  assign A_0 = A[0];
  assign A_1 = A[1];
  assign A_2 = A[2];
  assign A_3 = A[3];
  assign A_4 = A[4];
  assign A_5 = A[5];
  assign A_6 = A[6];
  assign A_7 = A[7];
  assign A_8 = A[8];
  assign A_9 = A[9];
  assign A_10 = A[10];
  assign A_11 = A[11];
  assign A_12 = A[12];
  assign A_13 = A[13];
  assign A_14 = A[14];
  assign A_15 = A[15];
  assign A_16 = A[16];
  assign A_17 = A[17];
  assign A_18 = A[18];
  assign A_19 = A[19];
  assign A_20 = A[20];
  assign A_21 = A[21];
  assign A_22 = A[22];
  assign A_23 = A[23];
  assign B_0 = B[0];
  assign B_1 = B[1];
  assign B_2 = B[2];
  assign B_3 = B[3];
  assign B_4 = B[4];
  assign B_5 = B[5];
  assign B_6 = B[6];
  assign B_7 = B[7];
  assign B_8 = B[8];
  assign B_9 = B[9];
  assign B_10 = B[10];
  assign B_11 = B[11];
  assign B_12 = B[12];
  assign B_13 = B[13];
  assign B_14 = B[14];
  assign B_15 = B[15];
  assign B_16 = B[16];
  assign B_17 = B[17];
  assign B_18 = B[18];
  assign B_19 = B[19];
  assign B_20 = B[20];
  assign B_21 = B[21];
  assign B_22 = B[22];
  assign B_23 = B[23];
  // U1
  \74283  \74283_i0 (
    .B2( B_1 ),
    .A2( A_1 ),
    .A1( A_0 ),
    .B1( B_0 ),
    .C0( 1'b0 ),
    .GND( 1'b0 ),
    .B4( B_3 ),
    .A4( A_3 ),
    .A3( A_2 ),
    .B3( B_2 ),
    .VCC( 1'b1 ),
    .S2( S_1 ),
    .S1( S_0 ),
    .C4( C_1 ),
    .S4( S_3 ),
    .S3( S_2 )
  );
  // U2
  \74283  \74283_i1 (
    .B2( B_5 ),
    .A2( A_5 ),
    .A1( A_4 ),
    .B1( B_4 ),
    .C0( C_1 ),
    .GND( 1'b0 ),
    .B4( B_7 ),
    .A4( A_7 ),
    .A3( A_6 ),
    .B3( B_6 ),
    .VCC( 1'b1 ),
    .S2( S_5 ),
    .S1( S_4 ),
    .C4( C_2 ),
    .S4( S_7 ),
    .S3( S_6 )
  );
  // U3
  \74283  \74283_i2 (
    .B2( B_9 ),
    .A2( A_9 ),
    .A1( A_8 ),
    .B1( B_8 ),
    .C0( C_2 ),
    .GND( 1'b0 ),
    .B4( B_11 ),
    .A4( A_11 ),
    .A3( A_10 ),
    .B3( B_10 ),
    .VCC( 1'b1 ),
    .S2( S_9 ),
    .S1( S_8 ),
    .C4( C_3 ),
    .S4( S_11 ),
    .S3( S_10 )
  );
  // U4
  \74283  \74283_i3 (
    .B2( B_13 ),
    .A2( A_13 ),
    .A1( A_12 ),
    .B1( B_12 ),
    .C0( C_3 ),
    .GND( 1'b0 ),
    .B4( B_15 ),
    .A4( A_15 ),
    .A3( A_14 ),
    .B3( B_14 ),
    .VCC( 1'b1 ),
    .S2( S_13 ),
    .S1( S_12 ),
    .C4( C_4 ),
    .S4( S_15 ),
    .S3( S_14 )
  );
  // U5
  \74283  \74283_i4 (
    .B2( B_17 ),
    .A2( A_17 ),
    .A1( A_16 ),
    .B1( B_16 ),
    .C0( C_4 ),
    .GND( 1'b0 ),
    .B4( B_19 ),
    .A4( A_19 ),
    .A3( A_18 ),
    .B3( B_18 ),
    .VCC( 1'b1 ),
    .S2( S_17 ),
    .S1( S_16 ),
    .C4( C_5 ),
    .S4( S_19 ),
    .S3( S_18 )
  );
  // U6
  \74283  \74283_i5 (
    .B2( B_21 ),
    .A2( A_21 ),
    .A1( A_20 ),
    .B1( B_20 ),
    .C0( C_5 ),
    .GND( 1'b0 ),
    .B4( B_23 ),
    .A4( A_23 ),
    .A3( A_22 ),
    .B3( B_22 ),
    .VCC( 1'b1 ),
    .S2( S_21 ),
    .S1( S_20 ),
    .S4( S_23 ),
    .S3( S_22 )
  );
  assign S[0] = S_0;
  assign S[1] = S_1;
  assign S[2] = S_2;
  assign S[3] = S_3;
  assign S[4] = S_4;
  assign S[5] = S_5;
  assign S[6] = S_6;
  assign S[7] = S_7;
  assign S[8] = S_8;
  assign S[9] = S_9;
  assign S[10] = S_10;
  assign S[11] = S_11;
  assign S[12] = S_12;
  assign S[13] = S_13;
  assign S[14] = S_14;
  assign S[15] = S_15;
  assign S[16] = S_16;
  assign S[17] = S_17;
  assign S[18] = S_18;
  assign S[19] = S_19;
  assign S[20] = S_20;
  assign S[21] = S_21;
  assign S[22] = S_22;
  assign S[23] = S_23;
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module pc (
  input CLK,
  input \~SR ,
  input [23:0] ADDR_ABS,
  input [23:0] OFFSET,
  input [23:0] ADDR_RET,
  input MUX1_SEL,
  input MUX2_SEL,
  input FLAG_N,
  input FLAG_C,
  input FLAG_Z,
  input FLAG_O,
  input [2:0] COND,
  input BRANCH_EN,
  input INT_EN_IN,
  input HALT_IN,
  input INT_REQ,
  input INT_VEC_0,
  input INT_VEC_1,
  input INT_VEC_2,
  input [23:0] SP_DELTA,
  input SP_LOAD_N,
  input JUMP_UNCOND,
  input PCEN,
  output INT_EN,
  output HALTED,
  output [23:0] PC_OUT,
  output [23:0] SP_OUT,
  output INT_ACK,
  output [3:0] FLAGS_SAVE,
  output [23:0] PC_SAVE
);
  wire CLK_GATED;
  wire PC_LOAD_N;
  wire [23:0] LOAD_ADDR;
  wire [23:0] PC_OUT_temp;
  wire [23:0] SP_OUT_temp;
  wire [23:0] SP_D;
  wire COND_RESULT;
  wire [23:0] PC_REL;
  wire [23:0] INT_VECTOR;
  wire INT_ACK_temp;
  wire [23:0] \PC+1 ;
  wire [1:0] \mux-sel ;
  // SC4-1
  sc_branch sc_branch_i0 (
    .FLAG_N( FLAG_N ),
    .FLAG_C( FLAG_C ),
    .FLAG_Z( FLAG_Z ),
    .FLAG_O( FLAG_O ),
    .COND( COND ),
    .BRANCH_EN( BRANCH_EN ),
    .COND_RESULT( COND_RESULT )
  );
  // SC5-1
  sc_control_flags sc_control_flags_i1 (
    .INT_EN_IN( INT_EN_IN ),
    .HALT_IN( HALT_IN ),
    .INT_REQ( INT_REQ ),
    .INT_VEC_0( INT_VEC_0 ),
    .INT_VEC_1( INT_VEC_1 ),
    .INT_VEC_2( INT_VEC_2 ),
    .CLK( CLK ),
    .INT_VECTOR( INT_VECTOR ),
    .INT_EN( INT_EN ),
    .HALTED( HALTED ),
    .INT_GATE( INT_ACK_temp ),
    .CLK_GATED( CLK_GATED )
  );
  assign \PC+1 [0] = 1'b1;
  assign \PC+1 [1] = 1'b0;
  assign \PC+1 [2] = 1'b0;
  assign \PC+1 [3] = 1'b0;
  assign \PC+1 [4] = 1'b0;
  assign \PC+1 [5] = 1'b0;
  assign \PC+1 [6] = 1'b0;
  assign \PC+1 [7] = 1'b0;
  assign \PC+1 [8] = 1'b0;
  assign \PC+1 [9] = 1'b0;
  assign \PC+1 [10] = 1'b0;
  assign \PC+1 [11] = 1'b0;
  assign \PC+1 [12] = 1'b0;
  assign \PC+1 [13] = 1'b0;
  assign \PC+1 [14] = 1'b0;
  assign \PC+1 [15] = 1'b0;
  assign \PC+1 [16] = 1'b0;
  assign \PC+1 [17] = 1'b0;
  assign \PC+1 [18] = 1'b0;
  assign \PC+1 [19] = 1'b0;
  assign \PC+1 [20] = 1'b0;
  assign \PC+1 [21] = 1'b0;
  assign \PC+1 [22] = 1'b0;
  assign \PC+1 [23] = 1'b0;
  // SC6-1
  sc_flags_save sc_flags_save_i2 (
    .INT_GATE( INT_ACK_temp ),
    .FLAG_N( FLAG_N ),
    .FLAG_C( FLAG_C ),
    .FLAG_Z( FLAG_Z ),
    .FLAG_O( FLAG_O ),
    .FLAGS_SAVE( FLAGS_SAVE )
  );
  assign PC_LOAD_N = ~ (COND_RESULT | INT_ACK_temp | JUMP_UNCOND);
  assign \mux-sel [0] = (INT_ACK_temp | (~ MUX2_SEL & MUX1_SEL));
  assign \mux-sel [1] = (MUX2_SEL | INT_ACK_temp);
  // SC1-1
  sc_pc_counter sc_pc_counter_i3 (
    .\~SR ( \~SR  ),
    .clk( CLK_GATED ),
    .\~PE ( PC_LOAD_N ),
    .D( LOAD_ADDR ),
    .\pc-en ( PCEN ),
    .Q( PC_OUT_temp )
  );
  // SC2-2
  sc_adder24 sc_adder24_i4 (
    .B( SP_DELTA ),
    .A( SP_OUT_temp ),
    .S( SP_D )
  );
  // SC1-2
  sc_pc_counter sc_pc_counter_i5 (
    .\~SR ( \~SR  ),
    .clk( CLK_GATED ),
    .\~PE ( SP_LOAD_N ),
    .D( SP_D ),
    .\pc-en ( PCEN ),
    .Q( SP_OUT_temp )
  );
  // SC2-1
  sc_adder24 sc_adder24_i6 (
    .B( OFFSET ),
    .A( PC_OUT_temp ),
    .S( PC_REL )
  );
  // SC2-3
  sc_adder24 sc_adder24_i7 (
    .B( \PC+1  ),
    .A( PC_OUT_temp ),
    .S( PC_SAVE )
  );
  Mux_4x1_NBits #(
    .Bits(24)
  )
  Mux_4x1_NBits_i8 (
    .sel( \mux-sel  ),
    .in_0( ADDR_ABS ),
    .in_1( PC_REL ),
    .in_2( ADDR_RET ),
    .in_3( INT_VECTOR ),
    .out( LOAD_ADDR )
  );
  assign PC_OUT = PC_OUT_temp;
  assign SP_OUT = SP_OUT_temp;
  assign INT_ACK = INT_ACK_temp;
endmodule
module DIG_RAMDualAccess
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
    input C, // Clock signal
    input ld,
    input [(AddrBits-1):0] \1A ,
    input [(AddrBits-1):0] \2A ,
    input [(Bits-1):0] \1Din ,
    input str,
    output [(Bits-1):0] \1D ,
    output [(Bits-1):0] \2D
);
    // CAUTION: uses distributed RAM
    reg [(Bits-1):0] memory [0:((1 << AddrBits)-1)];

    assign \1D = ld? memory[\1A ] : 'hz;
    assign \2D = memory[\2A ];

    always @ (posedge C) begin
        if (str)
            memory[\1A ] <= \1Din ;
    end

endmodule



module register (
  input WE,
  input [31:0] DATA_W,
  input [7:0] ADDR_A,
  input [7:0] ADDR_B,
  input [7:0] ADDR_W,
  input EXEC,
  input addr_c_sel,
  input [31:0] ir_bus,
  input clk,
  output [31:0] DATA_A,
  output [31:0] DATA_B,
  output [31:0] DATA_C
);
  wire \ram-and ;
  wire [7:0] ADDR_C;
  wire [7:0] \0x00 ;
  wire [7:0] IR_ADDR_CIN;
  assign \ram-and  = (EXEC & WE);
  assign \0x00 [0] = 1'b0;
  assign \0x00 [1] = 1'b0;
  assign \0x00 [2] = 1'b0;
  assign \0x00 [3] = 1'b0;
  assign \0x00 [4] = 1'b0;
  assign \0x00 [5] = 1'b0;
  assign \0x00 [6] = 1'b0;
  assign \0x00 [7] = 1'b0;
  assign IR_ADDR_CIN = ir_bus[23:16];
  // U1
  DIG_RAMDualAccess #(
    .Bits(32),
    .AddrBits(8)
  )
  DIG_RAMDualAccess_i0 (
    .str( \ram-and  ),
    .C( clk ),
    .ld( 1'b1 ),
    .\1A ( ADDR_W ),
    .\1Din ( DATA_W ),
    .\2A ( ADDR_A ),
    .\2D ( DATA_A )
  );
  // U2
  DIG_RAMDualAccess #(
    .Bits(32),
    .AddrBits(8)
  )
  DIG_RAMDualAccess_i1 (
    .str( \ram-and  ),
    .C( clk ),
    .ld( 1'b1 ),
    .\1A ( ADDR_W ),
    .\1Din ( DATA_W ),
    .\2A ( ADDR_B ),
    .\2D ( DATA_B )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i2 (
    .sel( addr_c_sel ),
    .in_0( \0x00  ),
    .in_1( IR_ADDR_CIN ),
    .out( ADDR_C )
  );
  // U3
  DIG_RAMDualAccess #(
    .Bits(32),
    .AddrBits(8)
  )
  DIG_RAMDualAccess_i3 (
    .str( \ram-and  ),
    .C( clk ),
    .ld( 1'b1 ),
    .\1A ( ADDR_W ),
    .\1Din ( DATA_W ),
    .\2A ( ADDR_C ),
    .\2D ( DATA_C )
  );
endmodule

module flag_reg (
  input ZERO_IN,
  input CARRY_IN,
  input NEGATIVE_IN,
  input OVERFLOW_IN,
  input FLAG_WE,
  input CLK,
  input EXEC,
  output FLAG_Z,
  output FLAG_C,
  output FLAG_N,
  output FLAG_O
);
  wire CLK_GATED;
  wire FLAG_Z_N;
  wire FLAG_C_N;
  wire FLAG_NN;
  wire FLAG_O_N;
  assign CLK_GATED = (CLK & EXEC & FLAG_WE);
  \7474  \7474_i0 (
    .\~1RD ( 1'b1 ),
    .\1D ( ZERO_IN ),
    .\1CP ( CLK_GATED ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( CLK_GATED ),
    .\2D ( CARRY_IN ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAG_Z ),
    .\~1Q ( FLAG_Z_N ),
    .\~2Q ( FLAG_C_N ),
    .\2Q ( FLAG_C )
  );
  \7474  \7474_i1 (
    .\~1RD ( 1'b1 ),
    .\1D ( NEGATIVE_IN ),
    .\1CP ( CLK_GATED ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( CLK_GATED ),
    .\2D ( OVERFLOW_IN ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAG_N ),
    .\~1Q ( FLAG_NN ),
    .\~2Q ( FLAG_O_N ),
    .\2Q ( FLAG_O )
  );
endmodule

module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module wb_mux (
  input [2:0] wb_sel,
  input [31:0] alu_out,
  input [31:0] shift_out,
  input [23:0] pc_save,
  input [31:0] mem_din,
  input [31:0] io_datain,
  input [31:0] reg_a,
  input [31:0] \ir-bus ,
  output [31:0] reg_w_data
);
  wire [31:0] pc_save_32;
  wire [31:0] \ir-bus(8-23) ;
  wire [31:0] \ir-bus(0-23) ;
  assign pc_save_32[23:0] = pc_save;
  assign pc_save_32[31:24] = 8'b0;
  assign \ir-bus(8-23) [15:0] = \ir-bus [23:8];
  assign \ir-bus(8-23) [31:16] = 16'b0;
  assign \ir-bus(0-23) [23:0] = \ir-bus [23:0];
  assign \ir-bus(0-23) [31:24] = 8'b0;
  Mux_8x1_NBits #(
    .Bits(32)
  )
  Mux_8x1_NBits_i0 (
    .sel( wb_sel ),
    .in_0( alu_out ),
    .in_1( shift_out ),
    .in_2( pc_save_32 ),
    .in_3( mem_din ),
    .in_4( io_datain ),
    .in_5( reg_a ),
    .in_6( \ir-bus(8-23)  ),
    .in_7( \ir-bus(0-23)  ),
    .out( reg_w_data )
  );
endmodule

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module ir (
  input [31:0] DATA_IN,
  input LOAD,
  input CLK,
  output [31:0] IR_BUS,
  output [7:0] OPCODE,
  output [7:0] ADDR_A,
  output [7:0] ADDR_B,
  output [7:0] ADDR_W,
  output [23:0] ADDR_ABS,
  output [23:0] OFFSET,
  output [2:0] COND,
  output MUX1_SEL,
  output MUX2_SEL
);
  wire [31:0] IR_BUS_temp;
  wire [23:0] OFFSET_temp;
  DIG_Register_BUS #(
    .Bits(32)
  )
  DIG_Register_BUS_i0 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( LOAD ),
    .Q( IR_BUS_temp )
  );
  assign OPCODE = IR_BUS_temp[31:24];
  assign ADDR_A = IR_BUS_temp[23:16];
  assign ADDR_B = IR_BUS_temp[15:8];
  assign ADDR_W = IR_BUS_temp[7:0];
  assign OFFSET_temp = IR_BUS_temp[23:0];
  assign COND = IR_BUS_temp[2:0];
  assign MUX1_SEL = IR_BUS_temp[0];
  assign MUX2_SEL = IR_BUS_temp[1];
  assign IR_BUS = IR_BUS_temp;
  assign ADDR_ABS = OFFSET_temp;
  assign OFFSET = OFFSET_temp;
endmodule

module bus_arbitration (
  input FETCH,
  input [23:0] PC_OUT,
  input [23:0] IR_ADDR,
  input [31:0] Reg_A,
  input MEM_RD_IN,
  input [2:0] addr_sel,
  input [31:0] Reg_b,
  input [31:0] \Reg-A-off ,
  input [31:0] \Reg-B-off ,
  input [31:0] \Reg-AB ,
  input [31:0] \PC-offset ,
  input [31:0] \SP-out ,
  input [31:0] \Alu-in ,
  output [23:0] ADDR_BUS,
  output MEM_RD_OUT
);
  wire [23:0] s_reg_a;
  wire [23:0] s_reg_b;
  wire [23:0] \reg-a-offset ;
  wire [23:0] \reg-b-offset ;
  wire [23:0] s_\pc-offset ;
  wire [23:0] \reg-a-b ;
  wire [23:0] s_\sp-out ;
  wire [23:0] \alu-out ;
  assign MEM_RD_OUT = (MEM_RD_IN | FETCH);
  assign s_reg_a = Reg_A[23:0];
  assign s_reg_b = Reg_b[23:0];
  assign \reg-a-offset  = \Reg-A-off [23:0];
  assign \reg-b-offset  = \Reg-B-off [23:0];
  assign \reg-a-b  = \Reg-AB [23:0];
  assign s_\pc-offset  = \PC-offset [23:0];
  assign s_\sp-out  = \SP-out [23:0];
  assign \alu-out  = \Alu-in [23:0];
  Mux_8x1_NBits #(
    .Bits(24)
  )
  Mux_8x1_NBits_i0 (
    .sel( addr_sel ),
    .in_0( IR_ADDR ),
    .in_1( s_reg_a ),
    .in_2( s_reg_b ),
    .in_3( \reg-a-offset  ),
    .in_4( \reg-b-offset  ),
    .in_5( s_\pc-offset  ),
    .in_6( \reg-a-b  ),
    .in_7( s_\sp-out  ),
    .out( ADDR_BUS )
  );
endmodule
module DIG_ROM_256X48_microcodeeeprom (
    input [7:0] A,
    input sel,
    output reg [47:0] D
);
    reg [47:0] my_rom [0:255];

    always @ (*) begin
        if (~sel)
            D = 48'hz;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 48'h8000000;
        my_rom[1] = 48'h100c0596;
        my_rom[2] = 48'h100c0769;
        my_rom[3] = 48'h100c0588;
        my_rom[4] = 48'h100c05ee;
        my_rom[5] = 48'h100c0566;
        my_rom[6] = 48'h100c0133;
        my_rom[7] = 48'h100c0796;
        my_rom[8] = 48'h100c1d96;
        my_rom[9] = 48'h100c1796;
        my_rom[10] = 48'h100c1d96;
        my_rom[11] = 48'h100c1096;
        my_rom[12] = 48'h100c2596;
        my_rom[13] = 48'h100c2296;
        my_rom[14] = 48'h100c2a96;
        my_rom[15] = 48'h100c0f96;
        my_rom[16] = 48'h100c4000;
        my_rom[17] = 48'h100d4000;
        my_rom[18] = 48'h100e4000;
        my_rom[19] = 48'h100f4000;
        my_rom[20] = 48'h100c4000;
        my_rom[21] = 48'h104c1500;
        my_rom[22] = 48'h104c1502;
        my_rom[23] = 48'h104c1503;
        my_rom[24] = 48'h104c1504;
        my_rom[25] = 48'h104c1505;
        my_rom[26] = 48'h104c1506;
        my_rom[27] = 48'h104c1508;
        my_rom[28] = 48'h104c1509;
        my_rom[29] = 48'h104c150b;
        my_rom[30] = 48'h104c150c;
        my_rom[31] = 48'h104c150d;
        my_rom[32] = 48'h1818c000;
        my_rom[33] = 48'h18200000;
        my_rom[34] = 48'h300804cc;
        my_rom[35] = 48'h5818c000;
        my_rom[36] = 48'h58200000;
        my_rom[37] = 48'h104c150e;
        my_rom[38] = 48'h104c150f;
        my_rom[39] = 48'h104c1510;
        my_rom[40] = 48'h104c1511;
        my_rom[41] = 48'h104c1512;
        my_rom[42] = 48'h104c1513;
        my_rom[43] = 48'h104c1514;
        my_rom[44] = 48'h104c1515;
        my_rom[45] = 48'h104c1518;
        my_rom[46] = 48'h104c1519;
        my_rom[47] = 48'h104c151a;
        my_rom[48] = 48'h11800000;
        my_rom[49] = 48'h10800000;
        my_rom[50] = 48'h13888000;
        my_rom[51] = 48'h11800000;
        my_rom[52] = 48'h100c0596;
        my_rom[53] = 48'h100c2d96;
        my_rom[54] = 48'h100c2b96;
        my_rom[55] = 48'h100c0c96;
        my_rom[56] = 48'h100c0e96;
        my_rom[57] = 48'h100c2f96;
        my_rom[58] = 48'h100c0896;
        my_rom[59] = 48'h100c2696;
        my_rom[60] = 48'h100c0196;
        my_rom[61] = 48'h100c0496;
        my_rom[62] = 48'h104c151c;
        my_rom[63] = 48'h104c151d;
        my_rom[64] = 48'h104c1540;
        my_rom[65] = 48'h104c1541;
        my_rom[66] = 48'h104c1542;
        my_rom[67] = 48'h104c1543;
        my_rom[68] = 48'h104c1544;
        my_rom[69] = 48'h104c1545;
        my_rom[70] = 48'h104c1546;
        my_rom[71] = 48'h104c1547;
        my_rom[72] = 48'h104c1548;
        my_rom[73] = 48'h104c1549;
        my_rom[74] = 48'h104c154a;
        my_rom[75] = 48'h104c154b;
        my_rom[76] = 48'h104c154c;
        my_rom[77] = 48'h104c154d;
        my_rom[78] = 48'h104c154e;
        my_rom[79] = 48'h104c154f;
        my_rom[80] = 48'h104c1550;
        my_rom[81] = 48'h104c1551;
        my_rom[82] = 48'h104c1552;
        my_rom[83] = 48'h104c1553;
        my_rom[84] = 48'h104c1554;
        my_rom[85] = 48'h104c1555;
        my_rom[86] = 48'h104c1556;
        my_rom[87] = 48'h104c1557;
        my_rom[88] = 48'h104c1558;
        my_rom[89] = 48'h104c1559;
        my_rom[90] = 48'h104c155a;
        my_rom[91] = 48'h104c155b;
        my_rom[92] = 48'h104c155c;
        my_rom[93] = 48'h104c155d;
        my_rom[94] = 48'h104c155e;
        my_rom[95] = 48'h104c155f;
        my_rom[96] = 48'h104c1501;
        my_rom[97] = 48'h104c1517;
        my_rom[98] = 48'h104c1516;
        my_rom[99] = 48'h104c151b;
        my_rom[100] = 48'h104c1527;
        my_rom[101] = 48'h104c1528;
        my_rom[102] = 48'h104c1536;
        my_rom[103] = 48'h104c1556;
        my_rom[104] = 48'h104c1555;
        my_rom[105] = 48'h104c155a;
        my_rom[106] = 48'h104c15e8;
        my_rom[107] = 48'h104c15d8;
        my_rom[108] = 48'h104c1507;
        my_rom[109] = 48'h104c150a;
        my_rom[110] = 48'h104c1544;
        my_rom[111] = 48'h104c1550;
        my_rom[112] = 48'h100c0096;
        my_rom[113] = 48'h100c2196;
        my_rom[114] = 48'h100c2396;
        my_rom[115] = 48'h100c2496;
        my_rom[116] = 48'h100c2796;
        my_rom[117] = 48'h100c0996;
        my_rom[118] = 48'h100c0d96;
        my_rom[119] = 48'h100c2d96;
        my_rom[120] = 48'h100c0596;
        my_rom[121] = 48'h100c2596;
        my_rom[122] = 48'h104c151e;
        my_rom[123] = 48'h104c151f;
        my_rom[124] = 48'h104c1520;
        my_rom[125] = 48'h104c1521;
        my_rom[126] = 48'h104c1522;
        my_rom[127] = 48'h104c1523;
        my_rom[128] = 48'h104c1524;
        my_rom[129] = 48'h104c1525;
        my_rom[130] = 48'h104c1526;
        my_rom[131] = 48'h104c1529;
        my_rom[132] = 48'h104c152a;
        my_rom[133] = 48'h104c152b;
        my_rom[134] = 48'h104c152c;
        my_rom[135] = 48'h104c152d;
        my_rom[136] = 48'h104c152e;
        my_rom[137] = 48'h104c152f;
        my_rom[138] = 48'h104c1530;
        my_rom[139] = 48'h104c1531;
        my_rom[140] = 48'h104c1532;
        my_rom[141] = 48'h104c1533;
        my_rom[142] = 48'h104c1534;
        my_rom[143] = 48'h104c1535;
        my_rom[144] = 48'h100c0590;
        my_rom[145] = 48'h100c0591;
        my_rom[146] = 48'h100c0592;
        my_rom[147] = 48'h100c0593;
        my_rom[148] = 48'h100c0594;
        my_rom[149] = 48'h100c0595;
        my_rom[150] = 48'h100c0596;
        my_rom[151] = 48'h100c0597;
        my_rom[152] = 48'h100c0598;
        my_rom[153] = 48'h100c0599;
        my_rom[154] = 48'h100c059a;
        my_rom[155] = 48'h100c059b;
        my_rom[156] = 48'h100c059c;
        my_rom[157] = 48'h100c059d;
        my_rom[158] = 48'h100c059e;
        my_rom[159] = 48'h100c059f;
        my_rom[160] = 48'h100c05a0;
        my_rom[161] = 48'h100c05a1;
        my_rom[162] = 48'h100c05a2;
        my_rom[163] = 48'h100c05a3;
        my_rom[164] = 48'h100c05a4;
        my_rom[165] = 48'h100c05a5;
        my_rom[166] = 48'h100c05a6;
        my_rom[167] = 48'h100c05a7;
        my_rom[168] = 48'h100c05a8;
        my_rom[169] = 48'h100c05a9;
        my_rom[170] = 48'h100c05aa;
        my_rom[171] = 48'h100c05ab;
        my_rom[172] = 48'h100c05ac;
        my_rom[173] = 48'h100c05ad;
        my_rom[174] = 48'h100c05ae;
        my_rom[175] = 48'h100c05af;
        my_rom[176] = 48'h100c05b0;
        my_rom[177] = 48'h100c05b1;
        my_rom[178] = 48'h100c05b2;
        my_rom[179] = 48'h100c05b3;
        my_rom[180] = 48'h100c05b4;
        my_rom[181] = 48'h100c05b5;
        my_rom[182] = 48'h100c05b6;
        my_rom[183] = 48'h100c05b7;
        my_rom[184] = 48'h100c05b8;
        my_rom[185] = 48'h100c05b9;
        my_rom[186] = 48'h100c05ba;
        my_rom[187] = 48'h100c05bb;
        my_rom[188] = 48'h100c05bc;
        my_rom[189] = 48'h100c05bd;
        my_rom[190] = 48'h100c05be;
        my_rom[191] = 48'h100c05bf;
        my_rom[192] = 48'h100c0585;
        my_rom[193] = 48'h100c05c1;
        my_rom[194] = 48'h100c05c2;
        my_rom[195] = 48'h100c0588;
        my_rom[196] = 48'h100c05c4;
        my_rom[197] = 48'h100c05c5;
        my_rom[198] = 48'h100c05c6;
        my_rom[199] = 48'h100c05c7;
        my_rom[200] = 48'h100c05c8;
        my_rom[201] = 48'h100c05c9;
        my_rom[202] = 48'h100c05ca;
        my_rom[203] = 48'h100c05cb;
        my_rom[204] = 48'h100c05cc;
        my_rom[205] = 48'h100c05cd;
        my_rom[206] = 48'h100c05ce;
        my_rom[207] = 48'h100c05cf;
        my_rom[208] = 48'h100c05d0;
        my_rom[209] = 48'h100c05d1;
        my_rom[210] = 48'h100c05d2;
        my_rom[211] = 48'h100c05d3;
        my_rom[212] = 48'h100c05d4;
        my_rom[213] = 48'h100c05d5;
        my_rom[214] = 48'h100c05d6;
        my_rom[215] = 48'h100c05d7;
        my_rom[216] = 48'h100c05d8;
        my_rom[217] = 48'h100c05d9;
        my_rom[218] = 48'h100c05da;
        my_rom[219] = 48'h100c05db;
        my_rom[220] = 48'h100c05dc;
        my_rom[221] = 48'h100c05dd;
        my_rom[222] = 48'h100c05de;
        my_rom[223] = 48'h100c05df;
        my_rom[224] = 48'h100c05e0;
        my_rom[225] = 48'h100c05e1;
        my_rom[226] = 48'h100c05e2;
        my_rom[227] = 48'h100c05e3;
        my_rom[228] = 48'h100c05e4;
        my_rom[229] = 48'h100c05e5;
        my_rom[230] = 48'h100c05e6;
        my_rom[231] = 48'h100c05e7;
        my_rom[232] = 48'h100c05e8;
        my_rom[233] = 48'h100c05e9;
        my_rom[234] = 48'h100c05ea;
        my_rom[235] = 48'h100c05eb;
        my_rom[236] = 48'h100c05ec;
        my_rom[237] = 48'h100c05ed;
        my_rom[238] = 48'h100c05ee;
        my_rom[239] = 48'h100c05ef;
        my_rom[240] = 48'h100c05f0;
        my_rom[241] = 48'h100c05f1;
        my_rom[242] = 48'h100c05f2;
        my_rom[243] = 48'h100c05f3;
        my_rom[244] = 48'h100c05f4;
        my_rom[245] = 48'h100c05f5;
        my_rom[246] = 48'h100c05f6;
        my_rom[247] = 48'h100c05f7;
        my_rom[248] = 48'h100c05f8;
        my_rom[249] = 48'h100c05f9;
        my_rom[250] = 48'h100c05fa;
        my_rom[251] = 48'h100c05fb;
        my_rom[252] = 48'h100c05fc;
        my_rom[253] = 48'h100c05fd;
        my_rom[254] = 48'h100c05fe;
        my_rom[255] = 48'h10000000;
    end
endmodule


module microcode (
  input [7:0] op,
  output [7:0] \alu-op ,
  output [4:0] \alu-pre ,
  output \cin-sel ,
  output [2:0] \wb-sel ,
  output [1:0] \shift-op ,
  output \flags-we ,
  output \reg-we ,
  output \mem-rd ,
  output \mem-wr ,
  output \addr-csel ,
  output \branch-en ,
  output \jump-type ,
  output [1:0] \sp-op ,
  output [1:0] cycles,
  output [2:0] ctrl_bus_sel,
  output [2:0] \b-main-sel ,
  output \pc-rel ,
  output [1:0] unused
);
  wire [47:0] s0;
  // microcode eeprom
  DIG_ROM_256X48_microcodeeeprom DIG_ROM_256X48_microcodeeeprom_i0 (
    .A( op ),
    .sel( 1'b1 ),
    .D( s0 )
  );
  assign \alu-op  = s0[7:0];
  assign \alu-pre  = s0[12:8];
  assign \cin-sel  = s0[13];
  assign \wb-sel  = s0[16:14];
  assign \shift-op  = s0[18:17];
  assign \flags-we  = s0[19];
  assign \reg-we  = s0[20];
  assign \mem-rd  = s0[21];
  assign \mem-wr  = s0[22];
  assign \addr-csel  = s0[23];
  assign \branch-en  = s0[24];
  assign \jump-type  = s0[25];
  assign \sp-op  = s0[27:26];
  assign cycles = s0[29:28];
  assign \b-main-sel  = s0[32:30];
  assign ctrl_bus_sel = s0[35:33];
  assign \pc-rel  = s0[36];
  assign unused = s0[38:37];
endmodule

module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module DriverInvBus#(
    parameter Bits = 2
)
(
    input [(Bits-1):0] in,
    input sel,
    output [(Bits-1):0] out
);
    assign out = (sel == 1'b0)? in : {Bits{1'bz}};
endmodule

module DriverBus#(
    parameter Bits = 2
)
(
    input [(Bits-1):0] in,
    input sel,
    output [(Bits-1):0] out
);
    assign out = (sel == 1'b1)? in : {Bits{1'bz}};
endmodule

module mmio_bus (
  input [23:0] ADDR,
  output [23:0] CPU_ADDR_OUT,
  output [23:0] mmio_addr,
  output is_mmio
);
  wire [3:0] s0;
  wire is_mmio_temp;
  assign s0 = ADDR[23:20];
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i0 (
    .a( s0 ),
    .b( 4'b1111 ),
    .\= ( is_mmio_temp )
  );
  DriverInvBus #(
    .Bits(24)
  )
  DriverInvBus_i1 (
    .in( ADDR ),
    .sel( is_mmio_temp ),
    .out( CPU_ADDR_OUT )
  );
  DriverBus #(
    .Bits(24)
  )
  DriverBus_i2 (
    .in( ADDR ),
    .sel( is_mmio_temp ),
    .out( mmio_addr )
  );
  assign is_mmio = is_mmio_temp;
endmodule

// quad 2-line to 1-line data selectors/multiplexers
module \74157  (
  input S, // select
  input A1,
  input A2,
  input A3,
  input A4,
  input B1,
  input B2,
  input B3,
  input B4,
  input G, // strobe
  input VCC,
  input GND,
  output Y1,
  output Y2,
  output Y3,
  output Y4
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  assign s1[0] = B1;
  assign s1[1] = B2;
  assign s1[2] = B3;
  assign s1[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( S ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( G ),
    .in_0( s2 ),
    .in_1( 4'b0 ),
    .out( s3 )
  );
  assign Y1 = s3[0];
  assign Y2 = s3[1];
  assign Y3 = s3[2];
  assign Y4 = s3[3];
endmodule

module shift (
  input [31:0] A,
  input [1:0] mode,
  input [4:0] B,
  output [31:0] Out
);
  wire shamt2;
  wire stg2_b00;
  wire stg2_b04;
  wire stg3_b00;
  wire stg2_b01;
  wire stg2_b05;
  wire stg3_b01;
  wire stg3_b02;
  wire stg2_b06;
  wire stg2_b02;
  wire stg3_b03;
  wire stg2_b07;
  wire stg2_b03;
  wire stg2_b08;
  wire stg3_b04;
  wire stg2_b09;
  wire stg3_b05;
  wire stg3_b06;
  wire stg2_b10;
  wire stg3_b07;
  wire stg2_b11;
  wire stg2_b12;
  wire stg3_b08;
  wire stg2_b13;
  wire stg3_b09;
  wire stg3_b10;
  wire stg2_b14;
  wire stg3_b11;
  wire stg2_b15;
  wire stg2_b16;
  wire stg3_b12;
  wire stg2_b17;
  wire stg3_b13;
  wire stg3_b14;
  wire stg2_b18;
  wire stg3_b15;
  wire stg2_b19;
  wire stg2_b20;
  wire stg3_b16;
  wire stg2_b21;
  wire stg3_b17;
  wire stg3_b18;
  wire stg2_b22;
  wire stg3_b19;
  wire stg2_b23;
  wire stg2_b24;
  wire stg3_b20;
  wire stg2_b25;
  wire stg3_b21;
  wire stg3_b22;
  wire stg2_b26;
  wire stg3_b23;
  wire stg2_b27;
  wire stg2_b28;
  wire stg3_b24;
  wire stg2_b29;
  wire stg3_b25;
  wire stg3_b26;
  wire stg2_b30;
  wire stg3_b27;
  wire stg2_b31;
  wire fill;
  wire stg3_b28;
  wire stg3_b29;
  wire stg3_b30;
  wire stg3_b31;
  wire in_b00;
  wire in_b01;
  wire in_b02;
  wire in_b03;
  wire in_b04;
  wire in_b05;
  wire in_b06;
  wire in_b07;
  wire in_b08;
  wire in_b09;
  wire in_b10;
  wire in_b11;
  wire in_b12;
  wire in_b13;
  wire in_b14;
  wire in_b15;
  wire in_b16;
  wire in_b17;
  wire in_b18;
  wire in_b19;
  wire in_b20;
  wire in_b21;
  wire in_b22;
  wire in_b23;
  wire in_b24;
  wire in_b25;
  wire in_b26;
  wire in_b27;
  wire in_b28;
  wire in_b29;
  wire in_b30;
  wire in_b31;
  wire [4:0] bin;
  wire shamt0;
  wire shamt1;
  wire shamt3;
  wire shamt4;
  wire out_b00;
  wire out_b01;
  wire out_b02;
  wire out_b03;
  wire out_b04;
  wire out_b05;
  wire out_b06;
  wire out_b07;
  wire out_b08;
  wire out_b09;
  wire out_b10;
  wire out_b11;
  wire out_b12;
  wire out_b13;
  wire out_b14;
  wire out_b15;
  wire out_b16;
  wire out_b17;
  wire out_b18;
  wire out_b19;
  wire out_b20;
  wire out_b21;
  wire out_b22;
  wire out_b23;
  wire out_b24;
  wire out_b25;
  wire out_b26;
  wire out_b27;
  wire out_b28;
  wire out_b29;
  wire out_b30;
  wire out_b31;
  wire stg4_b00;
  wire stg4_b01;
  wire stg4_b02;
  wire stg4_b03;
  wire stg4_b04;
  wire stg4_b05;
  wire stg4_b06;
  wire stg4_b07;
  wire stg4_b08;
  wire stg4_b09;
  wire stg4_b10;
  wire stg4_b11;
  wire stg4_b12;
  wire stg4_b13;
  wire stg4_b14;
  wire stg4_b15;
  wire stg4_b16;
  wire stg4_b17;
  wire stg4_b18;
  wire stg4_b19;
  wire stg4_b20;
  wire stg4_b21;
  wire stg4_b22;
  wire stg4_b23;
  wire stg4_b24;
  wire stg4_b25;
  wire stg4_b26;
  wire stg4_b27;
  wire stg4_b28;
  wire stg4_b29;
  wire stg4_b30;
  wire stg4_b31;
  wire stg5_b00;
  wire stg5_b01;
  wire stg5_b02;
  wire stg5_b03;
  wire stg5_b04;
  wire stg5_b05;
  wire stg5_b06;
  wire stg5_b07;
  wire stg5_b08;
  wire stg5_b09;
  wire stg5_b10;
  wire stg5_b11;
  wire stg5_b12;
  wire stg5_b13;
  wire stg5_b14;
  wire stg5_b15;
  wire stg5_b16;
  wire stg5_b17;
  wire stg5_b18;
  wire stg5_b19;
  wire stg5_b20;
  wire stg5_b21;
  wire stg5_b22;
  wire stg5_b23;
  wire stg5_b24;
  wire stg5_b25;
  wire stg5_b26;
  wire stg5_b27;
  wire stg5_b28;
  wire stg5_b29;
  wire stg5_b30;
  wire stg5_b31;
  wire LSL;
  wire stg0_b00;
  wire stg0_b01;
  wire stg0_b02;
  wire stg0_b03;
  wire stg0_b04;
  wire stg0_b05;
  wire stg0_b06;
  wire stg0_b07;
  wire stg0_b08;
  wire stg0_b09;
  wire stg0_b10;
  wire stg0_b11;
  wire stg0_b12;
  wire stg0_b13;
  wire stg0_b14;
  wire stg0_b15;
  wire stg0_b16;
  wire stg0_b17;
  wire stg0_b18;
  wire stg0_b19;
  wire stg0_b20;
  wire stg0_b21;
  wire stg0_b22;
  wire stg0_b23;
  wire stg0_b24;
  wire stg0_b25;
  wire stg0_b26;
  wire stg0_b27;
  wire stg0_b28;
  wire stg0_b29;
  wire stg0_b30;
  wire stg0_b31;
  wire stg1_b00;
  wire stg1_b01;
  wire stg1_b02;
  wire stg1_b03;
  wire stg1_b04;
  wire stg1_b05;
  wire stg1_b06;
  wire stg1_b07;
  wire stg1_b08;
  wire stg1_b09;
  wire stg1_b10;
  wire stg1_b11;
  wire stg1_b12;
  wire stg1_b13;
  wire stg1_b14;
  wire stg1_b15;
  wire stg1_b16;
  wire stg1_b17;
  wire stg1_b18;
  wire stg1_b19;
  wire stg1_b20;
  wire stg1_b21;
  wire stg1_b22;
  wire stg1_b23;
  wire stg1_b24;
  wire stg1_b25;
  wire stg1_b26;
  wire stg1_b27;
  wire stg1_b28;
  wire stg1_b29;
  wire stg1_b30;
  wire stg1_b31;
  wire MODE0;
  wire MODE1;
  assign in_b00 = A[0];
  assign in_b01 = A[1];
  assign in_b02 = A[2];
  assign in_b03 = A[3];
  assign in_b04 = A[4];
  assign in_b05 = A[5];
  assign in_b06 = A[6];
  assign in_b07 = A[7];
  assign in_b08 = A[8];
  assign in_b09 = A[9];
  assign in_b10 = A[10];
  assign in_b11 = A[11];
  assign in_b12 = A[12];
  assign in_b13 = A[13];
  assign in_b14 = A[14];
  assign in_b15 = A[15];
  assign in_b16 = A[16];
  assign in_b17 = A[17];
  assign in_b18 = A[18];
  assign in_b19 = A[19];
  assign in_b20 = A[20];
  assign in_b21 = A[21];
  assign in_b22 = A[22];
  assign in_b23 = A[23];
  assign in_b24 = A[24];
  assign in_b25 = A[25];
  assign in_b26 = A[26];
  assign in_b27 = A[27];
  assign in_b28 = A[28];
  assign in_b29 = A[29];
  assign in_b30 = A[30];
  assign in_b31 = A[31];
  assign MODE0 = mode[0];
  assign MODE1 = mode[1];
  assign bin = B[4:0];
  assign fill = ((MODE1 & ~ MODE0) & in_b31);
  assign LSL = (MODE0 & ~ MODE1);
  assign shamt0 = bin[0];
  assign shamt1 = bin[1];
  assign shamt2 = bin[2];
  assign shamt3 = bin[3];
  assign shamt4 = bin[4];
  \74157  \74157_i0 (
    .S( LSL ),
    .A1( in_b00 ),
    .B1( in_b31 ),
    .A2( in_b01 ),
    .B2( in_b30 ),
    .GND( 1'b0 ),
    .B3( in_b29 ),
    .A3( in_b02 ),
    .B4( in_b28 ),
    .A4( in_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b00 ),
    .Y2( stg0_b01 ),
    .Y3( stg0_b02 ),
    .Y4( stg0_b03 )
  );
  \74157  \74157_i1 (
    .S( LSL ),
    .A1( in_b04 ),
    .B1( in_b27 ),
    .A2( in_b05 ),
    .B2( in_b26 ),
    .GND( 1'b0 ),
    .B3( in_b25 ),
    .A3( in_b06 ),
    .B4( in_b24 ),
    .A4( in_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b04 ),
    .Y2( stg0_b05 ),
    .Y3( stg0_b06 ),
    .Y4( stg0_b07 )
  );
  \74157  \74157_i2 (
    .S( LSL ),
    .A1( in_b08 ),
    .B1( in_b23 ),
    .A2( in_b09 ),
    .B2( in_b22 ),
    .GND( 1'b0 ),
    .B3( in_b21 ),
    .A3( in_b10 ),
    .B4( in_b20 ),
    .A4( in_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b08 ),
    .Y2( stg0_b09 ),
    .Y3( stg0_b10 ),
    .Y4( stg0_b11 )
  );
  \74157  \74157_i3 (
    .S( LSL ),
    .A1( in_b12 ),
    .B1( in_b19 ),
    .A2( in_b13 ),
    .B2( in_b18 ),
    .GND( 1'b0 ),
    .B3( in_b17 ),
    .A3( in_b14 ),
    .B4( in_b16 ),
    .A4( in_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b12 ),
    .Y2( stg0_b13 ),
    .Y3( stg0_b14 ),
    .Y4( stg0_b15 )
  );
  \74157  \74157_i4 (
    .S( LSL ),
    .A1( in_b16 ),
    .B1( in_b15 ),
    .A2( in_b17 ),
    .B2( in_b14 ),
    .GND( 1'b0 ),
    .B3( in_b13 ),
    .A3( in_b18 ),
    .B4( in_b12 ),
    .A4( in_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b16 ),
    .Y2( stg0_b17 ),
    .Y3( stg0_b18 ),
    .Y4( stg0_b19 )
  );
  \74157  \74157_i5 (
    .S( LSL ),
    .A1( in_b20 ),
    .B1( in_b11 ),
    .A2( in_b21 ),
    .B2( in_b10 ),
    .GND( 1'b0 ),
    .B3( in_b09 ),
    .A3( in_b22 ),
    .B4( in_b08 ),
    .A4( in_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b20 ),
    .Y2( stg0_b21 ),
    .Y3( stg0_b22 ),
    .Y4( stg0_b23 )
  );
  \74157  \74157_i6 (
    .S( LSL ),
    .A1( in_b24 ),
    .B1( in_b07 ),
    .A2( in_b25 ),
    .B2( in_b06 ),
    .GND( 1'b0 ),
    .B3( in_b05 ),
    .A3( in_b26 ),
    .B4( in_b04 ),
    .A4( in_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b24 ),
    .Y2( stg0_b25 ),
    .Y3( stg0_b26 ),
    .Y4( stg0_b27 )
  );
  \74157  \74157_i7 (
    .S( LSL ),
    .A1( in_b28 ),
    .B1( in_b03 ),
    .A2( in_b29 ),
    .B2( in_b02 ),
    .GND( 1'b0 ),
    .B3( in_b01 ),
    .A3( in_b30 ),
    .B4( in_b00 ),
    .A4( in_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b28 ),
    .Y2( stg0_b29 ),
    .Y3( stg0_b30 ),
    .Y4( stg0_b31 )
  );
  \74157  \74157_i8 (
    .S( shamt0 ),
    .A1( stg0_b00 ),
    .B1( stg0_b01 ),
    .A2( stg0_b01 ),
    .B2( stg0_b02 ),
    .GND( 1'b0 ),
    .B3( stg0_b03 ),
    .A3( stg0_b02 ),
    .B4( stg0_b04 ),
    .A4( stg0_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b00 ),
    .Y2( stg1_b01 ),
    .Y3( stg1_b02 ),
    .Y4( stg1_b03 )
  );
  \74157  \74157_i9 (
    .S( shamt0 ),
    .A1( stg0_b04 ),
    .B1( stg0_b05 ),
    .A2( stg0_b05 ),
    .B2( stg0_b06 ),
    .GND( 1'b0 ),
    .B3( stg0_b07 ),
    .A3( stg0_b06 ),
    .B4( stg0_b08 ),
    .A4( stg0_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b04 ),
    .Y2( stg1_b05 ),
    .Y3( stg1_b06 ),
    .Y4( stg1_b07 )
  );
  \74157  \74157_i10 (
    .S( shamt0 ),
    .A1( stg0_b08 ),
    .B1( stg0_b09 ),
    .A2( stg0_b09 ),
    .B2( stg0_b10 ),
    .GND( 1'b0 ),
    .B3( stg0_b11 ),
    .A3( stg0_b10 ),
    .B4( stg0_b12 ),
    .A4( stg0_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b08 ),
    .Y2( stg1_b09 ),
    .Y3( stg1_b10 ),
    .Y4( stg1_b11 )
  );
  \74157  \74157_i11 (
    .S( shamt0 ),
    .A1( stg0_b12 ),
    .B1( stg0_b13 ),
    .A2( stg0_b13 ),
    .B2( stg0_b14 ),
    .GND( 1'b0 ),
    .B3( stg0_b15 ),
    .A3( stg0_b14 ),
    .B4( stg0_b16 ),
    .A4( stg0_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b12 ),
    .Y2( stg1_b13 ),
    .Y3( stg1_b14 ),
    .Y4( stg1_b15 )
  );
  \74157  \74157_i12 (
    .S( shamt0 ),
    .A1( stg0_b16 ),
    .B1( stg0_b17 ),
    .A2( stg0_b17 ),
    .B2( stg0_b18 ),
    .GND( 1'b0 ),
    .B3( stg0_b19 ),
    .A3( stg0_b18 ),
    .B4( stg0_b20 ),
    .A4( stg0_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b16 ),
    .Y2( stg1_b17 ),
    .Y3( stg1_b18 ),
    .Y4( stg1_b19 )
  );
  \74157  \74157_i13 (
    .S( shamt0 ),
    .A1( stg0_b20 ),
    .B1( stg0_b21 ),
    .A2( stg0_b21 ),
    .B2( stg0_b22 ),
    .GND( 1'b0 ),
    .B3( stg0_b23 ),
    .A3( stg0_b22 ),
    .B4( stg0_b24 ),
    .A4( stg0_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b20 ),
    .Y2( stg1_b21 ),
    .Y3( stg1_b22 ),
    .Y4( stg1_b23 )
  );
  \74157  \74157_i14 (
    .S( shamt0 ),
    .A1( stg0_b24 ),
    .B1( stg0_b25 ),
    .A2( stg0_b25 ),
    .B2( stg0_b26 ),
    .GND( 1'b0 ),
    .B3( stg0_b27 ),
    .A3( stg0_b26 ),
    .B4( stg0_b28 ),
    .A4( stg0_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b24 ),
    .Y2( stg1_b25 ),
    .Y3( stg1_b26 ),
    .Y4( stg1_b27 )
  );
  \74157  \74157_i15 (
    .S( shamt0 ),
    .A1( stg0_b28 ),
    .B1( stg0_b29 ),
    .A2( stg0_b29 ),
    .B2( stg0_b30 ),
    .GND( 1'b0 ),
    .B3( stg0_b31 ),
    .A3( stg0_b30 ),
    .B4( fill ),
    .A4( stg0_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b28 ),
    .Y2( stg1_b29 ),
    .Y3( stg1_b30 ),
    .Y4( stg1_b31 )
  );
  \74157  \74157_i16 (
    .S( shamt1 ),
    .A1( stg1_b00 ),
    .B1( stg1_b02 ),
    .A2( stg1_b01 ),
    .B2( stg1_b03 ),
    .GND( 1'b0 ),
    .B3( stg1_b04 ),
    .A3( stg1_b02 ),
    .B4( stg1_b05 ),
    .A4( stg1_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b00 ),
    .Y2( stg2_b01 ),
    .Y3( stg2_b02 ),
    .Y4( stg2_b03 )
  );
  \74157  \74157_i17 (
    .S( shamt1 ),
    .A1( stg1_b04 ),
    .B1( stg1_b06 ),
    .A2( stg1_b05 ),
    .B2( stg1_b07 ),
    .GND( 1'b0 ),
    .B3( stg1_b08 ),
    .A3( stg1_b06 ),
    .B4( stg1_b09 ),
    .A4( stg1_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b04 ),
    .Y2( stg2_b05 ),
    .Y3( stg2_b06 ),
    .Y4( stg2_b07 )
  );
  \74157  \74157_i18 (
    .S( shamt1 ),
    .A1( stg1_b08 ),
    .B1( stg1_b10 ),
    .A2( stg1_b09 ),
    .B2( stg1_b11 ),
    .GND( 1'b0 ),
    .B3( stg1_b12 ),
    .A3( stg1_b10 ),
    .B4( stg1_b13 ),
    .A4( stg1_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b08 ),
    .Y2( stg2_b09 ),
    .Y3( stg2_b10 ),
    .Y4( stg2_b11 )
  );
  \74157  \74157_i19 (
    .S( shamt1 ),
    .A1( stg1_b12 ),
    .B1( stg1_b14 ),
    .A2( stg1_b13 ),
    .B2( stg1_b15 ),
    .GND( 1'b0 ),
    .B3( stg1_b16 ),
    .A3( stg1_b14 ),
    .B4( stg1_b17 ),
    .A4( stg1_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b12 ),
    .Y2( stg2_b13 ),
    .Y3( stg2_b14 ),
    .Y4( stg2_b15 )
  );
  \74157  \74157_i20 (
    .S( shamt1 ),
    .A1( stg1_b16 ),
    .B1( stg1_b18 ),
    .A2( stg1_b17 ),
    .B2( stg1_b19 ),
    .GND( 1'b0 ),
    .B3( stg1_b20 ),
    .A3( stg1_b18 ),
    .B4( stg1_b21 ),
    .A4( stg1_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b16 ),
    .Y2( stg2_b17 ),
    .Y3( stg2_b18 ),
    .Y4( stg2_b19 )
  );
  \74157  \74157_i21 (
    .S( shamt1 ),
    .A1( stg1_b20 ),
    .B1( stg1_b22 ),
    .A2( stg1_b21 ),
    .B2( stg1_b23 ),
    .GND( 1'b0 ),
    .B3( stg1_b24 ),
    .A3( stg1_b22 ),
    .B4( stg1_b25 ),
    .A4( stg1_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b20 ),
    .Y2( stg2_b21 ),
    .Y3( stg2_b22 ),
    .Y4( stg2_b23 )
  );
  \74157  \74157_i22 (
    .S( shamt1 ),
    .A1( stg1_b24 ),
    .B1( stg1_b26 ),
    .A2( stg1_b25 ),
    .B2( stg1_b27 ),
    .GND( 1'b0 ),
    .B3( stg1_b28 ),
    .A3( stg1_b26 ),
    .B4( stg1_b29 ),
    .A4( stg1_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b24 ),
    .Y2( stg2_b25 ),
    .Y3( stg2_b26 ),
    .Y4( stg2_b27 )
  );
  \74157  \74157_i23 (
    .S( shamt1 ),
    .A1( stg1_b28 ),
    .B1( stg1_b30 ),
    .A2( stg1_b29 ),
    .B2( stg1_b31 ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg1_b30 ),
    .B4( fill ),
    .A4( stg1_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b28 ),
    .Y2( stg2_b29 ),
    .Y3( stg2_b30 ),
    .Y4( stg2_b31 )
  );
  \74157  \74157_i24 (
    .S( shamt2 ),
    .A1( stg2_b00 ),
    .B1( stg2_b04 ),
    .A2( stg2_b01 ),
    .B2( stg2_b05 ),
    .GND( 1'b0 ),
    .B3( stg2_b06 ),
    .A3( stg2_b02 ),
    .B4( stg2_b07 ),
    .A4( stg2_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b00 ),
    .Y2( stg3_b01 ),
    .Y3( stg3_b02 ),
    .Y4( stg3_b03 )
  );
  \74157  \74157_i25 (
    .S( shamt2 ),
    .A1( stg2_b04 ),
    .B1( stg2_b08 ),
    .A2( stg2_b05 ),
    .B2( stg2_b09 ),
    .GND( 1'b0 ),
    .B3( stg2_b10 ),
    .A3( stg2_b06 ),
    .B4( stg2_b11 ),
    .A4( stg2_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b04 ),
    .Y2( stg3_b05 ),
    .Y3( stg3_b06 ),
    .Y4( stg3_b07 )
  );
  \74157  \74157_i26 (
    .S( shamt2 ),
    .A1( stg2_b08 ),
    .B1( stg2_b12 ),
    .A2( stg2_b09 ),
    .B2( stg2_b13 ),
    .GND( 1'b0 ),
    .B3( stg2_b14 ),
    .A3( stg2_b10 ),
    .B4( stg2_b15 ),
    .A4( stg2_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b08 ),
    .Y2( stg3_b09 ),
    .Y3( stg3_b10 ),
    .Y4( stg3_b11 )
  );
  \74157  \74157_i27 (
    .S( shamt2 ),
    .A1( stg2_b12 ),
    .B1( stg2_b16 ),
    .A2( stg2_b13 ),
    .B2( stg2_b17 ),
    .GND( 1'b0 ),
    .B3( stg2_b18 ),
    .A3( stg2_b14 ),
    .B4( stg2_b19 ),
    .A4( stg2_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b12 ),
    .Y2( stg3_b13 ),
    .Y3( stg3_b14 ),
    .Y4( stg3_b15 )
  );
  \74157  \74157_i28 (
    .S( shamt2 ),
    .A1( stg2_b16 ),
    .B1( stg2_b20 ),
    .A2( stg2_b17 ),
    .B2( stg2_b21 ),
    .GND( 1'b0 ),
    .B3( stg2_b22 ),
    .A3( stg2_b18 ),
    .B4( stg2_b23 ),
    .A4( stg2_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b16 ),
    .Y2( stg3_b17 ),
    .Y3( stg3_b18 ),
    .Y4( stg3_b19 )
  );
  \74157  \74157_i29 (
    .S( shamt2 ),
    .A1( stg2_b20 ),
    .B1( stg2_b24 ),
    .A2( stg2_b21 ),
    .B2( stg2_b25 ),
    .GND( 1'b0 ),
    .B3( stg2_b26 ),
    .A3( stg2_b22 ),
    .B4( stg2_b27 ),
    .A4( stg2_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b20 ),
    .Y2( stg3_b21 ),
    .Y3( stg3_b22 ),
    .Y4( stg3_b23 )
  );
  \74157  \74157_i30 (
    .S( shamt2 ),
    .A1( stg2_b24 ),
    .B1( stg2_b28 ),
    .A2( stg2_b25 ),
    .B2( stg2_b29 ),
    .GND( 1'b0 ),
    .B3( stg2_b30 ),
    .A3( stg2_b26 ),
    .B4( stg2_b31 ),
    .A4( stg2_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b24 ),
    .Y2( stg3_b25 ),
    .Y3( stg3_b26 ),
    .Y4( stg3_b27 )
  );
  \74157  \74157_i31 (
    .S( shamt2 ),
    .A1( stg2_b28 ),
    .B1( fill ),
    .A2( stg2_b29 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg2_b30 ),
    .B4( fill ),
    .A4( stg2_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b28 ),
    .Y2( stg3_b29 ),
    .Y3( stg3_b30 ),
    .Y4( stg3_b31 )
  );
  \74157  \74157_i32 (
    .S( shamt3 ),
    .A1( stg3_b00 ),
    .B1( stg3_b08 ),
    .A2( stg3_b01 ),
    .B2( stg3_b09 ),
    .GND( 1'b0 ),
    .B3( stg3_b10 ),
    .A3( stg3_b02 ),
    .B4( stg3_b11 ),
    .A4( stg3_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b00 ),
    .Y2( stg4_b01 ),
    .Y3( stg4_b02 ),
    .Y4( stg4_b03 )
  );
  \74157  \74157_i33 (
    .S( shamt3 ),
    .A1( stg3_b04 ),
    .B1( stg3_b12 ),
    .A2( stg3_b05 ),
    .B2( stg3_b13 ),
    .GND( 1'b0 ),
    .B3( stg3_b14 ),
    .A3( stg3_b06 ),
    .B4( stg3_b15 ),
    .A4( stg3_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b04 ),
    .Y2( stg4_b05 ),
    .Y3( stg4_b06 ),
    .Y4( stg4_b07 )
  );
  \74157  \74157_i34 (
    .S( shamt3 ),
    .A1( stg3_b08 ),
    .B1( stg3_b16 ),
    .A2( stg3_b09 ),
    .B2( stg3_b17 ),
    .GND( 1'b0 ),
    .B3( stg3_b18 ),
    .A3( stg3_b10 ),
    .B4( stg3_b19 ),
    .A4( stg3_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b08 ),
    .Y2( stg4_b09 ),
    .Y3( stg4_b10 ),
    .Y4( stg4_b11 )
  );
  \74157  \74157_i35 (
    .S( shamt3 ),
    .A1( stg3_b12 ),
    .B1( stg3_b20 ),
    .A2( stg3_b13 ),
    .B2( stg3_b21 ),
    .GND( 1'b0 ),
    .B3( stg3_b22 ),
    .A3( stg3_b14 ),
    .B4( stg3_b23 ),
    .A4( stg3_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b12 ),
    .Y2( stg4_b13 ),
    .Y3( stg4_b14 ),
    .Y4( stg4_b15 )
  );
  \74157  \74157_i36 (
    .S( shamt3 ),
    .A1( stg3_b16 ),
    .B1( stg3_b24 ),
    .A2( stg3_b17 ),
    .B2( stg3_b25 ),
    .GND( 1'b0 ),
    .B3( stg3_b26 ),
    .A3( stg3_b18 ),
    .B4( stg3_b27 ),
    .A4( stg3_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b16 ),
    .Y2( stg4_b17 ),
    .Y3( stg4_b18 ),
    .Y4( stg4_b19 )
  );
  \74157  \74157_i37 (
    .S( shamt3 ),
    .A1( stg3_b20 ),
    .B1( stg3_b28 ),
    .A2( stg3_b21 ),
    .B2( stg3_b29 ),
    .GND( 1'b0 ),
    .B3( stg3_b30 ),
    .A3( stg3_b22 ),
    .B4( stg3_b31 ),
    .A4( stg3_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b20 ),
    .Y2( stg4_b21 ),
    .Y3( stg4_b22 ),
    .Y4( stg4_b23 )
  );
  \74157  \74157_i38 (
    .S( shamt3 ),
    .A1( stg3_b24 ),
    .B1( fill ),
    .A2( stg3_b25 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg3_b26 ),
    .B4( fill ),
    .A4( stg3_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b24 ),
    .Y2( stg4_b25 ),
    .Y3( stg4_b26 ),
    .Y4( stg4_b27 )
  );
  \74157  \74157_i39 (
    .S( shamt3 ),
    .A1( stg3_b28 ),
    .B1( fill ),
    .A2( stg3_b29 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg3_b30 ),
    .B4( fill ),
    .A4( stg3_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b28 ),
    .Y2( stg4_b29 ),
    .Y3( stg4_b30 ),
    .Y4( stg4_b31 )
  );
  \74157  \74157_i40 (
    .S( shamt4 ),
    .A1( stg4_b00 ),
    .B1( stg4_b16 ),
    .A2( stg4_b01 ),
    .B2( stg4_b17 ),
    .GND( 1'b0 ),
    .B3( stg4_b18 ),
    .A3( stg4_b02 ),
    .B4( stg4_b19 ),
    .A4( stg4_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b00 ),
    .Y2( stg5_b01 ),
    .Y3( stg5_b02 ),
    .Y4( stg5_b03 )
  );
  \74157  \74157_i41 (
    .S( shamt4 ),
    .A1( stg4_b04 ),
    .B1( stg4_b20 ),
    .A2( stg4_b05 ),
    .B2( stg4_b21 ),
    .GND( 1'b0 ),
    .B3( stg4_b22 ),
    .A3( stg4_b06 ),
    .B4( stg4_b23 ),
    .A4( stg4_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b04 ),
    .Y2( stg5_b05 ),
    .Y3( stg5_b06 ),
    .Y4( stg5_b07 )
  );
  \74157  \74157_i42 (
    .S( shamt4 ),
    .A1( stg4_b08 ),
    .B1( stg4_b24 ),
    .A2( stg4_b09 ),
    .B2( stg4_b25 ),
    .GND( 1'b0 ),
    .B3( stg4_b26 ),
    .A3( stg4_b10 ),
    .B4( stg4_b27 ),
    .A4( stg4_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b08 ),
    .Y2( stg5_b09 ),
    .Y3( stg5_b10 ),
    .Y4( stg5_b11 )
  );
  \74157  \74157_i43 (
    .S( shamt4 ),
    .A1( stg4_b12 ),
    .B1( stg4_b28 ),
    .A2( stg4_b13 ),
    .B2( stg4_b29 ),
    .GND( 1'b0 ),
    .B3( stg4_b30 ),
    .A3( stg4_b14 ),
    .B4( stg4_b31 ),
    .A4( stg4_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b12 ),
    .Y2( stg5_b13 ),
    .Y3( stg5_b14 ),
    .Y4( stg5_b15 )
  );
  \74157  \74157_i44 (
    .S( shamt4 ),
    .A1( stg4_b16 ),
    .B1( fill ),
    .A2( stg4_b17 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b18 ),
    .B4( fill ),
    .A4( stg4_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b16 ),
    .Y2( stg5_b17 ),
    .Y3( stg5_b18 ),
    .Y4( stg5_b19 )
  );
  \74157  \74157_i45 (
    .S( shamt4 ),
    .A1( stg4_b20 ),
    .B1( fill ),
    .A2( stg4_b21 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b22 ),
    .B4( fill ),
    .A4( stg4_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b20 ),
    .Y2( stg5_b21 ),
    .Y3( stg5_b22 ),
    .Y4( stg5_b23 )
  );
  \74157  \74157_i46 (
    .S( shamt4 ),
    .A1( stg4_b24 ),
    .B1( fill ),
    .A2( stg4_b25 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b26 ),
    .B4( fill ),
    .A4( stg4_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b24 ),
    .Y2( stg5_b25 ),
    .Y3( stg5_b26 ),
    .Y4( stg5_b27 )
  );
  \74157  \74157_i47 (
    .S( shamt4 ),
    .A1( stg4_b28 ),
    .B1( fill ),
    .A2( stg4_b29 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b30 ),
    .B4( fill ),
    .A4( stg4_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b28 ),
    .Y2( stg5_b29 ),
    .Y3( stg5_b30 ),
    .Y4( stg5_b31 )
  );
  \74157  \74157_i48 (
    .S( LSL ),
    .A1( stg5_b00 ),
    .B1( stg5_b31 ),
    .A2( stg5_b01 ),
    .B2( stg5_b30 ),
    .GND( 1'b0 ),
    .B3( stg5_b29 ),
    .A3( stg5_b02 ),
    .B4( stg5_b28 ),
    .A4( stg5_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b00 ),
    .Y2( out_b01 ),
    .Y3( out_b02 ),
    .Y4( out_b03 )
  );
  \74157  \74157_i49 (
    .S( LSL ),
    .A1( stg5_b04 ),
    .B1( stg5_b27 ),
    .A2( stg5_b05 ),
    .B2( stg5_b26 ),
    .GND( 1'b0 ),
    .B3( stg5_b25 ),
    .A3( stg5_b06 ),
    .B4( stg5_b24 ),
    .A4( stg5_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b04 ),
    .Y2( out_b05 ),
    .Y3( out_b06 ),
    .Y4( out_b07 )
  );
  \74157  \74157_i50 (
    .S( LSL ),
    .A1( stg5_b08 ),
    .B1( stg5_b23 ),
    .A2( stg5_b09 ),
    .B2( stg5_b22 ),
    .GND( 1'b0 ),
    .B3( stg5_b21 ),
    .A3( stg5_b10 ),
    .B4( stg5_b20 ),
    .A4( stg5_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b08 ),
    .Y2( out_b09 ),
    .Y3( out_b10 ),
    .Y4( out_b11 )
  );
  \74157  \74157_i51 (
    .S( LSL ),
    .A1( stg5_b12 ),
    .B1( stg5_b19 ),
    .A2( stg5_b13 ),
    .B2( stg5_b18 ),
    .GND( 1'b0 ),
    .B3( stg5_b17 ),
    .A3( stg5_b14 ),
    .B4( stg5_b16 ),
    .A4( stg5_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b12 ),
    .Y2( out_b13 ),
    .Y3( out_b14 ),
    .Y4( out_b15 )
  );
  \74157  \74157_i52 (
    .S( LSL ),
    .A1( stg5_b16 ),
    .B1( stg5_b15 ),
    .A2( stg5_b17 ),
    .B2( stg5_b14 ),
    .GND( 1'b0 ),
    .B3( stg5_b13 ),
    .A3( stg5_b18 ),
    .B4( stg5_b12 ),
    .A4( stg5_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b16 ),
    .Y2( out_b17 ),
    .Y3( out_b18 ),
    .Y4( out_b19 )
  );
  \74157  \74157_i53 (
    .S( LSL ),
    .A1( stg5_b20 ),
    .B1( stg5_b11 ),
    .A2( stg5_b21 ),
    .B2( stg5_b10 ),
    .GND( 1'b0 ),
    .B3( stg5_b09 ),
    .A3( stg5_b22 ),
    .B4( stg5_b08 ),
    .A4( stg5_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b20 ),
    .Y2( out_b21 ),
    .Y3( out_b22 ),
    .Y4( out_b23 )
  );
  \74157  \74157_i54 (
    .S( LSL ),
    .A1( stg5_b24 ),
    .B1( stg5_b07 ),
    .A2( stg5_b25 ),
    .B2( stg5_b06 ),
    .GND( 1'b0 ),
    .B3( stg5_b05 ),
    .A3( stg5_b26 ),
    .B4( stg5_b04 ),
    .A4( stg5_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b24 ),
    .Y2( out_b25 ),
    .Y3( out_b26 ),
    .Y4( out_b27 )
  );
  \74157  \74157_i55 (
    .S( LSL ),
    .A1( stg5_b28 ),
    .B1( stg5_b03 ),
    .A2( stg5_b29 ),
    .B2( stg5_b02 ),
    .GND( 1'b0 ),
    .B3( stg5_b01 ),
    .A3( stg5_b30 ),
    .B4( stg5_b00 ),
    .A4( stg5_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b28 ),
    .Y2( out_b29 ),
    .Y3( out_b30 ),
    .Y4( out_b31 )
  );
  assign Out[0] = out_b00;
  assign Out[1] = out_b01;
  assign Out[2] = out_b02;
  assign Out[3] = out_b03;
  assign Out[4] = out_b04;
  assign Out[5] = out_b05;
  assign Out[6] = out_b06;
  assign Out[7] = out_b07;
  assign Out[8] = out_b08;
  assign Out[9] = out_b09;
  assign Out[10] = out_b10;
  assign Out[11] = out_b11;
  assign Out[12] = out_b12;
  assign Out[13] = out_b13;
  assign Out[14] = out_b14;
  assign Out[15] = out_b15;
  assign Out[16] = out_b16;
  assign Out[17] = out_b17;
  assign Out[18] = out_b18;
  assign Out[19] = out_b19;
  assign Out[20] = out_b20;
  assign Out[21] = out_b21;
  assign Out[22] = out_b22;
  assign Out[23] = out_b23;
  assign Out[24] = out_b24;
  assign Out[25] = out_b25;
  assign Out[26] = out_b26;
  assign Out[27] = out_b27;
  assign Out[28] = out_b28;
  assign Out[29] = out_b29;
  assign Out[30] = out_b30;
  assign Out[31] = out_b31;
endmodule

module io_controller (
  input [23:0] mem_addr,
  input c_wr,
  input [15:0] kb_data,
  input [31:0] mem_data_out,
  output [31:0] io_data_in,
  output ram_cs,
  output vram_we,
  output [15:0] vram_addr,
  output [15:0] vram_data,
  output term_we,
  output [15:0] term_data
);
  wire comp2_eq;
  wire \comp3_> ;
  wire comp3_eq;
  wire comp4_eq;
  wire \comp4_< ;
  wire [31:0] c_kb_in;
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i0 (
    .a( mem_addr ),
    .b( 24'b100000000000000000000000 ),
    .\< ( ram_cs )
  );
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i1 (
    .a( mem_addr ),
    .b( 24'b100000000000000000010000 ),
    .\= ( comp2_eq )
  );
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i2 (
    .a( mem_addr ),
    .b( 24'b111100000000000000000000 ),
    .\> ( \comp3_>  ),
    .\= ( comp3_eq )
  );
  CompUnsigned #(
    .Bits(24)
  )
  CompUnsigned_i3 (
    .a( mem_addr ),
    .b( 24'b100000000000000000010100 ),
    .\= ( comp4_eq ),
    .\< ( \comp4_<  )
  );
  assign c_kb_in[15:0] = kb_data;
  assign c_kb_in[31:16] = 16'b0;
  assign term_data = mem_data_out[15:0];
  assign vram_addr = mem_addr[15:0];
  assign vram_data = mem_data_out[15:0];
  assign term_we = (comp2_eq & c_wr);
  assign vram_we = ((\comp3_>  | comp3_eq) & c_wr);
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i4 (
    .sel( comp4_eq ),
    .in_0( 32'b0 ),
    .in_1( c_kb_in ),
    .out( io_data_in )
  );
endmodule

module b_mux (
  input [31:0] ir,
  input [31:0] reg_b,
  input [2:0] sel,
  output [31:0] \alu-b 
);
  wire [31:0] ir0;
  wire [31:0] ir1;
  wire [31:0] ir2;
  wire [31:0] ir3;
  wire [31:0] ir4;
  wire [31:0] ir5;
  wire [23:0] ir4_out;
  wire ir_23;
  wire [15:0] ir1_out;
  wire ir_7;
  assign ir0[15:0] = ir[23:8];
  assign ir0[31:16] = 16'b0;
  assign ir2[15:0] = 16'b0;
  assign ir2[31:16] = ir[23:8];
  assign ir3[11:0] = 12'b0;
  assign ir3[31:12] = ir[23:4];
  assign ir_23 = ir[23];
  assign ir_7 = ir[7];
  assign ir4_out[0] = ir_7;
  assign ir4_out[1] = ir_7;
  assign ir4_out[2] = ir_7;
  assign ir4_out[3] = ir_7;
  assign ir4_out[4] = ir_7;
  assign ir4_out[5] = ir_7;
  assign ir4_out[6] = ir_7;
  assign ir4_out[7] = ir_7;
  assign ir4_out[8] = ir_7;
  assign ir4_out[9] = ir_7;
  assign ir4_out[10] = ir_7;
  assign ir4_out[11] = ir_7;
  assign ir4_out[12] = ir_7;
  assign ir4_out[13] = ir_7;
  assign ir4_out[14] = ir_7;
  assign ir4_out[15] = ir_7;
  assign ir4_out[16] = ir_7;
  assign ir4_out[17] = ir_7;
  assign ir4_out[18] = ir_7;
  assign ir4_out[19] = ir_7;
  assign ir4_out[20] = ir_7;
  assign ir4_out[21] = ir_7;
  assign ir4_out[22] = ir_7;
  assign ir4_out[23] = ir_7;
  assign ir1_out[0] = ir_23;
  assign ir1_out[1] = ir_23;
  assign ir1_out[2] = ir_23;
  assign ir1_out[3] = ir_23;
  assign ir1_out[4] = ir_23;
  assign ir1_out[5] = ir_23;
  assign ir1_out[6] = ir_23;
  assign ir1_out[7] = ir_23;
  assign ir1_out[8] = ir_23;
  assign ir1_out[9] = ir_23;
  assign ir1_out[10] = ir_23;
  assign ir1_out[11] = ir_23;
  assign ir1_out[12] = ir_23;
  assign ir1_out[13] = ir_23;
  assign ir1_out[14] = ir_23;
  assign ir1_out[15] = ir_23;
  assign ir5[22:0] = ir[23:1];
  assign ir5[23] = ir_23;
  assign ir5[24] = ir_23;
  assign ir5[25] = ir_23;
  assign ir5[26] = ir_23;
  assign ir5[27] = ir_23;
  assign ir5[28] = ir_23;
  assign ir5[29] = ir_23;
  assign ir5[30] = ir_23;
  assign ir5[31] = ir_23;
  assign ir4[7:0] = ir[7:0];
  assign ir4[31:8] = ir4_out;
  assign ir1[15:0] = ir[23:8];
  assign ir1[31:16] = ir1_out;
  Mux_8x1_NBits #(
    .Bits(32)
  )
  Mux_8x1_NBits_i0 (
    .sel( sel ),
    .in_0( reg_b ),
    .in_1( ir0 ),
    .in_2( ir1 ),
    .in_3( ir2 ),
    .in_4( ir3 ),
    .in_5( ir4 ),
    .in_6( ir5 ),
    .in_7( 32'b0 ),
    .out( \alu-b  )
  );
endmodule
module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule


module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module alu_1b_final (
  input [7:0] OPCODE,
  input A,
  input B,
  input C,
  input Asel,
  input Bsel,
  input A_inv,
  input B_inv,
  output MUX_OUT,
  output G,
  output P
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire A_eff;
  wire B_eff;
  wire [1:0] s2;
  wire P_temp;
  wire [1:0] s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  assign A_eff = ((Asel & A) ^ A_inv);
  assign B_eff = ((Bsel & B) ^ B_inv);
  assign s0 = OPCODE[3:0];
  assign s1 = OPCODE[7:4];
  assign s2[0] = A_eff;
  assign s2[1] = B_eff;
  assign G = (A_eff & B_eff);
  assign s3[0] = A_eff;
  assign s3[1] = B_eff;
  assign s4 = s0[0];
  assign s5 = s0[1];
  assign s6 = s0[2];
  assign s7 = s0[3];
  assign s8 = s1[0];
  assign s9 = s1[1];
  assign s10 = s1[2];
  assign s11 = s1[3];
  Mux_4x1 Mux_4x1_i0 (
    .sel( s3 ),
    .in_0( s4 ),
    .in_1( s5 ),
    .in_2( s6 ),
    .in_3( s7 ),
    .out( P_temp )
  );
  Mux_4x1 Mux_4x1_i1 (
    .sel( s2 ),
    .in_0( s8 ),
    .in_1( s9 ),
    .in_2( s10 ),
    .in_3( s11 ),
    .out( s12 )
  );
  Mux_2x1 Mux_2x1_i2 (
    .sel( C ),
    .in_0( P_temp ),
    .in_1( s12 ),
    .out( MUX_OUT )
  );
  assign P = P_temp;
endmodule

// quad 2-input AND gate
module \7408  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = (\1A  & \1B );
  assign \2Y  = (\2A  & \2B );
  assign \3Y  = (\3A  & \3B );
  assign \4Y  = (\4A  & \4B );
endmodule

// look-ahead carry generator
module \74182  (
  input C_n,
  input \~G0 ,
  input \~P0 ,
  input \~G1 ,
  input \~P1 ,
  input \~G2 ,
  input \~P2 ,
  input \~G3 ,
  input \~P3 ,
  input VCC,
  input GND,
  output \~P ,
  output \~G ,
  output \C_{n+z} ,
  output \C_{n+y} ,
  output \C_{n+x} 
);
  wire s0;
  assign \~P  = (\~P0  | \~P1  | \~P2  | \~P3 );
  assign \~G  = ((\~G0  & \~G1  & \~G2  & \~G3 ) | (\~P1  & \~G3  & \~G2  & \~G1 ) | (\~P2  & \~G3  & \~G2 ) | (\~P3  & \~G3 ));
  assign s0 = ~ C_n;
  assign \C_{n+z}  = ~ ((\~G2  & \~G1  & \~G0  & s0) | (\~P0  & \~G2  & \~G1  & \~G0 ) | (\~P1  & \~G2  & \~G1 ) | (\~P2  & \~G2 ));
  assign \C_{n+y}  = ~ ((\~G1  & \~G0  & s0) | (\~P0  & \~G1  & \~G0 ) | (\~P1  & \~G1 ));
  assign \C_{n+x}  = ~ ((\~G0  & s0) | (\~P0  & \~G0 ));
endmodule

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule

// octal buffer/line driver, inverted
module \74540  (
  input \~OE1 ,
  input \~OE2 ,
  input \0D ,
  input \1D ,
  input \2D ,
  input \3D ,
  input \4D ,
  input \5D ,
  input \6D ,
  input \7D ,
  input VCC,
  input GND,
  output \0O ,
  output \1O ,
  output \2O ,
  output \3O ,
  output \4O ,
  output \5O ,
  output \6O ,
  output \7O 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  assign s1 = ~ (\~OE1  | \~OE2 );
  assign s0 = ~ \0D ;
  assign s2 = ~ \1D ;
  assign s3 = ~ \2D ;
  assign s4 = ~ \3D ;
  assign s5 = ~ \4D ;
  assign s6 = ~ \5D ;
  assign s7 = ~ \6D ;
  assign s8 = ~ \7D ;
  Driver Driver_i0 (
    .in( s0 ),
    .sel( s1 ),
    .out( \0O  )
  );
  Driver Driver_i1 (
    .in( s2 ),
    .sel( s1 ),
    .out( \1O  )
  );
  Driver Driver_i2 (
    .in( s3 ),
    .sel( s1 ),
    .out( \2O  )
  );
  Driver Driver_i3 (
    .in( s4 ),
    .sel( s1 ),
    .out( \3O  )
  );
  Driver Driver_i4 (
    .in( s5 ),
    .sel( s1 ),
    .out( \4O  )
  );
  Driver Driver_i5 (
    .in( s6 ),
    .sel( s1 ),
    .out( \5O  )
  );
  Driver Driver_i6 (
    .in( s7 ),
    .sel( s1 ),
    .out( \6O  )
  );
  Driver Driver_i7 (
    .in( s8 ),
    .sel( s1 ),
    .out( \7O  )
  );
endmodule

// quad 2-input OR gate
module \7432  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = (\1A  | \1B );
  assign \2Y  = (\2A  | \2B );
  assign \3Y  = (\3A  | \3B );
  assign \4Y  = (\4A  | \4B );
endmodule

module alu_8b_final (
  input [7:0] opcode,
  input [4:0] control,
  input [7:0] A,
  input [7:0] B,
  input [7:0] C,
  input \nz-in ,
  input cin,
  output [7:0] out,
  output vout,
  output zout,
  output \nz-out ,
  output n,
  output cout
);
  wire a0;
  wire b0;
  wire ceff0;
  wire asel;
  wire bsel;
  wire ainv;
  wire binv;
  wire out0;
  wire g0;
  wire p0;
  wire a1;
  wire b1;
  wire ceff1;
  wire out1;
  wire g1;
  wire p1;
  wire a2;
  wire b2;
  wire ceff2;
  wire out2;
  wire g2;
  wire p2;
  wire a3;
  wire b3;
  wire ceff3;
  wire out3;
  wire g3;
  wire p3;
  wire a4;
  wire b4;
  wire ceff4;
  wire out4;
  wire g4;
  wire p4;
  wire a5;
  wire b5;
  wire ceff5;
  wire out5;
  wire g5;
  wire p5;
  wire a6;
  wire b6;
  wire ceff6;
  wire out6;
  wire g6;
  wire p6;
  wire a7;
  wire b7;
  wire ceff7;
  wire n_temp;
  wire g7;
  wire p7;
  wire csel;
  wire c0;
  wire c1;
  wire c2;
  wire c3;
  wire c4;
  wire c5;
  wire c6;
  wire c7;
  wire cin1;
  wire cin2;
  wire cin3;
  wire cin4;
  wire cin5;
  wire cin6;
  wire cin7;
  wire cout_temp;
  wire zout_temp;
  wire c0xp0;
  wire s0;
  wire c4xp1;
  wire s1;
  wire s2;
  wire s3;
  wire g1_b;
  wire p1_b;
  wire g0_b;
  wire p0_b;
  wire g3_b;
  wire p3_b;
  wire \p-out-0 ;
  wire \g-out-0 ;
  wire g2_b;
  wire p2_b;
  wire g5_b;
  wire p5_b;
  wire g4_b;
  wire p4_b;
  wire g7_b;
  wire p7_b;
  wire \p-out-1 ;
  wire \g-out-1 ;
  wire g6_b;
  wire p6_b;
  assign asel = control[0];
  assign ainv = control[1];
  assign bsel = control[2];
  assign binv = control[3];
  assign csel = control[4];
  assign a0 = A[0];
  assign a1 = A[1];
  assign a2 = A[2];
  assign a3 = A[3];
  assign a4 = A[4];
  assign a5 = A[5];
  assign a6 = A[6];
  assign a7 = A[7];
  assign b0 = B[0];
  assign b1 = B[1];
  assign b2 = B[2];
  assign b3 = B[3];
  assign b4 = B[4];
  assign b5 = B[5];
  assign b6 = B[6];
  assign b7 = B[7];
  assign c0 = C[0];
  assign c1 = C[1];
  assign c2 = C[2];
  assign c3 = C[3];
  assign c4 = C[4];
  assign c5 = C[5];
  assign c6 = C[6];
  assign c7 = C[7];
  alu_1b_final alu_1b_final_i0 (
    .OPCODE( opcode ),
    .A( a0 ),
    .B( b0 ),
    .C( ceff0 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out0 ),
    .G( g0 ),
    .P( p0 )
  );
  alu_1b_final alu_1b_final_i1 (
    .OPCODE( opcode ),
    .A( a1 ),
    .B( b1 ),
    .C( ceff1 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out1 ),
    .G( g1 ),
    .P( p1 )
  );
  alu_1b_final alu_1b_final_i2 (
    .OPCODE( opcode ),
    .A( a2 ),
    .B( b2 ),
    .C( ceff2 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out2 ),
    .G( g2 ),
    .P( p2 )
  );
  alu_1b_final alu_1b_final_i3 (
    .OPCODE( opcode ),
    .A( a3 ),
    .B( b3 ),
    .C( ceff3 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out3 ),
    .G( g3 ),
    .P( p3 )
  );
  alu_1b_final alu_1b_final_i4 (
    .OPCODE( opcode ),
    .A( a4 ),
    .B( b4 ),
    .C( ceff4 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out4 ),
    .G( g4 ),
    .P( p4 )
  );
  alu_1b_final alu_1b_final_i5 (
    .OPCODE( opcode ),
    .A( a5 ),
    .B( b5 ),
    .C( ceff5 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out5 ),
    .G( g5 ),
    .P( p5 )
  );
  alu_1b_final alu_1b_final_i6 (
    .OPCODE( opcode ),
    .A( a6 ),
    .B( b6 ),
    .C( ceff6 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( out6 ),
    .G( g6 ),
    .P( p6 )
  );
  alu_1b_final alu_1b_final_i7 (
    .OPCODE( opcode ),
    .A( a7 ),
    .B( b7 ),
    .C( ceff7 ),
    .Asel( asel ),
    .Bsel( bsel ),
    .A_inv( ainv ),
    .B_inv( binv ),
    .MUX_OUT( n_temp ),
    .G( g7 ),
    .P( p7 )
  );
  \74157  \74157_i8 (
    .S( csel ),
    .A1( cin ),
    .B1( c0 ),
    .A2( cin1 ),
    .B2( c1 ),
    .GND( 1'b0 ),
    .B3( c2 ),
    .A3( cin2 ),
    .B4( c3 ),
    .A4( cin3 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( ceff0 ),
    .Y2( ceff1 ),
    .Y3( ceff2 ),
    .Y4( ceff3 )
  );
  \74157  \74157_i9 (
    .S( csel ),
    .A1( cin4 ),
    .B1( c4 ),
    .A2( cin5 ),
    .B2( c5 ),
    .GND( 1'b0 ),
    .B3( c6 ),
    .A3( cin6 ),
    .B4( c7 ),
    .A4( cin7 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( ceff4 ),
    .Y2( ceff5 ),
    .Y3( ceff6 ),
    .Y4( ceff7 )
  );
  assign \nz-out  = (~ zout_temp | \nz-in );
  \7408  \7408_i10 (
    .\1A ( s2 ),
    .\1B ( cin ),
    .\2A ( s3 ),
    .\2B ( cin4 ),
    .GND( 1'b0 ),
    .\3A ( 1'b0 ),
    .\3B ( 1'b0 ),
    .\4A ( 1'b0 ),
    .\4B ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( c0xp0 ),
    .\2Y ( c4xp1 )
  );
  \74182  \74182_i11 (
    .\~G1 ( g1_b ),
    .\~P1 ( p1_b ),
    .\~G0 ( g0_b ),
    .\~P0 ( p0_b ),
    .\~G3 ( g3_b ),
    .\~P3 ( p3_b ),
    .GND( 1'b0 ),
    .C_n( cin ),
    .\~G2 ( g2_b ),
    .\~P2 ( p2_b ),
    .VCC( 1'b1 ),
    .\~P ( \p-out-0  ),
    .\C_{n+z} ( cin3 ),
    .\~G ( \g-out-0  ),
    .\C_{n+y} ( cin2 ),
    .\C_{n+x} ( cin1 )
  );
  assign out[0] = out0;
  assign out[1] = out1;
  assign out[2] = out2;
  assign out[3] = out3;
  assign out[4] = out4;
  assign out[5] = out5;
  assign out[6] = out6;
  assign out[7] = n_temp;
  assign zout_temp = (~ (out0 | out1 | out2 | out3) & ~ (out4 | out5 | out6 | n_temp));
  \74540  \74540_i12 (
    .\~OE1 ( 1'b0 ),
    .\0D ( p0 ),
    .\1D ( p1 ),
    .\2D ( p2 ),
    .\3D ( p3 ),
    .\4D ( g0 ),
    .\5D ( g1 ),
    .\6D ( g2 ),
    .\7D ( g3 ),
    .GND( 1'b0 ),
    .\~OE2 ( 1'b0 ),
    .VCC( 1'b1 ),
    .\7O ( g3_b ),
    .\6O ( g2_b ),
    .\5O ( g1_b ),
    .\4O ( g0_b ),
    .\3O ( p3_b ),
    .\2O ( p2_b ),
    .\1O ( p1_b ),
    .\0O ( p0_b )
  );
  \74540  \74540_i13 (
    .\~OE1 ( 1'b0 ),
    .\0D ( p4 ),
    .\1D ( p5 ),
    .\2D ( p6 ),
    .\3D ( p7 ),
    .\4D ( g4 ),
    .\5D ( g5 ),
    .\6D ( g6 ),
    .\7D ( g7 ),
    .GND( 1'b0 ),
    .\~OE2 ( 1'b0 ),
    .VCC( 1'b1 ),
    .\7O ( g7_b ),
    .\6O ( g6_b ),
    .\5O ( g5_b ),
    .\4O ( g4_b ),
    .\3O ( p7_b ),
    .\2O ( p6_b ),
    .\1O ( p5_b ),
    .\0O ( p4_b )
  );
  assign s2 = ~ \p-out-0 ;
  assign s0 = ~ \g-out-0 ;
  \7432  \7432_i14 (
    .\1A ( c0xp0 ),
    .\1B ( s0 ),
    .\2A ( c4xp1 ),
    .\2B ( s1 ),
    .GND( 1'b0 ),
    .\3A ( 1'b0 ),
    .\3B ( 1'b0 ),
    .\4A ( 1'b0 ),
    .\4B ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( cin4 ),
    .\2Y ( cout_temp )
  );
  \74182  \74182_i15 (
    .\~G1 ( g5_b ),
    .\~P1 ( p5_b ),
    .\~G0 ( g4_b ),
    .\~P0 ( p4_b ),
    .\~G3 ( g7_b ),
    .\~P3 ( p7_b ),
    .GND( 1'b0 ),
    .C_n( cin4 ),
    .\~G2 ( g6_b ),
    .\~P2 ( p6_b ),
    .VCC( 1'b1 ),
    .\~P ( \p-out-1  ),
    .\C_{n+z} ( cin7 ),
    .\~G ( \g-out-1  ),
    .\C_{n+y} ( cin6 ),
    .\C_{n+x} ( cin5 )
  );
  assign vout = (cin7 ^ cout_temp);
  assign s3 = ~ \p-out-1 ;
  assign s1 = ~ \g-out-1 ;
  assign zout = zout_temp;
  assign n = n_temp;
  assign cout = cout_temp;
endmodule

module alu_32b_final (
  input [31:0] A,
  input nz0,
  input [31:0] B,
  input [7:0] Opcode,
  input [4:0] control,
  input [31:0] REG_C,
  input \cin-sel ,
  input FLAG_C,
  output vout,
  output zout,
  output nzout,
  output nout,
  output [31:0] Out,
  output cout
);
  wire [7:0] \a0-7 ;
  wire [7:0] \b0-7 ;
  wire [7:0] \c0-7 ;
  wire cin0;
  wire [7:0] \out0-7 ;
  wire nz1;
  wire c7;
  wire [7:0] \a16-23 ;
  wire [7:0] \b16-23 ;
  wire [7:0] \c16-23 ;
  wire c15;
  wire [7:0] \out16-23 ;
  wire nz2;
  wire c23;
  wire [7:0] \a8-15 ;
  wire [7:0] \b8-15 ;
  wire [7:0] \c8-15 ;
  wire [7:0] \out8-15 ;
  wire nz3;
  wire [7:0] \a24-31 ;
  wire [7:0] \b24-31 ;
  wire [7:0] \c24-31 ;
  wire [7:0] \out24-31 ;
  wire nzout_temp;
  wire [31:0] ceff;
  wire asel;
  wire ainv;
  wire bsel;
  wire binv;
  wire csel;
  wire [31:0] FLAG_C32;
  wire [31:0] s0;
  assign FLAG_C32[0] = FLAG_C;
  assign FLAG_C32[31:1] = 31'b1;
  assign \a0-7  = A[7:0];
  assign \a8-15  = A[15:8];
  assign \a16-23  = A[23:16];
  assign \a24-31  = A[31:24];
  assign \b0-7  = B[7:0];
  assign \b8-15  = B[15:8];
  assign \b16-23  = B[23:16];
  assign \b24-31  = B[31:24];
  assign asel = control[0];
  assign ainv = control[1];
  assign bsel = control[2];
  assign binv = control[3];
  assign csel = control[4];
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i0 (
    .sel( \cin-sel  ),
    .in_0( FLAG_C32 ),
    .in_1( 32'b1 ),
    .out( s0 )
  );
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i1 (
    .sel( csel ),
    .in_0( s0 ),
    .in_1( REG_C ),
    .out( ceff )
  );
  assign \c0-7  = ceff[7:0];
  assign \c8-15  = ceff[15:8];
  assign \c16-23  = ceff[23:16];
  assign \c24-31  = ceff[31:24];
  assign cin0 = \c0-7 [0];
  // Cell 0
  alu_8b_final alu_8b_final_i2 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a0-7  ),
    .B( \b0-7  ),
    .C( \c0-7  ),
    .\nz-in ( nz0 ),
    .cin( cin0 ),
    .out( \out0-7  ),
    .\nz-out ( nz1 ),
    .cout( c7 )
  );
  // Cell 2
  alu_8b_final alu_8b_final_i3 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a16-23  ),
    .B( \b16-23  ),
    .C( \c16-23  ),
    .\nz-in ( nz1 ),
    .cin( c15 ),
    .out( \out16-23  ),
    .\nz-out ( nz2 ),
    .cout( c23 )
  );
  // Cell 1
  alu_8b_final alu_8b_final_i4 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a8-15  ),
    .B( \b8-15  ),
    .C( \c8-15  ),
    .\nz-in ( nz2 ),
    .cin( c7 ),
    .out( \out8-15  ),
    .\nz-out ( nz3 ),
    .cout( c15 )
  );
  // Cell 3
  alu_8b_final alu_8b_final_i5 (
    .opcode( Opcode ),
    .control( control ),
    .A( \a24-31  ),
    .B( \b24-31  ),
    .C( \c24-31  ),
    .\nz-in ( nz3 ),
    .cin( c23 ),
    .out( \out24-31  ),
    .vout( vout ),
    .\nz-out ( nzout_temp ),
    .n( nout ),
    .cout( cout )
  );
  assign Out[7:0] = \out0-7 ;
  assign Out[15:8] = \out8-15 ;
  assign Out[23:16] = \out16-23 ;
  assign Out[31:24] = \out24-31 ;
  assign zout = ~ nzout_temp;
  assign nzout = nzout_temp;
endmodule

module main (
  input clk,
  input reset,
  output [23:0] b,
  output [31:0] a,
  output [31:0] f,
  output [23:0] e,
  output [23:0] i,
  output [7:0] h,
  output [7:0] d,
  output [7:0] g,
  output [7:0] c,
  output [7:0] k,
  output [31:0] j,
  output [31:0] l,
  output [31:0] m,
  output [31:0] p,
  output [15:0] term_data,
  output [15:0] vram_addr,
  output term_we,
  output [31:0] r,
  output [31:0] n,
  output a1,
  output [7:0] a2,
  output [7:0] a3,
  output [23:0] t8
);
  wire [1:0] ctrl_cycles;
  wire seq_fetch;
  wire seq_exec;
  wire [23:0] i_temp;
  wire [23:0] e_temp;
  wire [23:0] t8_temp;
  wire \pc-mux-sel-1 ;
  wire \pc-mux-sel-2 ;
  wire flag_n;
  wire flag_c;
  wire flag_z;
  wire flag_v;
  wire [2:0] cond;
  wire \pc-branch-en ;
  wire HALT_IN;
  wire [23:0] sp_delta;
  wire sp_load_n;
  wire \pc-jump-uncond ;
  wire [23:0] b_temp;
  wire [31:0] l_temp;
  wire [31:0] f_temp;
  wire [7:0] a3_temp;
  wire [7:0] d_temp;
  wire [7:0] a2_temp;
  wire [7:0] c_temp;
  wire [7:0] k_temp;
  wire [4:0] ctrl_alu_pre;
  wire ctrl_cin_sel;
  wire [2:0] ctrl_wb_sel;
  wire [1:0] ctrl_shift_op;
  wire ctrl_flags_we;
  wire a1_temp;
  wire ctrl_mem_rd;
  wire ctrl_mem_wr;
  wire ctrl_addr_csel;
  wire ctrl_branch_en;
  wire ctrl_jump_type;
  wire [1:0] ctrl_sp_op;
  wire [2:0] ctrl_bus_sel;
  wire [2:0] \b-main-sel ;
  wire [31:0] m_temp;
  wire [31:0] n_temp;
  wire [31:0] r_temp;
  wire [31:0] reg_c;
  wire [31:0] alu_b;
  wire alu_vout;
  wire alu_zout;
  wire alu_nzout;
  wire alu_nout;
  wire [31:0] j_temp;
  wire alu_cout;
  wire [31:0] shift_out;
  wire [31:0] io_data_in;
  wire s0;
  wire s1;
  wire [23:0] mem_addr;
  wire [23:0] CPU_ADDR_OUT;
  wire [23:0] mmio_addr;
  wire is_mmio;
  wire ram_cs;
  wire vram_we;
  wire [15:0] vram_data;
  wire mem_rd_out;
  wire s2;
  wire [23:0] mem_addr_in;
  wire s3;
  wire [7:0] \ir-24-31 ;
  wire [31:0] \mem-eeprom-out ;
  sequencer sequencer_i0 (
    .reset( reset ),
    .cycles( ctrl_cycles ),
    .CLK( clk ),
    .FETCH( seq_fetch ),
    .EXECUTE( seq_exec )
  );
  pc pc_i1 (
    .CLK( clk ),
    .\~SR ( reset ),
    .ADDR_ABS( i_temp ),
    .OFFSET( e_temp ),
    .ADDR_RET( t8_temp ),
    .MUX1_SEL( \pc-mux-sel-1  ),
    .MUX2_SEL( \pc-mux-sel-2  ),
    .FLAG_N( flag_n ),
    .FLAG_C( flag_c ),
    .FLAG_Z( flag_z ),
    .FLAG_O( flag_v ),
    .COND( cond ),
    .BRANCH_EN( \pc-branch-en  ),
    .INT_EN_IN( 1'b0 ),
    .HALT_IN( HALT_IN ),
    .INT_REQ( 1'b0 ),
    .INT_VEC_0( 1'b1 ),
    .INT_VEC_1( 1'b1 ),
    .INT_VEC_2( 1'b1 ),
    .SP_DELTA( sp_delta ),
    .SP_LOAD_N( sp_load_n ),
    .JUMP_UNCOND( \pc-jump-uncond  ),
    .PCEN( seq_fetch ),
    .PC_OUT( b_temp ),
    .PC_SAVE( t8_temp )
  );
  register register_i2 (
    .WE( a1_temp ),
    .DATA_W( m_temp ),
    .ADDR_A( a2_temp ),
    .ADDR_B( d_temp ),
    .ADDR_W( a3_temp ),
    .EXEC( seq_exec ),
    .addr_c_sel( ctrl_addr_csel ),
    .ir_bus( f_temp ),
    .clk( clk ),
    .DATA_A( n_temp ),
    .DATA_B( r_temp ),
    .DATA_C( reg_c )
  );
  flag_reg flag_reg_i3 (
    .ZERO_IN( alu_zout ),
    .CARRY_IN( alu_cout ),
    .NEGATIVE_IN( alu_nout ),
    .OVERFLOW_IN( alu_vout ),
    .FLAG_WE( ctrl_flags_we ),
    .CLK( clk ),
    .EXEC( seq_exec ),
    .FLAG_Z( flag_z ),
    .FLAG_C( flag_c ),
    .FLAG_N( flag_n ),
    .FLAG_O( flag_v )
  );
  wb_mux wb_mux_i4 (
    .wb_sel( ctrl_wb_sel ),
    .alu_out( j_temp ),
    .shift_out( shift_out ),
    .pc_save( t8_temp ),
    .mem_din( l_temp ),
    .io_datain( io_data_in ),
    .reg_a( n_temp ),
    .\ir-bus ( f_temp ),
    .reg_w_data( m_temp )
  );
  assign s0 = (seq_exec & a1_temp & s1);
  assign HALT_IN = (s3 & seq_exec);
  assign \pc-branch-en  = (ctrl_branch_en & seq_exec);
  assign \pc-jump-uncond  = (ctrl_jump_type & seq_exec);
  ir ir_i5 (
    .DATA_IN( l_temp ),
    .LOAD( seq_fetch ),
    .CLK( clk ),
    .IR_BUS( f_temp ),
    .OPCODE( c_temp ),
    .ADDR_A( a2_temp ),
    .ADDR_B( d_temp ),
    .ADDR_W( a3_temp ),
    .ADDR_ABS( i_temp ),
    .OFFSET( e_temp ),
    .COND( cond )
  );
  bus_arbitration bus_arbitration_i6 (
    .FETCH( seq_fetch ),
    .PC_OUT( b_temp ),
    .IR_ADDR( i_temp ),
    .Reg_A( j_temp ),
    .MEM_RD_IN( ctrl_mem_rd ),
    .addr_sel( ctrl_bus_sel ),
    .Reg_b( 32'b1 ),
    .\Reg-A-off ( 32'b1 ),
    .\Reg-B-off ( 32'b1 ),
    .\Reg-AB ( 32'b1 ),
    .\PC-offset ( 32'b1 ),
    .\SP-out ( 32'b1 ),
    .\Alu-in ( 32'b1 ),
    .ADDR_BUS( mem_addr ),
    .MEM_RD_OUT( mem_rd_out )
  );
  microcode microcode_i7 (
    .op( c_temp ),
    .\alu-op ( k_temp ),
    .\alu-pre ( ctrl_alu_pre ),
    .\cin-sel ( ctrl_cin_sel ),
    .\wb-sel ( ctrl_wb_sel ),
    .\shift-op ( ctrl_shift_op ),
    .\flags-we ( ctrl_flags_we ),
    .\reg-we ( a1_temp ),
    .\mem-rd ( ctrl_mem_rd ),
    .\mem-wr ( ctrl_mem_wr ),
    .\addr-csel ( ctrl_addr_csel ),
    .\branch-en ( ctrl_branch_en ),
    .\jump-type ( ctrl_jump_type ),
    .\sp-op ( ctrl_sp_op ),
    .cycles( ctrl_cycles ),
    .ctrl_bus_sel( ctrl_bus_sel ),
    .\b-main-sel ( \b-main-sel  ),
    .\pc-rel ( \pc-mux-sel-1  )
  );
  CompUnsigned #(
    .Bits(8)
  )
  CompUnsigned_i8 (
    .a( 8'b10 ),
    .b( a3_temp ),
    .\= ( s1 )
  );
  mmio_bus mmio_bus_i9 (
    .ADDR( mem_addr ),
    .CPU_ADDR_OUT( CPU_ADDR_OUT ),
    .mmio_addr( mmio_addr ),
    .is_mmio( is_mmio )
  );
  CompUnsigned #(
    .Bits(8)
  )
  CompUnsigned_i10 (
    .a( 8'b11111111 ),
    .b( c_temp ),
    .\= ( s3 )
  );
  assign \ir-24-31  = f_temp[31:24];
  shift shift_i11 (
    .A( n_temp ),
    .mode( ctrl_shift_op ),
    .B( r_temp ),
    .Out( shift_out )
  );
  io_controller io_controller_i12 (
    .mem_addr( mmio_addr ),
    .c_wr( ctrl_mem_wr ),
    .kb_data( 16'b1 ),
    .mem_data_out( r_temp ),
    .io_data_in( io_data_in ),
    .ram_cs( ram_cs ),
    .vram_we( vram_we ),
    .vram_addr( vram_addr ),
    .vram_data( vram_data ),
    .term_we( term_we ),
    .term_data( term_data )
  );
  assign s2 = (is_mmio & mem_rd_out);
  CompUnsigned #(
    .Bits(8)
  )
  CompUnsigned_i13 (
    .a( \ir-24-31  ),
    .b( 8'b110011 ),
    .\= ( \pc-mux-sel-2  )
  );
  Mux_4x1_NBits #(
    .Bits(24)
  )
  Mux_4x1_NBits_i14 (
    .sel( ctrl_sp_op ),
    .in_0( 24'b0 ),
    .in_1( 24'b1 ),
    .in_2( 24'b111111111111111111111111 ),
    .in_3( 24'b0 ),
    .out( sp_delta )
  );
  assign sp_load_n = ~ (ctrl_sp_op[0] | ctrl_sp_op[1]);
  b_mux b_mux_i15 (
    .ir( f_temp ),
    .reg_b( r_temp ),
    .sel( \b-main-sel  ),
    .\alu-b ( alu_b )
  );
  DIG_RAMDualPort #(
    .Bits(32),
    .AddrBits(24)
  )
  DIG_RAMDualPort_i16 (
    .A( mem_addr ),
    .Din( r_temp ),
    .str( ctrl_mem_wr ),
    .C( clk ),
    .ld( mem_rd_out ),
    .D( \mem-eeprom-out  )
  );
  alu_32b_final alu_32b_final_i17 (
    .A( n_temp ),
    .nz0( 1'b0 ),
    .B( alu_b ),
    .Opcode( k_temp ),
    .control( ctrl_alu_pre ),
    .REG_C( reg_c ),
    .\cin-sel ( ctrl_cin_sel ),
    .FLAG_C( flag_c ),
    .vout( alu_vout ),
    .zout( alu_zout ),
    .nzout( alu_nzout ),
    .nout( alu_nout ),
    .Out( j_temp ),
    .cout( alu_cout )
  );
  DIG_Register_BUS #(
    .Bits(32)
  )
  DIG_Register_BUS_i18 (
    .D( alu_b ),
    .C( clk ),
    .en( s0 ),
    .Q( p )
  );
  Mux_2x1_NBits #(
    .Bits(24)
  )
  Mux_2x1_NBits_i19 (
    .sel( s2 ),
    .in_0( CPU_ADDR_OUT ),
    .in_1( mmio_addr ),
    .out( mem_addr_in )
  );
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i20 (
    .sel( ram_cs ),
    .in_0( \mem-eeprom-out  ),
    .in_1( io_data_in ),
    .out( l_temp )
  );
  assign b = b_temp;
  assign a = l_temp;
  assign f = f_temp;
  assign e = e_temp;
  assign i = i_temp;
  assign h = a3_temp;
  assign d = d_temp;
  assign g = a2_temp;
  assign c = c_temp;
  assign k = k_temp;
  assign j = j_temp;
  assign l = l_temp;
  assign m = m_temp;
  assign r = r_temp;
  assign n = n_temp;
  assign a1 = a1_temp;
  assign a2 = a2_temp;
  assign a3 = a3_temp;
  assign t8 = t8_temp;
endmodule
