/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule


module memory (
  input [23:0] ADDR,
  input MEM_RD,
  input MEM_WR,
  input CLK,
  input [31:0] CPU_DIN,
  output [31:0] CPU_D_OUT
);
  wire \~WE ;
  wire \~OE ;
  assign \~WE  = ~ MEM_WR;
  assign \~OE  = ~ MEM_RD;
  DIG_RAMDualPort #(
    .Bits(32),
    .AddrBits(24)
  )
  DIG_RAMDualPort_i0 (
    .A( ADDR ),
    .Din( CPU_DIN ),
    .str( MEM_WR ),
    .C( CLK ),
    .ld( MEM_RD ),
    .D( CPU_D_OUT )
  );
endmodule
