/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_ROM_256X32_microcodeeeprom (
    input [7:0] A,
    input sel,
    output reg [31:0] D
);
    reg [31:0] my_rom [0:255];

    always @ (*) begin
        if (~sel)
            D = 32'hz;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 32'h1;
        my_rom[1] = 32'h96c802;
        my_rom[2] = 32'h69d822;
        my_rom[3] = 32'h88c802;
        my_rom[4] = 32'heec802;
        my_rom[5] = 32'h66c802;
        my_rom[6] = 32'h338802;
        my_rom[7] = 32'h0;
        my_rom[8] = 32'h0;
        my_rom[9] = 32'h0;
        my_rom[10] = 32'h0;
        my_rom[11] = 32'h0;
        my_rom[12] = 32'h0;
        my_rom[13] = 32'h0;
        my_rom[14] = 32'h0;
        my_rom[15] = 32'h0;
        my_rom[16] = 32'h802;
        my_rom[17] = 32'h802;
        my_rom[18] = 32'h802;
        my_rom[19] = 32'h802;
        my_rom[20] = 32'h802;
        my_rom[21] = 32'h0;
        my_rom[22] = 32'h0;
        my_rom[23] = 32'h0;
        my_rom[24] = 32'h0;
        my_rom[25] = 32'h0;
        my_rom[26] = 32'h0;
        my_rom[27] = 32'h0;
        my_rom[28] = 32'h0;
        my_rom[29] = 32'h0;
        my_rom[30] = 32'h0;
        my_rom[31] = 32'h0;
        my_rom[32] = 32'hc03;
        my_rom[33] = 32'h203;
        my_rom[34] = 32'hcc4802;
        my_rom[35] = 32'h0;
        my_rom[36] = 32'h0;
        my_rom[37] = 32'h0;
        my_rom[38] = 32'h0;
        my_rom[39] = 32'h0;
        my_rom[40] = 32'h0;
        my_rom[41] = 32'h0;
        my_rom[42] = 32'h0;
        my_rom[43] = 32'h0;
        my_rom[44] = 32'h0;
        my_rom[45] = 32'h0;
        my_rom[46] = 32'h0;
        my_rom[47] = 32'h0;
        my_rom[48] = 32'h182;
        my_rom[49] = 32'h102;
        my_rom[50] = 32'h18a;
        my_rom[51] = 32'h182;
        my_rom[52] = 32'h0;
        my_rom[53] = 32'h0;
        my_rom[54] = 32'h0;
        my_rom[55] = 32'h0;
        my_rom[56] = 32'h0;
        my_rom[57] = 32'h0;
        my_rom[58] = 32'h0;
        my_rom[59] = 32'h0;
        my_rom[60] = 32'h0;
        my_rom[61] = 32'h0;
        my_rom[62] = 32'h0;
        my_rom[63] = 32'h0;
        my_rom[64] = 32'h0;
        my_rom[65] = 32'h0;
        my_rom[66] = 32'h0;
        my_rom[67] = 32'h0;
        my_rom[68] = 32'h0;
        my_rom[69] = 32'h0;
        my_rom[70] = 32'h0;
        my_rom[71] = 32'h0;
        my_rom[72] = 32'h0;
        my_rom[73] = 32'h0;
        my_rom[74] = 32'h0;
        my_rom[75] = 32'h0;
        my_rom[76] = 32'h0;
        my_rom[77] = 32'h0;
        my_rom[78] = 32'h0;
        my_rom[79] = 32'h0;
        my_rom[80] = 32'h0;
        my_rom[81] = 32'h0;
        my_rom[82] = 32'h0;
        my_rom[83] = 32'h0;
        my_rom[84] = 32'h0;
        my_rom[85] = 32'h0;
        my_rom[86] = 32'h0;
        my_rom[87] = 32'h0;
        my_rom[88] = 32'h0;
        my_rom[89] = 32'h0;
        my_rom[90] = 32'h0;
        my_rom[91] = 32'h0;
        my_rom[92] = 32'h0;
        my_rom[93] = 32'h0;
        my_rom[94] = 32'h0;
        my_rom[95] = 32'h0;
        my_rom[96] = 32'h0;
        my_rom[97] = 32'h0;
        my_rom[98] = 32'h0;
        my_rom[99] = 32'h0;
        my_rom[100] = 32'h0;
        my_rom[101] = 32'h0;
        my_rom[102] = 32'h0;
        my_rom[103] = 32'h0;
        my_rom[104] = 32'h0;
        my_rom[105] = 32'h0;
        my_rom[106] = 32'h0;
        my_rom[107] = 32'h0;
        my_rom[108] = 32'h0;
        my_rom[109] = 32'h0;
        my_rom[110] = 32'h0;
        my_rom[111] = 32'h0;
        my_rom[112] = 32'h0;
        my_rom[113] = 32'h0;
        my_rom[114] = 32'h0;
        my_rom[115] = 32'h0;
        my_rom[116] = 32'h0;
        my_rom[117] = 32'h0;
        my_rom[118] = 32'h0;
        my_rom[119] = 32'h0;
        my_rom[120] = 32'h0;
        my_rom[121] = 32'h0;
        my_rom[122] = 32'h0;
        my_rom[123] = 32'h0;
        my_rom[124] = 32'h0;
        my_rom[125] = 32'h0;
        my_rom[126] = 32'h0;
        my_rom[127] = 32'h0;
        my_rom[128] = 32'h800002;
        my_rom[129] = 32'h810002;
        my_rom[130] = 32'h820002;
        my_rom[131] = 32'h830002;
        my_rom[132] = 32'h840002;
        my_rom[133] = 32'h850002;
        my_rom[134] = 32'h860002;
        my_rom[135] = 32'h870002;
        my_rom[136] = 32'h880002;
        my_rom[137] = 32'h890002;
        my_rom[138] = 32'h8a0002;
        my_rom[139] = 32'h8b0002;
        my_rom[140] = 32'h8c0002;
        my_rom[141] = 32'h8d0002;
        my_rom[142] = 32'h8e0002;
        my_rom[143] = 32'h8f0002;
        my_rom[144] = 32'h900002;
        my_rom[145] = 32'h910002;
        my_rom[146] = 32'h920002;
        my_rom[147] = 32'h930002;
        my_rom[148] = 32'h940002;
        my_rom[149] = 32'h950002;
        my_rom[150] = 32'h960002;
        my_rom[151] = 32'h970002;
        my_rom[152] = 32'h980002;
        my_rom[153] = 32'h990002;
        my_rom[154] = 32'h9a0002;
        my_rom[155] = 32'h9b0002;
        my_rom[156] = 32'h9c0002;
        my_rom[157] = 32'h9d0002;
        my_rom[158] = 32'h9e0002;
        my_rom[159] = 32'h9f0002;
        my_rom[160] = 32'ha00002;
        my_rom[161] = 32'ha10002;
        my_rom[162] = 32'ha20002;
        my_rom[163] = 32'ha30002;
        my_rom[164] = 32'ha40002;
        my_rom[165] = 32'ha50002;
        my_rom[166] = 32'ha60002;
        my_rom[167] = 32'ha70002;
        my_rom[168] = 32'ha80002;
        my_rom[169] = 32'ha90002;
        my_rom[170] = 32'haa0002;
        my_rom[171] = 32'hab0002;
        my_rom[172] = 32'hac0002;
        my_rom[173] = 32'had0002;
        my_rom[174] = 32'hae0002;
        my_rom[175] = 32'haf0002;
        my_rom[176] = 32'hb00002;
        my_rom[177] = 32'hb10002;
        my_rom[178] = 32'hb20002;
        my_rom[179] = 32'hb30002;
        my_rom[180] = 32'hb40002;
        my_rom[181] = 32'hb50002;
        my_rom[182] = 32'hb60002;
        my_rom[183] = 32'hb70002;
        my_rom[184] = 32'hb80002;
        my_rom[185] = 32'hb90002;
        my_rom[186] = 32'hba0002;
        my_rom[187] = 32'hbb0002;
        my_rom[188] = 32'hbc0002;
        my_rom[189] = 32'hbd0002;
        my_rom[190] = 32'hbe0002;
        my_rom[191] = 32'hbf0002;
        my_rom[192] = 32'hc00002;
        my_rom[193] = 32'hc10002;
        my_rom[194] = 32'hc20002;
        my_rom[195] = 32'hc30002;
        my_rom[196] = 32'hc40002;
        my_rom[197] = 32'hc50002;
        my_rom[198] = 32'hc60002;
        my_rom[199] = 32'hc70002;
        my_rom[200] = 32'hc80002;
        my_rom[201] = 32'hc90002;
        my_rom[202] = 32'hca0002;
        my_rom[203] = 32'hcb0002;
        my_rom[204] = 32'hcc0002;
        my_rom[205] = 32'hcd0002;
        my_rom[206] = 32'hce0002;
        my_rom[207] = 32'hcf0002;
        my_rom[208] = 32'hd00002;
        my_rom[209] = 32'hd10002;
        my_rom[210] = 32'hd20002;
        my_rom[211] = 32'hd30002;
        my_rom[212] = 32'hd40002;
        my_rom[213] = 32'hd50002;
        my_rom[214] = 32'hd60002;
        my_rom[215] = 32'hd70002;
        my_rom[216] = 32'hd80002;
        my_rom[217] = 32'hd90002;
        my_rom[218] = 32'hda0002;
        my_rom[219] = 32'hdb0002;
        my_rom[220] = 32'hdc0002;
        my_rom[221] = 32'hdd0002;
        my_rom[222] = 32'hde0002;
        my_rom[223] = 32'hdf0002;
        my_rom[224] = 32'he00002;
        my_rom[225] = 32'he10002;
        my_rom[226] = 32'he20002;
        my_rom[227] = 32'he30002;
        my_rom[228] = 32'he40002;
        my_rom[229] = 32'he50002;
        my_rom[230] = 32'he60002;
        my_rom[231] = 32'he70002;
        my_rom[232] = 32'he80002;
        my_rom[233] = 32'he90002;
        my_rom[234] = 32'hea0002;
        my_rom[235] = 32'heb0002;
        my_rom[236] = 32'hec0002;
        my_rom[237] = 32'hed0002;
        my_rom[238] = 32'hee0002;
        my_rom[239] = 32'hef0002;
        my_rom[240] = 32'hf00002;
        my_rom[241] = 32'hf10002;
        my_rom[242] = 32'hf20002;
        my_rom[243] = 32'hf30002;
        my_rom[244] = 32'hf40002;
        my_rom[245] = 32'hf50002;
        my_rom[246] = 32'hf60002;
        my_rom[247] = 32'hf70002;
        my_rom[248] = 32'hf80002;
        my_rom[249] = 32'hf90002;
        my_rom[250] = 32'hfa0002;
        my_rom[251] = 32'hfb0002;
        my_rom[252] = 32'hfc0002;
        my_rom[253] = 32'hfd0002;
        my_rom[254] = 32'hfe0002;
        my_rom[255] = 32'h2;
    end
endmodule


module microcode (
  input [7:0] op,
  output [7:0] \alu-op ,
  output [4:0] \alu-pre ,
  output \cin-sel ,
  output [1:0] \wb-sel ,
  output [1:0] \shift-op ,
  output \flags-we ,
  output \reg-we ,
  output \mem-rd ,
  output \mem-wr ,
  output \addr-csel ,
  output \branch-en ,
  output \jump-type ,
  output [1:0] \sp-op ,
  output [1:0] cycles,
  output [2:0] unused
);
  wire [31:0] s0;
  // microcode eeprom
  DIG_ROM_256X32_microcodeeeprom DIG_ROM_256X32_microcodeeeprom_i0 (
    .A( op ),
    .sel( 1'b1 ),
    .D( s0 )
  );
  assign \alu-op  = s0[7:0];
  assign \alu-pre  = s0[12:8];
  assign \cin-sel  = s0[13];
  assign \wb-sel  = s0[15:14];
  assign \shift-op  = s0[17:16];
  assign \flags-we  = s0[18];
  assign \reg-we  = s0[19];
  assign \mem-rd  = s0[20];
  assign \mem-wr  = s0[21];
  assign \addr-csel  = s0[22];
  assign \branch-en  = s0[23];
  assign \jump-type  = s0[24];
  assign \sp-op  = s0[26:25];
  assign cycles = s0[28:27];
  assign unused = s0[31:29];
endmodule
