/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module DriverInvBus#(
    parameter Bits = 2
)
(
    input [(Bits-1):0] in,
    input sel,
    output [(Bits-1):0] out
);
    assign out = (sel == 1'b0)? in : {Bits{1'bz}};
endmodule

module DriverBus#(
    parameter Bits = 2
)
(
    input [(Bits-1):0] in,
    input sel,
    output [(Bits-1):0] out
);
    assign out = (sel == 1'b1)? in : {Bits{1'bz}};
endmodule

module mmio_bus (
  input [23:0] ADDR,
  output [23:0] CPU_ADDR_OUT,
  output [23:0] MMIO_ADDR_OUT
);
  wire [3:0] s0;
  wire add_check;
  assign s0 = ADDR[23:20];
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i0 (
    .a( s0 ),
    .b( 4'b1111 ),
    .\= ( add_check )
  );
  DriverInvBus #(
    .Bits(24)
  )
  DriverInvBus_i1 (
    .in( ADDR ),
    .sel( add_check ),
    .out( CPU_ADDR_OUT )
  );
  DriverBus #(
    .Bits(24)
  )
  DriverBus_i2 (
    .in( ADDR ),
    .sel( add_check ),
    .out( MMIO_ADDR_OUT )
  );
endmodule
