/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

// hex inverter
module \7404  (
  input \1A ,
  input \2A ,
  input \3A ,
  input \4A ,
  input \5A ,
  input \6A ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y ,
  output \5Y ,
  output \6Y 
);
  assign \1Y  = ~ \1A ;
  assign \2Y  = ~ \2A ;
  assign \3Y  = ~ \3A ;
  assign \4Y  = ~ \4A ;
  assign \5Y  = ~ \5A ;
  assign \6Y  = ~ \6A ;
endmodule

module Mux_8x1
(
    input [2:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    output reg out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


// 3-line to 8-line data selectors/multiplexers
module \74151  (
  input A,
  input C,
  input B,
  input S,
  input D0,
  input D1,
  input D2,
  input D3,
  input D4,
  input D5,
  input D6,
  input D7,
  input VCC,
  input GND,
  output Y,
  output W
);
  wire [2:0] s0;
  wire s1;
  wire Y_temp;
  assign s0[0] = A;
  assign s0[1] = B;
  assign s0[2] = C;
  Mux_8x1 Mux_8x1_i0 (
    .sel( s0 ),
    .in_0( D0 ),
    .in_1( D1 ),
    .in_2( D2 ),
    .in_3( D3 ),
    .in_4( D4 ),
    .in_5( D5 ),
    .in_6( D6 ),
    .in_7( D7 ),
    .out( s1 )
  );
  assign Y_temp = (~ S & s1);
  assign W = ~ Y_temp;
  assign Y = Y_temp;
endmodule

module sc_branch (
  input FLAG_N,
  input FLAG_C,
  input FLAG_Z,
  input FLAG_O,
  input [2:0] COND,
  input BRANCH_EN,
  output COND_RESULT
);
  wire MUX_Y;
  wire COND_2;
  wire COND_1;
  wire COND_0;
  wire MUX_D7;
  wire \3Y ;
  wire \2Y ;
  wire \1Y ;
  \7404  \7404_i0 (
    .\1A ( FLAG_Z ),
    .\2A ( FLAG_C ),
    .\3A ( FLAG_N ),
    .GND( 1'b0 ),
    .\4A ( FLAG_O ),
    .\5A ( 1'b0 ),
    .\6A ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( \1Y  ),
    .\2Y ( \2Y  ),
    .\3Y ( \3Y  ),
    .\4Y ( MUX_D7 )
  );
  assign COND_0 = COND[0];
  assign COND_1 = COND[1];
  assign COND_2 = COND[2];
  // U1
  \74151  \74151_i1 (
    .D3( FLAG_O ),
    .D2( FLAG_N ),
    .D1( FLAG_C ),
    .D0( FLAG_Z ),
    .S( 1'b0 ),
    .GND( 1'b0 ),
    .C( COND_2 ),
    .B( COND_1 ),
    .A( COND_0 ),
    .D7( MUX_D7 ),
    .D6( \3Y  ),
    .D5( \2Y  ),
    .D4( \1Y  ),
    .VCC( 1'b1 ),
    .Y( MUX_Y )
  );
  assign COND_RESULT = (MUX_Y & BRANCH_EN);
endmodule

module DIG_D_FF_AS_1bit
#(
    parameter Default = 0
)
(
   input Set,
   input D,
   input C,
   input Clr,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q  = ~state;

    always @ (posedge C or posedge Clr or posedge Set)
    begin
        if (Set)
            state <= 1'b1;
        else if (Clr)
            state <= 'h0;
        else
            state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

// dual D-flip-flop
module \7474  (
  input \~1SD ,
  input \1D ,
  input \1CP ,
  input \~1RD ,
  input \~2SD ,
  input \2D ,
  input \2CP ,
  input \~2RD ,
  input VCC,
  input GND,
  output \1Q ,
  output \~1Q ,
  output \2Q ,
  output \~2Q 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s0 = ~ \~1SD ;
  assign s1 = ~ \~1RD ;
  assign s3 = ~ \~2SD ;
  assign s4 = ~ \~2RD ;
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i0 (
    .Set( s0 ),
    .D( \1D  ),
    .C( \1CP  ),
    .Clr( s1 ),
    .Q( \1Q  ),
    .\~Q ( s2 )
  );
  DIG_D_FF_AS_1bit #(
    .Default(0)
  )
  DIG_D_FF_AS_1bit_i1 (
    .Set( s3 ),
    .D( \2D  ),
    .C( \2CP  ),
    .Clr( s4 ),
    .Q( \2Q  ),
    .\~Q ( s5 )
  );
  assign \~1Q  = (s2 | (~ \~1SD  & ~ \~1RD ));
  assign \~2Q  = (s5 | (~ \~2SD  & ~ \~2RD ));
endmodule

module sc_control_flags (
  input INT_EN_IN,
  input HALT_IN,
  input INT_REQ,
  input INT_VEC_0,
  input INT_VEC_1,
  input INT_VEC_2,
  input CLK,
  output [23:0] INT_VECTOR,
  output INT_EN,
  output HALTED,
  output INT_GATE,
  output CLK_GATED
);
  wire INT_EN_temp;
  wire HALTED_temp;
  \7474  \7474_i0 (
    .\~1RD ( 1'b1 ),
    .\1D ( INT_EN_IN ),
    .\1CP ( CLK ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( CLK ),
    .\2D ( HALT_IN ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( INT_EN_temp ),
    .\2Q ( HALTED_temp )
  );
  assign INT_VECTOR[0] = 1'b0;
  assign INT_VECTOR[1] = 1'b0;
  assign INT_VECTOR[2] = 1'b0;
  assign INT_VECTOR[3] = INT_VEC_0;
  assign INT_VECTOR[4] = INT_VEC_1;
  assign INT_VECTOR[5] = INT_VEC_2;
  assign INT_VECTOR[6] = 1'b0;
  assign INT_VECTOR[7] = 1'b0;
  assign INT_VECTOR[8] = 1'b0;
  assign INT_VECTOR[9] = 1'b0;
  assign INT_VECTOR[10] = 1'b0;
  assign INT_VECTOR[11] = 1'b0;
  assign INT_VECTOR[12] = 1'b0;
  assign INT_VECTOR[13] = 1'b0;
  assign INT_VECTOR[14] = 1'b0;
  assign INT_VECTOR[15] = 1'b0;
  assign INT_VECTOR[16] = 1'b0;
  assign INT_VECTOR[17] = 1'b0;
  assign INT_VECTOR[18] = 1'b0;
  assign INT_VECTOR[19] = 1'b0;
  assign INT_VECTOR[20] = 1'b0;
  assign INT_VECTOR[21] = 1'b0;
  assign INT_VECTOR[22] = 1'b0;
  assign INT_VECTOR[23] = 1'b0;
  assign INT_GATE = (INT_REQ & INT_EN_temp);
  assign CLK_GATED = (CLK & ~ HALTED_temp);
  assign INT_EN = INT_EN_temp;
  assign HALTED = HALTED_temp;
endmodule

module sc_flags_save (
  input INT_GATE,
  input FLAG_N,
  input FLAG_C,
  input FLAG_Z,
  input FLAG_O,
  output [3:0] FLAGS_SAVE
);
  wire FLAGS_SAVE_Z;
  wire FLAGS_SAVE_C;
  wire FLAGS_SAVE_N;
  wire FLAGS_SAVE_O;
  \7474  \7474_i0 (
    .\~1RD ( 1'b1 ),
    .\1D ( FLAG_Z ),
    .\1CP ( INT_GATE ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( INT_GATE ),
    .\2D ( FLAG_C ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAGS_SAVE_Z ),
    .\2Q ( FLAGS_SAVE_C )
  );
  \7474  \7474_i1 (
    .\~1RD ( 1'b1 ),
    .\1D ( FLAG_N ),
    .\1CP ( INT_GATE ),
    .\~1SD ( 1'b1 ),
    .GND( 1'b0 ),
    .\~2SD ( 1'b1 ),
    .\2CP ( INT_GATE ),
    .\2D ( FLAG_O ),
    .\~2RD ( 1'b1 ),
    .VCC( 1'b1 ),
    .\1Q ( FLAGS_SAVE_N ),
    .\2Q ( FLAGS_SAVE_O )
  );
  assign FLAGS_SAVE[0] = FLAGS_SAVE_Z;
  assign FLAGS_SAVE[1] = FLAGS_SAVE_C;
  assign FLAGS_SAVE[2] = FLAGS_SAVE_N;
  assign FLAGS_SAVE[3] = FLAGS_SAVE_O;
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



// hex synchronous counter
module \74163  (
  input \~PE ,
  input \~SR ,
  input CP,
  input CET,
  input CEP,
  input P0,
  input P1,
  input P2,
  input P3,
  input VCC,
  input GND,
  output TC,
  output Q0,
  output Q1,
  output Q2,
  output Q3
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire s3;
  wire s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [3:0] s7;
  assign s4 = (CEP & CET);
  assign s6[0] = P0;
  assign s6[1] = P1;
  assign s6[2] = P2;
  assign s6[3] = P3;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( s4 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .out( s5 )
  );
  assign TC = (s3 & CET);
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( \~PE  ),
    .in_0( s6 ),
    .in_1( s5 ),
    .out( s7 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( \~SR  ),
    .in_0( 4'b0 ),
    .in_1( s7 ),
    .out( s0 )
  );
  // Q
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i3 (
    .D( s0 ),
    .C( CP ),
    .Q( s1 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i4 (
    .a( s1 ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s2 ),
    .c_o( s3 )
  );
  assign Q0 = s1[0];
  assign Q1 = s1[1];
  assign Q2 = s1[2];
  assign Q3 = s1[3];
endmodule

module sc_pc_counter (
  input \~SR ,
  input clk,
  input \~PE ,
  input [23:0] D,
  input \pc-en ,
  output [23:0] Q
);
  wire D_0;
  wire D_1;
  wire D_2;
  wire D_3;
  wire Q_3;
  wire Q_2;
  wire Q_1;
  wire Q_0;
  wire tc1;
  wire D_4;
  wire D_5;
  wire D_6;
  wire D_7;
  wire Q_7;
  wire Q_6;
  wire Q_5;
  wire Q_4;
  wire tc2;
  wire D_8;
  wire D_9;
  wire D_10;
  wire D_11;
  wire Q_11;
  wire Q_10;
  wire Q_9;
  wire Q_8;
  wire tc3;
  wire D_12;
  wire D_13;
  wire D_14;
  wire D_15;
  wire Q_15;
  wire Q_14;
  wire Q_13;
  wire Q_12;
  wire tc4;
  wire D_16;
  wire D_17;
  wire D_18;
  wire D_19;
  wire Q_19;
  wire Q_18;
  wire Q_17;
  wire Q_16;
  wire tc5;
  wire D_20;
  wire D_21;
  wire D_22;
  wire D_23;
  wire Q_23;
  wire Q_22;
  wire Q_21;
  wire Q_20;
  assign D_0 = D[0];
  assign D_1 = D[1];
  assign D_2 = D[2];
  assign D_3 = D[3];
  assign D_4 = D[4];
  assign D_5 = D[5];
  assign D_6 = D[6];
  assign D_7 = D[7];
  assign D_8 = D[8];
  assign D_9 = D[9];
  assign D_10 = D[10];
  assign D_11 = D[11];
  assign D_12 = D[12];
  assign D_13 = D[13];
  assign D_14 = D[14];
  assign D_15 = D[15];
  assign D_16 = D[16];
  assign D_17 = D[17];
  assign D_18 = D[18];
  assign D_19 = D[19];
  assign D_20 = D[20];
  assign D_21 = D[21];
  assign D_22 = D[22];
  assign D_23 = D[23];
  // U1
  \74163  \74163_i0 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_0 ),
    .P1( D_1 ),
    .P2( D_2 ),
    .P3( D_3 ),
    .CEP( \pc-en  ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( \pc-en  ),
    .VCC( 1'b1 ),
    .Q3( Q_3 ),
    .Q2( Q_2 ),
    .Q1( Q_1 ),
    .Q0( Q_0 ),
    .TC( tc1 )
  );
  // U2
  \74163  \74163_i1 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_4 ),
    .P1( D_5 ),
    .P2( D_6 ),
    .P3( D_7 ),
    .CEP( tc1 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc1 ),
    .VCC( 1'b1 ),
    .Q3( Q_7 ),
    .Q2( Q_6 ),
    .Q1( Q_5 ),
    .Q0( Q_4 ),
    .TC( tc2 )
  );
  // U3
  \74163  \74163_i2 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_8 ),
    .P1( D_9 ),
    .P2( D_10 ),
    .P3( D_11 ),
    .CEP( tc2 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc2 ),
    .VCC( 1'b1 ),
    .Q3( Q_11 ),
    .Q2( Q_10 ),
    .Q1( Q_9 ),
    .Q0( Q_8 ),
    .TC( tc3 )
  );
  // U4
  \74163  \74163_i3 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_12 ),
    .P1( D_13 ),
    .P2( D_14 ),
    .P3( D_15 ),
    .CEP( tc3 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc3 ),
    .VCC( 1'b1 ),
    .Q3( Q_15 ),
    .Q2( Q_14 ),
    .Q1( Q_13 ),
    .Q0( Q_12 ),
    .TC( tc4 )
  );
  // U5
  \74163  \74163_i4 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_16 ),
    .P1( D_17 ),
    .P2( D_18 ),
    .P3( D_19 ),
    .CEP( tc4 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc4 ),
    .VCC( 1'b1 ),
    .Q3( Q_19 ),
    .Q2( Q_18 ),
    .Q1( Q_17 ),
    .Q0( Q_16 ),
    .TC( tc5 )
  );
  // U6
  \74163  \74163_i5 (
    .\~SR ( \~SR  ),
    .CP( clk ),
    .P0( D_20 ),
    .P1( D_21 ),
    .P2( D_22 ),
    .P3( D_23 ),
    .CEP( tc5 ),
    .GND( 1'b0 ),
    .\~PE ( \~PE  ),
    .CET( tc5 ),
    .VCC( 1'b1 ),
    .Q3( Q_23 ),
    .Q2( Q_22 ),
    .Q1( Q_21 ),
    .Q0( Q_20 )
  );
  assign Q[0] = Q_0;
  assign Q[1] = Q_1;
  assign Q[2] = Q_2;
  assign Q[3] = Q_3;
  assign Q[4] = Q_4;
  assign Q[5] = Q_5;
  assign Q[6] = Q_6;
  assign Q[7] = Q_7;
  assign Q[8] = Q_8;
  assign Q[9] = Q_9;
  assign Q[10] = Q_10;
  assign Q[11] = Q_11;
  assign Q[12] = Q_12;
  assign Q[13] = Q_13;
  assign Q[14] = Q_14;
  assign Q[15] = Q_15;
  assign Q[16] = Q_16;
  assign Q[17] = Q_17;
  assign Q[18] = Q_18;
  assign Q[19] = Q_19;
  assign Q[20] = Q_20;
  assign Q[21] = Q_21;
  assign Q[22] = Q_22;
  assign Q[23] = Q_23;
endmodule

// 4-bit binary full adder, alternative pinning
module \74283  (
  input C0,
  input B1,
  input B2,
  input B3,
  input B4,
  input A1,
  input A2,
  input A3,
  input A4,
  input VCC,
  input GND,
  output S1,
  output S2,
  output S3,
  output S4,
  output C4
);
  wire [3:0] s0;
  wire [3:0] s5;
  wire [3:0] s6;
  assign s5[0] = B1;
  assign s5[1] = B2;
  assign s5[2] = B3;
  assign s5[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i0 (
    .a( s0 ),
    .b( s5 ),
    .c_i( C0 ),
    .s( s6 ),
    .c_o( C4 )
  );
  assign S1 = s6[0];
  assign S2 = s6[1];
  assign S3 = s6[2];
  assign S4 = s6[3];
endmodule

module sc_adder24 (
  input [23:0] B,
  input [23:0] A,
  output [23:0] S
);
  wire A_0;
  wire A_1;
  wire A_2;
  wire A_3;
  wire A_4;
  wire A_5;
  wire A_6;
  wire A_7;
  wire A_8;
  wire A_9;
  wire A_10;
  wire A_11;
  wire A_12;
  wire A_13;
  wire A_14;
  wire A_15;
  wire A_16;
  wire A_17;
  wire A_18;
  wire A_19;
  wire A_20;
  wire A_21;
  wire A_22;
  wire A_23;
  wire S_1;
  wire B_1;
  wire S_0;
  wire B_0;
  wire C_1;
  wire S_3;
  wire B_3;
  wire S_2;
  wire B_2;
  wire S_5;
  wire B_5;
  wire S_4;
  wire B_4;
  wire C_2;
  wire S_7;
  wire B_7;
  wire S_6;
  wire B_6;
  wire S_9;
  wire B_9;
  wire S_8;
  wire B_8;
  wire C_3;
  wire S_11;
  wire B_11;
  wire S_10;
  wire B_10;
  wire S_13;
  wire B_13;
  wire S_12;
  wire B_12;
  wire C_4;
  wire S_15;
  wire B_15;
  wire S_14;
  wire B_14;
  wire S_17;
  wire B_17;
  wire S_16;
  wire B_16;
  wire C_5;
  wire S_19;
  wire B_19;
  wire S_18;
  wire B_18;
  wire S_21;
  wire B_21;
  wire S_20;
  wire B_20;
  wire S_23;
  wire B_23;
  wire S_22;
  wire B_22;
  assign A_0 = A[0];
  assign A_1 = A[1];
  assign A_2 = A[2];
  assign A_3 = A[3];
  assign A_4 = A[4];
  assign A_5 = A[5];
  assign A_6 = A[6];
  assign A_7 = A[7];
  assign A_8 = A[8];
  assign A_9 = A[9];
  assign A_10 = A[10];
  assign A_11 = A[11];
  assign A_12 = A[12];
  assign A_13 = A[13];
  assign A_14 = A[14];
  assign A_15 = A[15];
  assign A_16 = A[16];
  assign A_17 = A[17];
  assign A_18 = A[18];
  assign A_19 = A[19];
  assign A_20 = A[20];
  assign A_21 = A[21];
  assign A_22 = A[22];
  assign A_23 = A[23];
  assign B_0 = B[0];
  assign B_1 = B[1];
  assign B_2 = B[2];
  assign B_3 = B[3];
  assign B_4 = B[4];
  assign B_5 = B[5];
  assign B_6 = B[6];
  assign B_7 = B[7];
  assign B_8 = B[8];
  assign B_9 = B[9];
  assign B_10 = B[10];
  assign B_11 = B[11];
  assign B_12 = B[12];
  assign B_13 = B[13];
  assign B_14 = B[14];
  assign B_15 = B[15];
  assign B_16 = B[16];
  assign B_17 = B[17];
  assign B_18 = B[18];
  assign B_19 = B[19];
  assign B_20 = B[20];
  assign B_21 = B[21];
  assign B_22 = B[22];
  assign B_23 = B[23];
  // U1
  \74283  \74283_i0 (
    .B2( B_1 ),
    .A2( A_1 ),
    .A1( A_0 ),
    .B1( B_0 ),
    .C0( 1'b0 ),
    .GND( 1'b0 ),
    .B4( B_3 ),
    .A4( A_3 ),
    .A3( A_2 ),
    .B3( B_2 ),
    .VCC( 1'b1 ),
    .S2( S_1 ),
    .S1( S_0 ),
    .C4( C_1 ),
    .S4( S_3 ),
    .S3( S_2 )
  );
  // U2
  \74283  \74283_i1 (
    .B2( B_5 ),
    .A2( A_5 ),
    .A1( A_4 ),
    .B1( B_4 ),
    .C0( C_1 ),
    .GND( 1'b0 ),
    .B4( B_7 ),
    .A4( A_7 ),
    .A3( A_6 ),
    .B3( B_6 ),
    .VCC( 1'b1 ),
    .S2( S_5 ),
    .S1( S_4 ),
    .C4( C_2 ),
    .S4( S_7 ),
    .S3( S_6 )
  );
  // U3
  \74283  \74283_i2 (
    .B2( B_9 ),
    .A2( A_9 ),
    .A1( A_8 ),
    .B1( B_8 ),
    .C0( C_2 ),
    .GND( 1'b0 ),
    .B4( B_11 ),
    .A4( A_11 ),
    .A3( A_10 ),
    .B3( B_10 ),
    .VCC( 1'b1 ),
    .S2( S_9 ),
    .S1( S_8 ),
    .C4( C_3 ),
    .S4( S_11 ),
    .S3( S_10 )
  );
  // U4
  \74283  \74283_i3 (
    .B2( B_13 ),
    .A2( A_13 ),
    .A1( A_12 ),
    .B1( B_12 ),
    .C0( C_3 ),
    .GND( 1'b0 ),
    .B4( B_15 ),
    .A4( A_15 ),
    .A3( A_14 ),
    .B3( B_14 ),
    .VCC( 1'b1 ),
    .S2( S_13 ),
    .S1( S_12 ),
    .C4( C_4 ),
    .S4( S_15 ),
    .S3( S_14 )
  );
  // U5
  \74283  \74283_i4 (
    .B2( B_17 ),
    .A2( A_17 ),
    .A1( A_16 ),
    .B1( B_16 ),
    .C0( C_4 ),
    .GND( 1'b0 ),
    .B4( B_19 ),
    .A4( A_19 ),
    .A3( A_18 ),
    .B3( B_18 ),
    .VCC( 1'b1 ),
    .S2( S_17 ),
    .S1( S_16 ),
    .C4( C_5 ),
    .S4( S_19 ),
    .S3( S_18 )
  );
  // U6
  \74283  \74283_i5 (
    .B2( B_21 ),
    .A2( A_21 ),
    .A1( A_20 ),
    .B1( B_20 ),
    .C0( C_5 ),
    .GND( 1'b0 ),
    .B4( B_23 ),
    .A4( A_23 ),
    .A3( A_22 ),
    .B3( B_22 ),
    .VCC( 1'b1 ),
    .S2( S_21 ),
    .S1( S_20 ),
    .S4( S_23 ),
    .S3( S_22 )
  );
  assign S[0] = S_0;
  assign S[1] = S_1;
  assign S[2] = S_2;
  assign S[3] = S_3;
  assign S[4] = S_4;
  assign S[5] = S_5;
  assign S[6] = S_6;
  assign S[7] = S_7;
  assign S[8] = S_8;
  assign S[9] = S_9;
  assign S[10] = S_10;
  assign S[11] = S_11;
  assign S[12] = S_12;
  assign S[13] = S_13;
  assign S[14] = S_14;
  assign S[15] = S_15;
  assign S[16] = S_16;
  assign S[17] = S_17;
  assign S[18] = S_18;
  assign S[19] = S_19;
  assign S[20] = S_20;
  assign S[21] = S_21;
  assign S[22] = S_22;
  assign S[23] = S_23;
endmodule

// quad 2-line to 1-line data selectors/multiplexers
module \74157  (
  input S, // select
  input A1,
  input A2,
  input A3,
  input A4,
  input B1,
  input B2,
  input B3,
  input B4,
  input G, // strobe
  input VCC,
  input GND,
  output Y1,
  output Y2,
  output Y3,
  output Y4
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  assign s1[0] = B1;
  assign s1[1] = B2;
  assign s1[2] = B3;
  assign s1[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( S ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( G ),
    .in_0( s2 ),
    .in_1( 4'b0 ),
    .out( s3 )
  );
  assign Y1 = s3[0];
  assign Y2 = s3[1];
  assign Y3 = s3[2];
  assign Y4 = s3[3];
endmodule

module sc_mux24_2to1 (
  input [23:0] B,
  input [23:0] A,
  input SEL,
  output [23:0] Y
);
  wire A_0;
  wire B_0;
  wire Y_0;
  wire A_1;
  wire B_1;
  wire Y_1;
  wire Y_2;
  wire B_2;
  wire A_2;
  wire Y_3;
  wire B_3;
  wire A_3;
  wire A_4;
  wire B_4;
  wire Y_4;
  wire A_5;
  wire B_5;
  wire Y_5;
  wire Y_6;
  wire B_6;
  wire A_6;
  wire Y_7;
  wire B_7;
  wire A_7;
  wire A_8;
  wire B_8;
  wire Y_8;
  wire A_9;
  wire B_9;
  wire Y_9;
  wire Y_10;
  wire B_10;
  wire A_10;
  wire Y_11;
  wire B_11;
  wire A_11;
  wire A_12;
  wire B_12;
  wire Y_12;
  wire A_13;
  wire B_13;
  wire Y_13;
  wire Y_14;
  wire B_14;
  wire A_14;
  wire Y_15;
  wire B_15;
  wire A_15;
  wire A_16;
  wire B_16;
  wire Y_16;
  wire A_17;
  wire B_17;
  wire Y_17;
  wire Y_18;
  wire B_18;
  wire A_18;
  wire Y_19;
  wire B_19;
  wire A_19;
  wire A_20;
  wire B_20;
  wire Y_20;
  wire A_21;
  wire B_21;
  wire Y_21;
  wire Y_22;
  wire B_22;
  wire A_22;
  wire Y_23;
  wire B_23;
  wire A_23;
  assign A_0 = A[0];
  assign A_1 = A[1];
  assign A_2 = A[2];
  assign A_3 = A[3];
  assign A_4 = A[4];
  assign A_5 = A[5];
  assign A_6 = A[6];
  assign A_7 = A[7];
  assign A_8 = A[8];
  assign A_9 = A[9];
  assign A_10 = A[10];
  assign A_11 = A[11];
  assign A_12 = A[12];
  assign A_13 = A[13];
  assign A_14 = A[14];
  assign A_15 = A[15];
  assign A_16 = A[16];
  assign A_17 = A[17];
  assign A_18 = A[18];
  assign A_19 = A[19];
  assign A_20 = A[20];
  assign A_21 = A[21];
  assign A_22 = A[22];
  assign A_23 = A[23];
  assign B_0 = B[0];
  assign B_1 = B[1];
  assign B_2 = B[2];
  assign B_3 = B[3];
  assign B_4 = B[4];
  assign B_5 = B[5];
  assign B_6 = B[6];
  assign B_7 = B[7];
  assign B_8 = B[8];
  assign B_9 = B[9];
  assign B_10 = B[10];
  assign B_11 = B[11];
  assign B_12 = B[12];
  assign B_13 = B[13];
  assign B_14 = B[14];
  assign B_15 = B[15];
  assign B_16 = B[16];
  assign B_17 = B[17];
  assign B_18 = B[18];
  assign B_19 = B[19];
  assign B_20 = B[20];
  assign B_21 = B[21];
  assign B_22 = B[22];
  assign B_23 = B[23];
  // U1
  \74157  \74157_i0 (
    .S( SEL ),
    .A1( A_0 ),
    .B1( B_0 ),
    .A2( A_1 ),
    .B2( B_1 ),
    .GND( 1'b0 ),
    .B3( B_2 ),
    .A3( A_2 ),
    .B4( B_3 ),
    .A4( A_3 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( Y_0 ),
    .Y2( Y_1 ),
    .Y3( Y_2 ),
    .Y4( Y_3 )
  );
  // U2
  \74157  \74157_i1 (
    .S( SEL ),
    .A1( A_4 ),
    .B1( B_4 ),
    .A2( A_5 ),
    .B2( B_5 ),
    .GND( 1'b0 ),
    .B3( B_6 ),
    .A3( A_6 ),
    .B4( B_7 ),
    .A4( A_7 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( Y_4 ),
    .Y2( Y_5 ),
    .Y3( Y_6 ),
    .Y4( Y_7 )
  );
  // U3
  \74157  \74157_i2 (
    .S( SEL ),
    .A1( A_8 ),
    .B1( B_8 ),
    .A2( A_9 ),
    .B2( B_9 ),
    .GND( 1'b0 ),
    .B3( B_10 ),
    .A3( A_10 ),
    .B4( B_11 ),
    .A4( A_11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( Y_8 ),
    .Y2( Y_9 ),
    .Y3( Y_10 ),
    .Y4( Y_11 )
  );
  // U4
  \74157  \74157_i3 (
    .S( SEL ),
    .A1( A_12 ),
    .B1( B_12 ),
    .A2( A_13 ),
    .B2( B_13 ),
    .GND( 1'b0 ),
    .B3( B_14 ),
    .A3( A_14 ),
    .B4( B_15 ),
    .A4( A_15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( Y_12 ),
    .Y2( Y_13 ),
    .Y3( Y_14 ),
    .Y4( Y_15 )
  );
  // U5
  \74157  \74157_i4 (
    .S( SEL ),
    .A1( A_16 ),
    .B1( B_16 ),
    .A2( A_17 ),
    .B2( B_17 ),
    .GND( 1'b0 ),
    .B3( B_18 ),
    .A3( A_18 ),
    .B4( B_19 ),
    .A4( A_19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( Y_16 ),
    .Y2( Y_17 ),
    .Y3( Y_18 ),
    .Y4( Y_19 )
  );
  // U6
  \74157  \74157_i5 (
    .S( SEL ),
    .A1( A_20 ),
    .B1( B_20 ),
    .A2( A_21 ),
    .B2( B_21 ),
    .GND( 1'b0 ),
    .B3( B_22 ),
    .A3( A_22 ),
    .B4( B_23 ),
    .A4( A_23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( Y_20 ),
    .Y2( Y_21 ),
    .Y3( Y_22 ),
    .Y4( Y_23 )
  );
  assign Y[0] = Y_0;
  assign Y[1] = Y_1;
  assign Y[2] = Y_2;
  assign Y[3] = Y_3;
  assign Y[4] = Y_4;
  assign Y[5] = Y_5;
  assign Y[6] = Y_6;
  assign Y[7] = Y_7;
  assign Y[8] = Y_8;
  assign Y[9] = Y_9;
  assign Y[10] = Y_10;
  assign Y[11] = Y_11;
  assign Y[12] = Y_12;
  assign Y[13] = Y_13;
  assign Y[14] = Y_14;
  assign Y[15] = Y_15;
  assign Y[16] = Y_16;
  assign Y[17] = Y_17;
  assign Y[18] = Y_18;
  assign Y[19] = Y_19;
  assign Y[20] = Y_20;
  assign Y[21] = Y_21;
  assign Y[22] = Y_22;
  assign Y[23] = Y_23;
endmodule

module pc (
  input CLK,
  input \~SR ,
  input [23:0] ADDR_ABS,
  input [23:0] OFFSET,
  input [23:0] ADDR_RET,
  input MUX1_SEL,
  input MUX2_SEL,
  input FLAG_N,
  input FLAG_C,
  input FLAG_Z,
  input FLAG_O,
  input [2:0] COND,
  input BRANCH_EN,
  input INT_EN_IN,
  input HALT_IN,
  input INT_REQ,
  input INT_VEC_0,
  input INT_VEC_1,
  input INT_VEC_2,
  input [23:0] SP_DELTA,
  input SP_LOAD_N,
  input JUMP_UNCOND,
  input \pc-en ,
  output INT_EN,
  output HALTED,
  output [23:0] PC_OUT,
  output [23:0] SP_OUT,
  output INT_ACK,
  output [3:0] FLAGS_SAVE,
  output [23:0] PC_SAVE
);
  wire CLK_GATED;
  wire PC_LOAD_N;
  wire [23:0] LOAD_ADDR;
  wire [23:0] PC_OUT_temp;
  wire [23:0] SP_OUT_temp;
  wire [23:0] SP_D;
  wire COND_RESULT;
  wire [23:0] PC_REL;
  wire [23:0] L1_OUT;
  wire [23:0] \SC2-2Y ;
  wire [23:0] INT_VECTOR;
  wire INT_ACK_temp;
  wire [23:0] \PC+1 ;
  // SC4-1
  sc_branch sc_branch_i0 (
    .FLAG_N( FLAG_N ),
    .FLAG_C( FLAG_C ),
    .FLAG_Z( FLAG_Z ),
    .FLAG_O( FLAG_O ),
    .COND( COND ),
    .BRANCH_EN( BRANCH_EN ),
    .COND_RESULT( COND_RESULT )
  );
  // SC5-1
  sc_control_flags sc_control_flags_i1 (
    .INT_EN_IN( INT_EN_IN ),
    .HALT_IN( HALT_IN ),
    .INT_REQ( INT_REQ ),
    .INT_VEC_0( INT_VEC_0 ),
    .INT_VEC_1( INT_VEC_1 ),
    .INT_VEC_2( INT_VEC_2 ),
    .CLK( CLK ),
    .INT_VECTOR( INT_VECTOR ),
    .INT_EN( INT_EN ),
    .HALTED( HALTED ),
    .INT_GATE( INT_ACK_temp ),
    .CLK_GATED( CLK_GATED )
  );
  assign \PC+1 [0] = 1'b1;
  assign \PC+1 [1] = 1'b0;
  assign \PC+1 [2] = 1'b0;
  assign \PC+1 [3] = 1'b0;
  assign \PC+1 [4] = 1'b0;
  assign \PC+1 [5] = 1'b0;
  assign \PC+1 [6] = 1'b0;
  assign \PC+1 [7] = 1'b0;
  assign \PC+1 [8] = 1'b0;
  assign \PC+1 [9] = 1'b0;
  assign \PC+1 [10] = 1'b0;
  assign \PC+1 [11] = 1'b0;
  assign \PC+1 [12] = 1'b0;
  assign \PC+1 [13] = 1'b0;
  assign \PC+1 [14] = 1'b0;
  assign \PC+1 [15] = 1'b0;
  assign \PC+1 [16] = 1'b0;
  assign \PC+1 [17] = 1'b0;
  assign \PC+1 [18] = 1'b0;
  assign \PC+1 [19] = 1'b0;
  assign \PC+1 [20] = 1'b0;
  assign \PC+1 [21] = 1'b0;
  assign \PC+1 [22] = 1'b0;
  assign \PC+1 [23] = 1'b0;
  // SC6-1
  sc_flags_save sc_flags_save_i2 (
    .INT_GATE( INT_ACK_temp ),
    .FLAG_N( FLAG_N ),
    .FLAG_C( FLAG_C ),
    .FLAG_Z( FLAG_Z ),
    .FLAG_O( FLAG_O ),
    .FLAGS_SAVE( FLAGS_SAVE )
  );
  assign PC_LOAD_N = ~ (COND_RESULT | INT_ACK_temp | JUMP_UNCOND);
  // SC1-1
  sc_pc_counter sc_pc_counter_i3 (
    .\~SR ( \~SR  ),
    .clk( CLK_GATED ),
    .\~PE ( PC_LOAD_N ),
    .D( LOAD_ADDR ),
    .\pc-en ( \pc-en  ),
    .Q( PC_OUT_temp )
  );
  // SC2-2
  sc_adder24 sc_adder24_i4 (
    .B( SP_DELTA ),
    .A( SP_OUT_temp ),
    .S( SP_D )
  );
  // SC1-2
  sc_pc_counter sc_pc_counter_i5 (
    .\~SR ( \~SR  ),
    .clk( CLK_GATED ),
    .\~PE ( SP_LOAD_N ),
    .D( SP_D ),
    .\pc-en ( \pc-en  ),
    .Q( SP_OUT_temp )
  );
  // SC2-1
  sc_adder24 sc_adder24_i6 (
    .B( OFFSET ),
    .A( PC_OUT_temp ),
    .S( PC_REL )
  );
  // SC3-1
  sc_mux24_2to1 sc_mux24_2to1_i7 (
    .B( PC_REL ),
    .A( ADDR_ABS ),
    .SEL( MUX1_SEL ),
    .Y( L1_OUT )
  );
  // SC3-2
  sc_mux24_2to1 sc_mux24_2to1_i8 (
    .B( ADDR_RET ),
    .A( L1_OUT ),
    .SEL( MUX2_SEL ),
    .Y( \SC2-2Y  )
  );
  // SC3-3
  sc_mux24_2to1 sc_mux24_2to1_i9 (
    .B( INT_VECTOR ),
    .A( \SC2-2Y  ),
    .SEL( INT_ACK_temp ),
    .Y( LOAD_ADDR )
  );
  // SC2-3
  sc_adder24 sc_adder24_i10 (
    .B( \PC+1  ),
    .A( PC_OUT_temp ),
    .S( PC_SAVE )
  );
  assign PC_OUT = PC_OUT_temp;
  assign SP_OUT = SP_OUT_temp;
  assign INT_ACK = INT_ACK_temp;
endmodule
