/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_RAMDualAccess
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
    input C, // Clock signal
    input ld,
    input [(AddrBits-1):0] \1A ,
    input [(AddrBits-1):0] \2A ,
    input [(Bits-1):0] \1Din ,
    input str,
    output [(Bits-1):0] \1D ,
    output [(Bits-1):0] \2D
);
    // CAUTION: uses distributed RAM
    reg [(Bits-1):0] memory [0:((1 << AddrBits)-1)];

    assign \1D = ld? memory[\1A ] : 'hz;
    assign \2D = memory[\2A ];

    always @ (posedge C) begin
        if (str)
            memory[\1A ] <= \1Din ;
    end

endmodule



module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module register (
  input WE,
  input [31:0] DATA_W,
  input [7:0] ADDR_A,
  input [7:0] ADDR_B,
  input [7:0] ADDR_W,
  input clock,
  input EXEC,
  input addr_c_sel,
  input [7:0] IR_ADDR_CIN,
  output [31:0] DATA_A,
  output [31:0] DATA_B,
  output [31:0] DATA_C
);
  wire \ram-and ;
  wire [7:0] ADDR_C;
  wire [7:0] \0x00 ;
  assign \ram-and  = (EXEC & WE);
  assign \0x00 [0] = 1'b0;
  assign \0x00 [1] = 1'b0;
  assign \0x00 [2] = 1'b0;
  assign \0x00 [3] = 1'b0;
  assign \0x00 [4] = 1'b0;
  assign \0x00 [5] = 1'b0;
  assign \0x00 [6] = 1'b0;
  assign \0x00 [7] = 1'b0;
  // U1
  DIG_RAMDualAccess #(
    .Bits(32),
    .AddrBits(8)
  )
  DIG_RAMDualAccess_i0 (
    .str( \ram-and  ),
    .C( clock ),
    .ld( 1'b1 ),
    .\1A ( ADDR_W ),
    .\1Din ( DATA_W ),
    .\2A ( ADDR_A ),
    .\2D ( DATA_A )
  );
  // U2
  DIG_RAMDualAccess #(
    .Bits(32),
    .AddrBits(8)
  )
  DIG_RAMDualAccess_i1 (
    .str( \ram-and  ),
    .C( clock ),
    .ld( 1'b1 ),
    .\1A ( ADDR_W ),
    .\1Din ( DATA_W ),
    .\2A ( ADDR_B ),
    .\2D ( DATA_B )
  );
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i2 (
    .sel( addr_c_sel ),
    .in_0( \0x00  ),
    .in_1( IR_ADDR_CIN ),
    .out( ADDR_C )
  );
  // U3
  DIG_RAMDualAccess #(
    .Bits(32),
    .AddrBits(8)
  )
  DIG_RAMDualAccess_i3 (
    .str( \ram-and  ),
    .C( clock ),
    .ld( 1'b1 ),
    .\1A ( ADDR_W ),
    .\1Din ( DATA_W ),
    .\2A ( ADDR_C ),
    .\2D ( DATA_C )
  );
endmodule
