/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



// hex synchronous counter
module \74163  (
  input \~PE ,
  input \~SR ,
  input CP,
  input CET,
  input CEP,
  input P0,
  input P1,
  input P2,
  input P3,
  input VCC,
  input GND,
  output TC,
  output Q0,
  output Q1,
  output Q2,
  output Q3
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire s3;
  wire s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [3:0] s7;
  assign s4 = (CEP & CET);
  assign s6[0] = P0;
  assign s6[1] = P1;
  assign s6[2] = P2;
  assign s6[3] = P3;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( s4 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .out( s5 )
  );
  assign TC = (s3 & CET);
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( \~PE  ),
    .in_0( s6 ),
    .in_1( s5 ),
    .out( s7 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( \~SR  ),
    .in_0( 4'b0 ),
    .in_1( s7 ),
    .out( s0 )
  );
  // Q
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i3 (
    .D( s0 ),
    .C( CP ),
    .Q( s1 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i4 (
    .a( s1 ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s2 ),
    .c_o( s3 )
  );
  assign Q0 = s1[0];
  assign Q1 = s1[1];
  assign Q2 = s1[2];
  assign Q3 = s1[3];
endmodule

module sequencer (
  input reset,
  input [1:0] cycles,
  input CLK,
  output FETCH,
  output EXECUTE,
  output MEM_WAIT
);
  wire RESET_N;
  wire \~clk ;
  wire UNUSED_Q3;
  wire UNUSED_Q2;
  wire SEQ_Q1;
  wire SEQ_Q0;
  wire SEQ_TC;
  wire SEQ_Q0_N;
  wire SEQ_Q1_N;
  assign \~clk  = ~ CLK;
  \74163  \74163_i0 (
    .\~SR ( RESET_N ),
    .CP( \~clk  ),
    .P0( 1'b0 ),
    .P1( 1'b0 ),
    .P2( 1'b0 ),
    .P3( 1'b0 ),
    .CEP( 1'b1 ),
    .GND( 1'b0 ),
    .\~PE ( 1'b1 ),
    .CET( 1'b1 ),
    .VCC( 1'b1 ),
    .Q3( UNUSED_Q3 ),
    .Q2( UNUSED_Q2 ),
    .Q1( SEQ_Q1 ),
    .Q0( SEQ_Q0 ),
    .TC( SEQ_TC )
  );
  assign RESET_N = (~ (~ reset) & ~ (~ (SEQ_Q0 ^ cycles[0]) & ~ (SEQ_Q1 ^ cycles[1])));
  assign SEQ_Q0_N = ~ SEQ_Q0;
  assign SEQ_Q1_N = ~ SEQ_Q1;
  assign FETCH = (SEQ_Q0_N & SEQ_Q1_N);
  assign EXECUTE = (SEQ_Q0 & SEQ_Q1_N);
  assign MEM_WAIT = (SEQ_Q0_N & SEQ_Q1);
endmodule
