/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


// quad 2-line to 1-line data selectors/multiplexers
module \74157  (
  input S, // select
  input A1,
  input A2,
  input A3,
  input A4,
  input B1,
  input B2,
  input B3,
  input B4,
  input G, // strobe
  input VCC,
  input GND,
  output Y1,
  output Y2,
  output Y3,
  output Y4
);
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  assign s1[0] = B1;
  assign s1[1] = B2;
  assign s1[2] = B3;
  assign s1[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i0 (
    .sel( S ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i1 (
    .sel( G ),
    .in_0( s2 ),
    .in_1( 4'b0 ),
    .out( s3 )
  );
  assign Y1 = s3[0];
  assign Y2 = s3[1];
  assign Y3 = s3[2];
  assign Y4 = s3[3];
endmodule

module shift (
  input [31:0] A,
  input [1:0] mode,
  input [4:0] B,
  output [31:0] Out
);
  wire shamt2;
  wire stg2_b00;
  wire stg2_b04;
  wire stg3_b00;
  wire stg2_b01;
  wire stg2_b05;
  wire stg3_b01;
  wire stg3_b02;
  wire stg2_b06;
  wire stg2_b02;
  wire stg3_b03;
  wire stg2_b07;
  wire stg2_b03;
  wire stg2_b08;
  wire stg3_b04;
  wire stg2_b09;
  wire stg3_b05;
  wire stg3_b06;
  wire stg2_b10;
  wire stg3_b07;
  wire stg2_b11;
  wire stg2_b12;
  wire stg3_b08;
  wire stg2_b13;
  wire stg3_b09;
  wire stg3_b10;
  wire stg2_b14;
  wire stg3_b11;
  wire stg2_b15;
  wire stg2_b16;
  wire stg3_b12;
  wire stg2_b17;
  wire stg3_b13;
  wire stg3_b14;
  wire stg2_b18;
  wire stg3_b15;
  wire stg2_b19;
  wire stg2_b20;
  wire stg3_b16;
  wire stg2_b21;
  wire stg3_b17;
  wire stg3_b18;
  wire stg2_b22;
  wire stg3_b19;
  wire stg2_b23;
  wire stg2_b24;
  wire stg3_b20;
  wire stg2_b25;
  wire stg3_b21;
  wire stg3_b22;
  wire stg2_b26;
  wire stg3_b23;
  wire stg2_b27;
  wire stg2_b28;
  wire stg3_b24;
  wire stg2_b29;
  wire stg3_b25;
  wire stg3_b26;
  wire stg2_b30;
  wire stg3_b27;
  wire stg2_b31;
  wire fill;
  wire stg3_b28;
  wire stg3_b29;
  wire stg3_b30;
  wire stg3_b31;
  wire in_b00;
  wire in_b01;
  wire in_b02;
  wire in_b03;
  wire in_b04;
  wire in_b05;
  wire in_b06;
  wire in_b07;
  wire in_b08;
  wire in_b09;
  wire in_b10;
  wire in_b11;
  wire in_b12;
  wire in_b13;
  wire in_b14;
  wire in_b15;
  wire in_b16;
  wire in_b17;
  wire in_b18;
  wire in_b19;
  wire in_b20;
  wire in_b21;
  wire in_b22;
  wire in_b23;
  wire in_b24;
  wire in_b25;
  wire in_b26;
  wire in_b27;
  wire in_b28;
  wire in_b29;
  wire in_b30;
  wire in_b31;
  wire shamt0;
  wire shamt1;
  wire shamt3;
  wire shamt4;
  wire out_b00;
  wire out_b01;
  wire out_b02;
  wire out_b03;
  wire out_b04;
  wire out_b05;
  wire out_b06;
  wire out_b07;
  wire out_b08;
  wire out_b09;
  wire out_b10;
  wire out_b11;
  wire out_b12;
  wire out_b13;
  wire out_b14;
  wire out_b15;
  wire out_b16;
  wire out_b17;
  wire out_b18;
  wire out_b19;
  wire out_b20;
  wire out_b21;
  wire out_b22;
  wire out_b23;
  wire out_b24;
  wire out_b25;
  wire out_b26;
  wire out_b27;
  wire out_b28;
  wire out_b29;
  wire out_b30;
  wire out_b31;
  wire stg4_b00;
  wire stg4_b01;
  wire stg4_b02;
  wire stg4_b03;
  wire stg4_b04;
  wire stg4_b05;
  wire stg4_b06;
  wire stg4_b07;
  wire stg4_b08;
  wire stg4_b09;
  wire stg4_b10;
  wire stg4_b11;
  wire stg4_b12;
  wire stg4_b13;
  wire stg4_b14;
  wire stg4_b15;
  wire stg4_b16;
  wire stg4_b17;
  wire stg4_b18;
  wire stg4_b19;
  wire stg4_b20;
  wire stg4_b21;
  wire stg4_b22;
  wire stg4_b23;
  wire stg4_b24;
  wire stg4_b25;
  wire stg4_b26;
  wire stg4_b27;
  wire stg4_b28;
  wire stg4_b29;
  wire stg4_b30;
  wire stg4_b31;
  wire stg5_b00;
  wire stg5_b01;
  wire stg5_b02;
  wire stg5_b03;
  wire stg5_b04;
  wire stg5_b05;
  wire stg5_b06;
  wire stg5_b07;
  wire stg5_b08;
  wire stg5_b09;
  wire stg5_b10;
  wire stg5_b11;
  wire stg5_b12;
  wire stg5_b13;
  wire stg5_b14;
  wire stg5_b15;
  wire stg5_b16;
  wire stg5_b17;
  wire stg5_b18;
  wire stg5_b19;
  wire stg5_b20;
  wire stg5_b21;
  wire stg5_b22;
  wire stg5_b23;
  wire stg5_b24;
  wire stg5_b25;
  wire stg5_b26;
  wire stg5_b27;
  wire stg5_b28;
  wire stg5_b29;
  wire stg5_b30;
  wire stg5_b31;
  wire LSL;
  wire stg0_b00;
  wire stg0_b01;
  wire stg0_b02;
  wire stg0_b03;
  wire stg0_b04;
  wire stg0_b05;
  wire stg0_b06;
  wire stg0_b07;
  wire stg0_b08;
  wire stg0_b09;
  wire stg0_b10;
  wire stg0_b11;
  wire stg0_b12;
  wire stg0_b13;
  wire stg0_b14;
  wire stg0_b15;
  wire stg0_b16;
  wire stg0_b17;
  wire stg0_b18;
  wire stg0_b19;
  wire stg0_b20;
  wire stg0_b21;
  wire stg0_b22;
  wire stg0_b23;
  wire stg0_b24;
  wire stg0_b25;
  wire stg0_b26;
  wire stg0_b27;
  wire stg0_b28;
  wire stg0_b29;
  wire stg0_b30;
  wire stg0_b31;
  wire stg1_b00;
  wire stg1_b01;
  wire stg1_b02;
  wire stg1_b03;
  wire stg1_b04;
  wire stg1_b05;
  wire stg1_b06;
  wire stg1_b07;
  wire stg1_b08;
  wire stg1_b09;
  wire stg1_b10;
  wire stg1_b11;
  wire stg1_b12;
  wire stg1_b13;
  wire stg1_b14;
  wire stg1_b15;
  wire stg1_b16;
  wire stg1_b17;
  wire stg1_b18;
  wire stg1_b19;
  wire stg1_b20;
  wire stg1_b21;
  wire stg1_b22;
  wire stg1_b23;
  wire stg1_b24;
  wire stg1_b25;
  wire stg1_b26;
  wire stg1_b27;
  wire stg1_b28;
  wire stg1_b29;
  wire stg1_b30;
  wire stg1_b31;
  wire MODE0;
  wire MODE1;
  assign in_b00 = A[0];
  assign in_b01 = A[1];
  assign in_b02 = A[2];
  assign in_b03 = A[3];
  assign in_b04 = A[4];
  assign in_b05 = A[5];
  assign in_b06 = A[6];
  assign in_b07 = A[7];
  assign in_b08 = A[8];
  assign in_b09 = A[9];
  assign in_b10 = A[10];
  assign in_b11 = A[11];
  assign in_b12 = A[12];
  assign in_b13 = A[13];
  assign in_b14 = A[14];
  assign in_b15 = A[15];
  assign in_b16 = A[16];
  assign in_b17 = A[17];
  assign in_b18 = A[18];
  assign in_b19 = A[19];
  assign in_b20 = A[20];
  assign in_b21 = A[21];
  assign in_b22 = A[22];
  assign in_b23 = A[23];
  assign in_b24 = A[24];
  assign in_b25 = A[25];
  assign in_b26 = A[26];
  assign in_b27 = A[27];
  assign in_b28 = A[28];
  assign in_b29 = A[29];
  assign in_b30 = A[30];
  assign in_b31 = A[31];
  assign shamt0 = B[0];
  assign shamt1 = B[1];
  assign shamt2 = B[2];
  assign shamt3 = B[3];
  assign shamt4 = B[4];
  assign MODE0 = mode[0];
  assign MODE1 = mode[1];
  assign fill = ((MODE1 & ~ MODE0) & in_b31);
  assign LSL = (MODE0 & ~ MODE1);
  \74157  \74157_i0 (
    .S( LSL ),
    .A1( in_b00 ),
    .B1( in_b31 ),
    .A2( in_b01 ),
    .B2( in_b30 ),
    .GND( 1'b0 ),
    .B3( in_b29 ),
    .A3( in_b02 ),
    .B4( in_b28 ),
    .A4( in_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b00 ),
    .Y2( stg0_b01 ),
    .Y3( stg0_b02 ),
    .Y4( stg0_b03 )
  );
  \74157  \74157_i1 (
    .S( LSL ),
    .A1( in_b04 ),
    .B1( in_b27 ),
    .A2( in_b05 ),
    .B2( in_b26 ),
    .GND( 1'b0 ),
    .B3( in_b25 ),
    .A3( in_b06 ),
    .B4( in_b24 ),
    .A4( in_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b04 ),
    .Y2( stg0_b05 ),
    .Y3( stg0_b06 ),
    .Y4( stg0_b07 )
  );
  \74157  \74157_i2 (
    .S( LSL ),
    .A1( in_b08 ),
    .B1( in_b23 ),
    .A2( in_b09 ),
    .B2( in_b22 ),
    .GND( 1'b0 ),
    .B3( in_b21 ),
    .A3( in_b10 ),
    .B4( in_b20 ),
    .A4( in_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b08 ),
    .Y2( stg0_b09 ),
    .Y3( stg0_b10 ),
    .Y4( stg0_b11 )
  );
  \74157  \74157_i3 (
    .S( LSL ),
    .A1( in_b12 ),
    .B1( in_b19 ),
    .A2( in_b13 ),
    .B2( in_b18 ),
    .GND( 1'b0 ),
    .B3( in_b17 ),
    .A3( in_b14 ),
    .B4( in_b16 ),
    .A4( in_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b12 ),
    .Y2( stg0_b13 ),
    .Y3( stg0_b14 ),
    .Y4( stg0_b15 )
  );
  \74157  \74157_i4 (
    .S( LSL ),
    .A1( in_b16 ),
    .B1( in_b15 ),
    .A2( in_b17 ),
    .B2( in_b14 ),
    .GND( 1'b0 ),
    .B3( in_b13 ),
    .A3( in_b18 ),
    .B4( in_b12 ),
    .A4( in_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b16 ),
    .Y2( stg0_b17 ),
    .Y3( stg0_b18 ),
    .Y4( stg0_b19 )
  );
  \74157  \74157_i5 (
    .S( LSL ),
    .A1( in_b20 ),
    .B1( in_b11 ),
    .A2( in_b21 ),
    .B2( in_b10 ),
    .GND( 1'b0 ),
    .B3( in_b09 ),
    .A3( in_b22 ),
    .B4( in_b08 ),
    .A4( in_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b20 ),
    .Y2( stg0_b21 ),
    .Y3( stg0_b22 ),
    .Y4( stg0_b23 )
  );
  \74157  \74157_i6 (
    .S( LSL ),
    .A1( in_b24 ),
    .B1( in_b07 ),
    .A2( in_b25 ),
    .B2( in_b06 ),
    .GND( 1'b0 ),
    .B3( in_b05 ),
    .A3( in_b26 ),
    .B4( in_b04 ),
    .A4( in_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b24 ),
    .Y2( stg0_b25 ),
    .Y3( stg0_b26 ),
    .Y4( stg0_b27 )
  );
  \74157  \74157_i7 (
    .S( LSL ),
    .A1( in_b28 ),
    .B1( in_b03 ),
    .A2( in_b29 ),
    .B2( in_b02 ),
    .GND( 1'b0 ),
    .B3( in_b01 ),
    .A3( in_b30 ),
    .B4( in_b00 ),
    .A4( in_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg0_b28 ),
    .Y2( stg0_b29 ),
    .Y3( stg0_b30 ),
    .Y4( stg0_b31 )
  );
  \74157  \74157_i8 (
    .S( shamt0 ),
    .A1( stg0_b00 ),
    .B1( stg0_b01 ),
    .A2( stg0_b01 ),
    .B2( stg0_b02 ),
    .GND( 1'b0 ),
    .B3( stg0_b03 ),
    .A3( stg0_b02 ),
    .B4( stg0_b04 ),
    .A4( stg0_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b00 ),
    .Y2( stg1_b01 ),
    .Y3( stg1_b02 ),
    .Y4( stg1_b03 )
  );
  \74157  \74157_i9 (
    .S( shamt0 ),
    .A1( stg0_b04 ),
    .B1( stg0_b05 ),
    .A2( stg0_b05 ),
    .B2( stg0_b06 ),
    .GND( 1'b0 ),
    .B3( stg0_b07 ),
    .A3( stg0_b06 ),
    .B4( stg0_b08 ),
    .A4( stg0_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b04 ),
    .Y2( stg1_b05 ),
    .Y3( stg1_b06 ),
    .Y4( stg1_b07 )
  );
  \74157  \74157_i10 (
    .S( shamt0 ),
    .A1( stg0_b08 ),
    .B1( stg0_b09 ),
    .A2( stg0_b09 ),
    .B2( stg0_b10 ),
    .GND( 1'b0 ),
    .B3( stg0_b11 ),
    .A3( stg0_b10 ),
    .B4( stg0_b12 ),
    .A4( stg0_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b08 ),
    .Y2( stg1_b09 ),
    .Y3( stg1_b10 ),
    .Y4( stg1_b11 )
  );
  \74157  \74157_i11 (
    .S( shamt0 ),
    .A1( stg0_b12 ),
    .B1( stg0_b13 ),
    .A2( stg0_b13 ),
    .B2( stg0_b14 ),
    .GND( 1'b0 ),
    .B3( stg0_b15 ),
    .A3( stg0_b14 ),
    .B4( stg0_b16 ),
    .A4( stg0_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b12 ),
    .Y2( stg1_b13 ),
    .Y3( stg1_b14 ),
    .Y4( stg1_b15 )
  );
  \74157  \74157_i12 (
    .S( shamt0 ),
    .A1( stg0_b16 ),
    .B1( stg0_b17 ),
    .A2( stg0_b17 ),
    .B2( stg0_b18 ),
    .GND( 1'b0 ),
    .B3( stg0_b19 ),
    .A3( stg0_b18 ),
    .B4( stg0_b20 ),
    .A4( stg0_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b16 ),
    .Y2( stg1_b17 ),
    .Y3( stg1_b18 ),
    .Y4( stg1_b19 )
  );
  \74157  \74157_i13 (
    .S( shamt0 ),
    .A1( stg0_b20 ),
    .B1( stg0_b21 ),
    .A2( stg0_b21 ),
    .B2( stg0_b22 ),
    .GND( 1'b0 ),
    .B3( stg0_b23 ),
    .A3( stg0_b22 ),
    .B4( stg0_b24 ),
    .A4( stg0_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b20 ),
    .Y2( stg1_b21 ),
    .Y3( stg1_b22 ),
    .Y4( stg1_b23 )
  );
  \74157  \74157_i14 (
    .S( shamt0 ),
    .A1( stg0_b24 ),
    .B1( stg0_b25 ),
    .A2( stg0_b25 ),
    .B2( stg0_b26 ),
    .GND( 1'b0 ),
    .B3( stg0_b27 ),
    .A3( stg0_b26 ),
    .B4( stg0_b28 ),
    .A4( stg0_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b24 ),
    .Y2( stg1_b25 ),
    .Y3( stg1_b26 ),
    .Y4( stg1_b27 )
  );
  \74157  \74157_i15 (
    .S( shamt0 ),
    .A1( stg0_b28 ),
    .B1( stg0_b29 ),
    .A2( stg0_b29 ),
    .B2( stg0_b30 ),
    .GND( 1'b0 ),
    .B3( stg0_b31 ),
    .A3( stg0_b30 ),
    .B4( fill ),
    .A4( stg0_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg1_b28 ),
    .Y2( stg1_b29 ),
    .Y3( stg1_b30 ),
    .Y4( stg1_b31 )
  );
  \74157  \74157_i16 (
    .S( shamt1 ),
    .A1( stg1_b00 ),
    .B1( stg1_b02 ),
    .A2( stg1_b01 ),
    .B2( stg1_b03 ),
    .GND( 1'b0 ),
    .B3( stg1_b04 ),
    .A3( stg1_b02 ),
    .B4( stg1_b05 ),
    .A4( stg1_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b00 ),
    .Y2( stg2_b01 ),
    .Y3( stg2_b02 ),
    .Y4( stg2_b03 )
  );
  \74157  \74157_i17 (
    .S( shamt1 ),
    .A1( stg1_b04 ),
    .B1( stg1_b06 ),
    .A2( stg1_b05 ),
    .B2( stg1_b07 ),
    .GND( 1'b0 ),
    .B3( stg1_b08 ),
    .A3( stg1_b06 ),
    .B4( stg1_b09 ),
    .A4( stg1_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b04 ),
    .Y2( stg2_b05 ),
    .Y3( stg2_b06 ),
    .Y4( stg2_b07 )
  );
  \74157  \74157_i18 (
    .S( shamt1 ),
    .A1( stg1_b08 ),
    .B1( stg1_b10 ),
    .A2( stg1_b09 ),
    .B2( stg1_b11 ),
    .GND( 1'b0 ),
    .B3( stg1_b12 ),
    .A3( stg1_b10 ),
    .B4( stg1_b13 ),
    .A4( stg1_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b08 ),
    .Y2( stg2_b09 ),
    .Y3( stg2_b10 ),
    .Y4( stg2_b11 )
  );
  \74157  \74157_i19 (
    .S( shamt1 ),
    .A1( stg1_b12 ),
    .B1( stg1_b14 ),
    .A2( stg1_b13 ),
    .B2( stg1_b15 ),
    .GND( 1'b0 ),
    .B3( stg1_b16 ),
    .A3( stg1_b14 ),
    .B4( stg1_b17 ),
    .A4( stg1_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b12 ),
    .Y2( stg2_b13 ),
    .Y3( stg2_b14 ),
    .Y4( stg2_b15 )
  );
  \74157  \74157_i20 (
    .S( shamt1 ),
    .A1( stg1_b16 ),
    .B1( stg1_b18 ),
    .A2( stg1_b17 ),
    .B2( stg1_b19 ),
    .GND( 1'b0 ),
    .B3( stg1_b20 ),
    .A3( stg1_b18 ),
    .B4( stg1_b21 ),
    .A4( stg1_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b16 ),
    .Y2( stg2_b17 ),
    .Y3( stg2_b18 ),
    .Y4( stg2_b19 )
  );
  \74157  \74157_i21 (
    .S( shamt1 ),
    .A1( stg1_b20 ),
    .B1( stg1_b22 ),
    .A2( stg1_b21 ),
    .B2( stg1_b23 ),
    .GND( 1'b0 ),
    .B3( stg1_b24 ),
    .A3( stg1_b22 ),
    .B4( stg1_b25 ),
    .A4( stg1_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b20 ),
    .Y2( stg2_b21 ),
    .Y3( stg2_b22 ),
    .Y4( stg2_b23 )
  );
  \74157  \74157_i22 (
    .S( shamt1 ),
    .A1( stg1_b24 ),
    .B1( stg1_b26 ),
    .A2( stg1_b25 ),
    .B2( stg1_b27 ),
    .GND( 1'b0 ),
    .B3( stg1_b28 ),
    .A3( stg1_b26 ),
    .B4( stg1_b29 ),
    .A4( stg1_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b24 ),
    .Y2( stg2_b25 ),
    .Y3( stg2_b26 ),
    .Y4( stg2_b27 )
  );
  \74157  \74157_i23 (
    .S( shamt1 ),
    .A1( stg1_b28 ),
    .B1( stg1_b30 ),
    .A2( stg1_b29 ),
    .B2( stg1_b31 ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg1_b30 ),
    .B4( fill ),
    .A4( stg1_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg2_b28 ),
    .Y2( stg2_b29 ),
    .Y3( stg2_b30 ),
    .Y4( stg2_b31 )
  );
  \74157  \74157_i24 (
    .S( shamt2 ),
    .A1( stg2_b00 ),
    .B1( stg2_b04 ),
    .A2( stg2_b01 ),
    .B2( stg2_b05 ),
    .GND( 1'b0 ),
    .B3( stg2_b06 ),
    .A3( stg2_b02 ),
    .B4( stg2_b07 ),
    .A4( stg2_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b00 ),
    .Y2( stg3_b01 ),
    .Y3( stg3_b02 ),
    .Y4( stg3_b03 )
  );
  \74157  \74157_i25 (
    .S( shamt2 ),
    .A1( stg2_b04 ),
    .B1( stg2_b08 ),
    .A2( stg2_b05 ),
    .B2( stg2_b09 ),
    .GND( 1'b0 ),
    .B3( stg2_b10 ),
    .A3( stg2_b06 ),
    .B4( stg2_b11 ),
    .A4( stg2_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b04 ),
    .Y2( stg3_b05 ),
    .Y3( stg3_b06 ),
    .Y4( stg3_b07 )
  );
  \74157  \74157_i26 (
    .S( shamt2 ),
    .A1( stg2_b08 ),
    .B1( stg2_b12 ),
    .A2( stg2_b09 ),
    .B2( stg2_b13 ),
    .GND( 1'b0 ),
    .B3( stg2_b14 ),
    .A3( stg2_b10 ),
    .B4( stg2_b15 ),
    .A4( stg2_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b08 ),
    .Y2( stg3_b09 ),
    .Y3( stg3_b10 ),
    .Y4( stg3_b11 )
  );
  \74157  \74157_i27 (
    .S( shamt2 ),
    .A1( stg2_b12 ),
    .B1( stg2_b16 ),
    .A2( stg2_b13 ),
    .B2( stg2_b17 ),
    .GND( 1'b0 ),
    .B3( stg2_b18 ),
    .A3( stg2_b14 ),
    .B4( stg2_b19 ),
    .A4( stg2_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b12 ),
    .Y2( stg3_b13 ),
    .Y3( stg3_b14 ),
    .Y4( stg3_b15 )
  );
  \74157  \74157_i28 (
    .S( shamt2 ),
    .A1( stg2_b16 ),
    .B1( stg2_b20 ),
    .A2( stg2_b17 ),
    .B2( stg2_b21 ),
    .GND( 1'b0 ),
    .B3( stg2_b22 ),
    .A3( stg2_b18 ),
    .B4( stg2_b23 ),
    .A4( stg2_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b16 ),
    .Y2( stg3_b17 ),
    .Y3( stg3_b18 ),
    .Y4( stg3_b19 )
  );
  \74157  \74157_i29 (
    .S( shamt2 ),
    .A1( stg2_b20 ),
    .B1( stg2_b24 ),
    .A2( stg2_b21 ),
    .B2( stg2_b25 ),
    .GND( 1'b0 ),
    .B3( stg2_b26 ),
    .A3( stg2_b22 ),
    .B4( stg2_b27 ),
    .A4( stg2_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b20 ),
    .Y2( stg3_b21 ),
    .Y3( stg3_b22 ),
    .Y4( stg3_b23 )
  );
  \74157  \74157_i30 (
    .S( shamt2 ),
    .A1( stg2_b24 ),
    .B1( stg2_b28 ),
    .A2( stg2_b25 ),
    .B2( stg2_b29 ),
    .GND( 1'b0 ),
    .B3( stg2_b30 ),
    .A3( stg2_b26 ),
    .B4( stg2_b31 ),
    .A4( stg2_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b24 ),
    .Y2( stg3_b25 ),
    .Y3( stg3_b26 ),
    .Y4( stg3_b27 )
  );
  \74157  \74157_i31 (
    .S( shamt2 ),
    .A1( stg2_b28 ),
    .B1( fill ),
    .A2( stg2_b29 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg2_b30 ),
    .B4( fill ),
    .A4( stg2_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg3_b28 ),
    .Y2( stg3_b29 ),
    .Y3( stg3_b30 ),
    .Y4( stg3_b31 )
  );
  \74157  \74157_i32 (
    .S( shamt3 ),
    .A1( stg3_b00 ),
    .B1( stg3_b08 ),
    .A2( stg3_b01 ),
    .B2( stg3_b09 ),
    .GND( 1'b0 ),
    .B3( stg3_b10 ),
    .A3( stg3_b02 ),
    .B4( stg3_b11 ),
    .A4( stg3_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b00 ),
    .Y2( stg4_b01 ),
    .Y3( stg4_b02 ),
    .Y4( stg4_b03 )
  );
  \74157  \74157_i33 (
    .S( shamt3 ),
    .A1( stg3_b04 ),
    .B1( stg3_b12 ),
    .A2( stg3_b05 ),
    .B2( stg3_b13 ),
    .GND( 1'b0 ),
    .B3( stg3_b14 ),
    .A3( stg3_b06 ),
    .B4( stg3_b15 ),
    .A4( stg3_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b04 ),
    .Y2( stg4_b05 ),
    .Y3( stg4_b06 ),
    .Y4( stg4_b07 )
  );
  \74157  \74157_i34 (
    .S( shamt3 ),
    .A1( stg3_b08 ),
    .B1( stg3_b16 ),
    .A2( stg3_b09 ),
    .B2( stg3_b17 ),
    .GND( 1'b0 ),
    .B3( stg3_b18 ),
    .A3( stg3_b10 ),
    .B4( stg3_b19 ),
    .A4( stg3_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b08 ),
    .Y2( stg4_b09 ),
    .Y3( stg4_b10 ),
    .Y4( stg4_b11 )
  );
  \74157  \74157_i35 (
    .S( shamt3 ),
    .A1( stg3_b12 ),
    .B1( stg3_b20 ),
    .A2( stg3_b13 ),
    .B2( stg3_b21 ),
    .GND( 1'b0 ),
    .B3( stg3_b22 ),
    .A3( stg3_b14 ),
    .B4( stg3_b23 ),
    .A4( stg3_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b12 ),
    .Y2( stg4_b13 ),
    .Y3( stg4_b14 ),
    .Y4( stg4_b15 )
  );
  \74157  \74157_i36 (
    .S( shamt3 ),
    .A1( stg3_b16 ),
    .B1( stg3_b24 ),
    .A2( stg3_b17 ),
    .B2( stg3_b25 ),
    .GND( 1'b0 ),
    .B3( stg3_b26 ),
    .A3( stg3_b18 ),
    .B4( stg3_b27 ),
    .A4( stg3_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b16 ),
    .Y2( stg4_b17 ),
    .Y3( stg4_b18 ),
    .Y4( stg4_b19 )
  );
  \74157  \74157_i37 (
    .S( shamt3 ),
    .A1( stg3_b20 ),
    .B1( stg3_b28 ),
    .A2( stg3_b21 ),
    .B2( stg3_b29 ),
    .GND( 1'b0 ),
    .B3( stg3_b30 ),
    .A3( stg3_b22 ),
    .B4( stg3_b31 ),
    .A4( stg3_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b20 ),
    .Y2( stg4_b21 ),
    .Y3( stg4_b22 ),
    .Y4( stg4_b23 )
  );
  \74157  \74157_i38 (
    .S( shamt3 ),
    .A1( stg3_b24 ),
    .B1( fill ),
    .A2( stg3_b25 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg3_b26 ),
    .B4( fill ),
    .A4( stg3_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b24 ),
    .Y2( stg4_b25 ),
    .Y3( stg4_b26 ),
    .Y4( stg4_b27 )
  );
  \74157  \74157_i39 (
    .S( shamt3 ),
    .A1( stg3_b28 ),
    .B1( fill ),
    .A2( stg3_b29 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg3_b30 ),
    .B4( fill ),
    .A4( stg3_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg4_b28 ),
    .Y2( stg4_b29 ),
    .Y3( stg4_b30 ),
    .Y4( stg4_b31 )
  );
  \74157  \74157_i40 (
    .S( shamt4 ),
    .A1( stg4_b00 ),
    .B1( stg4_b16 ),
    .A2( stg4_b01 ),
    .B2( stg4_b17 ),
    .GND( 1'b0 ),
    .B3( stg4_b18 ),
    .A3( stg4_b02 ),
    .B4( stg4_b19 ),
    .A4( stg4_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b00 ),
    .Y2( stg5_b01 ),
    .Y3( stg5_b02 ),
    .Y4( stg5_b03 )
  );
  \74157  \74157_i41 (
    .S( shamt4 ),
    .A1( stg4_b04 ),
    .B1( stg4_b20 ),
    .A2( stg4_b05 ),
    .B2( stg4_b21 ),
    .GND( 1'b0 ),
    .B3( stg4_b22 ),
    .A3( stg4_b06 ),
    .B4( stg4_b23 ),
    .A4( stg4_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b04 ),
    .Y2( stg5_b05 ),
    .Y3( stg5_b06 ),
    .Y4( stg5_b07 )
  );
  \74157  \74157_i42 (
    .S( shamt4 ),
    .A1( stg4_b08 ),
    .B1( stg4_b24 ),
    .A2( stg4_b09 ),
    .B2( stg4_b25 ),
    .GND( 1'b0 ),
    .B3( stg4_b26 ),
    .A3( stg4_b10 ),
    .B4( stg4_b27 ),
    .A4( stg4_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b08 ),
    .Y2( stg5_b09 ),
    .Y3( stg5_b10 ),
    .Y4( stg5_b11 )
  );
  \74157  \74157_i43 (
    .S( shamt4 ),
    .A1( stg4_b12 ),
    .B1( stg4_b28 ),
    .A2( stg4_b13 ),
    .B2( stg4_b29 ),
    .GND( 1'b0 ),
    .B3( stg4_b30 ),
    .A3( stg4_b14 ),
    .B4( stg4_b31 ),
    .A4( stg4_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b12 ),
    .Y2( stg5_b13 ),
    .Y3( stg5_b14 ),
    .Y4( stg5_b15 )
  );
  \74157  \74157_i44 (
    .S( shamt4 ),
    .A1( stg4_b16 ),
    .B1( fill ),
    .A2( stg4_b17 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b18 ),
    .B4( fill ),
    .A4( stg4_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b16 ),
    .Y2( stg5_b17 ),
    .Y3( stg5_b18 ),
    .Y4( stg5_b19 )
  );
  \74157  \74157_i45 (
    .S( shamt4 ),
    .A1( stg4_b20 ),
    .B1( fill ),
    .A2( stg4_b21 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b22 ),
    .B4( fill ),
    .A4( stg4_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b20 ),
    .Y2( stg5_b21 ),
    .Y3( stg5_b22 ),
    .Y4( stg5_b23 )
  );
  \74157  \74157_i46 (
    .S( shamt4 ),
    .A1( stg4_b24 ),
    .B1( fill ),
    .A2( stg4_b25 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b26 ),
    .B4( fill ),
    .A4( stg4_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b24 ),
    .Y2( stg5_b25 ),
    .Y3( stg5_b26 ),
    .Y4( stg5_b27 )
  );
  \74157  \74157_i47 (
    .S( shamt4 ),
    .A1( stg4_b28 ),
    .B1( fill ),
    .A2( stg4_b29 ),
    .B2( fill ),
    .GND( 1'b0 ),
    .B3( fill ),
    .A3( stg4_b30 ),
    .B4( fill ),
    .A4( stg4_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( stg5_b28 ),
    .Y2( stg5_b29 ),
    .Y3( stg5_b30 ),
    .Y4( stg5_b31 )
  );
  \74157  \74157_i48 (
    .S( LSL ),
    .A1( stg5_b00 ),
    .B1( stg5_b31 ),
    .A2( stg5_b01 ),
    .B2( stg5_b30 ),
    .GND( 1'b0 ),
    .B3( stg5_b29 ),
    .A3( stg5_b02 ),
    .B4( stg5_b28 ),
    .A4( stg5_b03 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b00 ),
    .Y2( out_b01 ),
    .Y3( out_b02 ),
    .Y4( out_b03 )
  );
  \74157  \74157_i49 (
    .S( LSL ),
    .A1( stg5_b04 ),
    .B1( stg5_b27 ),
    .A2( stg5_b05 ),
    .B2( stg5_b26 ),
    .GND( 1'b0 ),
    .B3( stg5_b25 ),
    .A3( stg5_b06 ),
    .B4( stg5_b24 ),
    .A4( stg5_b07 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b04 ),
    .Y2( out_b05 ),
    .Y3( out_b06 ),
    .Y4( out_b07 )
  );
  \74157  \74157_i50 (
    .S( LSL ),
    .A1( stg5_b08 ),
    .B1( stg5_b23 ),
    .A2( stg5_b09 ),
    .B2( stg5_b22 ),
    .GND( 1'b0 ),
    .B3( stg5_b21 ),
    .A3( stg5_b10 ),
    .B4( stg5_b20 ),
    .A4( stg5_b11 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b08 ),
    .Y2( out_b09 ),
    .Y3( out_b10 ),
    .Y4( out_b11 )
  );
  \74157  \74157_i51 (
    .S( LSL ),
    .A1( stg5_b12 ),
    .B1( stg5_b19 ),
    .A2( stg5_b13 ),
    .B2( stg5_b18 ),
    .GND( 1'b0 ),
    .B3( stg5_b17 ),
    .A3( stg5_b14 ),
    .B4( stg5_b16 ),
    .A4( stg5_b15 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b12 ),
    .Y2( out_b13 ),
    .Y3( out_b14 ),
    .Y4( out_b15 )
  );
  \74157  \74157_i52 (
    .S( LSL ),
    .A1( stg5_b16 ),
    .B1( stg5_b15 ),
    .A2( stg5_b17 ),
    .B2( stg5_b14 ),
    .GND( 1'b0 ),
    .B3( stg5_b13 ),
    .A3( stg5_b18 ),
    .B4( stg5_b12 ),
    .A4( stg5_b19 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b16 ),
    .Y2( out_b17 ),
    .Y3( out_b18 ),
    .Y4( out_b19 )
  );
  \74157  \74157_i53 (
    .S( LSL ),
    .A1( stg5_b20 ),
    .B1( stg5_b11 ),
    .A2( stg5_b21 ),
    .B2( stg5_b10 ),
    .GND( 1'b0 ),
    .B3( stg5_b09 ),
    .A3( stg5_b22 ),
    .B4( stg5_b08 ),
    .A4( stg5_b23 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b20 ),
    .Y2( out_b21 ),
    .Y3( out_b22 ),
    .Y4( out_b23 )
  );
  \74157  \74157_i54 (
    .S( LSL ),
    .A1( stg5_b24 ),
    .B1( stg5_b07 ),
    .A2( stg5_b25 ),
    .B2( stg5_b06 ),
    .GND( 1'b0 ),
    .B3( stg5_b05 ),
    .A3( stg5_b26 ),
    .B4( stg5_b04 ),
    .A4( stg5_b27 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b24 ),
    .Y2( out_b25 ),
    .Y3( out_b26 ),
    .Y4( out_b27 )
  );
  \74157  \74157_i55 (
    .S( LSL ),
    .A1( stg5_b28 ),
    .B1( stg5_b03 ),
    .A2( stg5_b29 ),
    .B2( stg5_b02 ),
    .GND( 1'b0 ),
    .B3( stg5_b01 ),
    .A3( stg5_b30 ),
    .B4( stg5_b00 ),
    .A4( stg5_b31 ),
    .G( 1'b0 ),
    .VCC( 1'b1 ),
    .Y1( out_b28 ),
    .Y2( out_b29 ),
    .Y3( out_b30 ),
    .Y4( out_b31 )
  );
  assign Out[0] = out_b00;
  assign Out[1] = out_b01;
  assign Out[2] = out_b02;
  assign Out[3] = out_b03;
  assign Out[4] = out_b04;
  assign Out[5] = out_b05;
  assign Out[6] = out_b06;
  assign Out[7] = out_b07;
  assign Out[8] = out_b08;
  assign Out[9] = out_b09;
  assign Out[10] = out_b10;
  assign Out[11] = out_b11;
  assign Out[12] = out_b12;
  assign Out[13] = out_b13;
  assign Out[14] = out_b14;
  assign Out[15] = out_b15;
  assign Out[16] = out_b16;
  assign Out[17] = out_b17;
  assign Out[18] = out_b18;
  assign Out[19] = out_b19;
  assign Out[20] = out_b20;
  assign Out[21] = out_b21;
  assign Out[22] = out_b22;
  assign Out[23] = out_b23;
  assign Out[24] = out_b24;
  assign Out[25] = out_b25;
  assign Out[26] = out_b26;
  assign Out[27] = out_b27;
  assign Out[28] = out_b28;
  assign Out[29] = out_b29;
  assign Out[30] = out_b30;
  assign Out[31] = out_b31;
endmodule
