/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module wb_mux (
  input [1:0] wb_sel,
  input [31:0] alu_out,
  input [31:0] shift_out,
  input [23:0] pc_save,
  input [31:0] mem_din,
  output [31:0] reg_w_data
);
  wire [31:0] pc_save_32;
  assign pc_save_32[23:0] = pc_save;
  assign pc_save_32[24] = 1'b0;
  assign pc_save_32[25] = 1'b0;
  assign pc_save_32[26] = 1'b0;
  assign pc_save_32[27] = 1'b0;
  assign pc_save_32[28] = 1'b0;
  assign pc_save_32[29] = 1'b0;
  assign pc_save_32[30] = 1'b0;
  assign pc_save_32[31] = 1'b0;
  Mux_4x1_NBits #(
    .Bits(32)
  )
  Mux_4x1_NBits_i0 (
    .sel( wb_sel ),
    .in_0( alu_out ),
    .in_1( shift_out ),
    .in_2( pc_save_32 ),
    .in_3( mem_din ),
    .out( reg_w_data )
  );
endmodule
