/*
 * Copyright (c) 2025-2026 Tyrone Marhguy
 * SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
 *
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_8x1
(
    input [2:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    output reg out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module alu_1b_final (
  input [7:0] OPCODE,
  input A,
  input B,
  input C,
  output MUX_OUT
);
  wire [2:0] s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  assign s0[0] = A;
  assign s0[1] = B;
  assign s0[2] = C;
  assign s1 = OPCODE[0];
  assign s2 = OPCODE[1];
  assign s3 = OPCODE[2];
  assign s4 = OPCODE[3];
  assign s5 = OPCODE[4];
  assign s6 = OPCODE[5];
  assign s7 = OPCODE[6];
  assign s8 = OPCODE[7];
  Mux_8x1 Mux_8x1_i0 (
    .sel( s0 ),
    .in_0( s1 ),
    .in_1( s2 ),
    .in_2( s3 ),
    .in_3( s4 ),
    .in_4( s5 ),
    .in_5( s6 ),
    .in_6( s7 ),
    .in_7( s8 ),
    .out( MUX_OUT )
  );
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



// 4-bit binary full adder, alternative pinning
module \74283  (
  input C0,
  input B1,
  input B2,
  input B3,
  input B4,
  input A1,
  input A2,
  input A3,
  input A4,
  input VCC,
  input GND,
  output S1,
  output S2,
  output S3,
  output S4,
  output C4
);
  wire [3:0] s0;
  wire [3:0] s5;
  wire [3:0] s6;
  assign s5[0] = B1;
  assign s5[1] = B2;
  assign s5[2] = B3;
  assign s5[3] = B4;
  assign s0[0] = A1;
  assign s0[1] = A2;
  assign s0[2] = A3;
  assign s0[3] = A4;
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i0 (
    .a( s0 ),
    .b( s5 ),
    .c_i( C0 ),
    .s( s6 ),
    .c_o( C4 )
  );
  assign S1 = s6[0];
  assign S2 = s6[1];
  assign S3 = s6[2];
  assign S4 = s6[3];
endmodule

module alu_4b_final (
  input [3:0] A,
  input [3:0] B,
  input [7:0] lutA,
  input [3:0] C,
  input cin,
  input [7:0] lutB,
  output [3:0] Out,
  output cout,
  output aeff3,
  output beff3
);
  wire out1;
  wire y1;
  wire x1;
  wire out0;
  wire x0;
  wire y0;
  wire out3;
  wire beff3_temp;
  wire aeff3_temp;
  wire out2;
  wire x2;
  wire y2;
  wire a0;
  wire a1;
  wire a2;
  wire a3;
  wire b0;
  wire b1;
  wire b2;
  wire b3;
  wire c0;
  wire c1;
  wire c2;
  wire c3;
  assign a0 = A[0];
  assign a1 = A[1];
  assign a2 = A[2];
  assign a3 = A[3];
  assign b0 = B[0];
  assign b1 = B[1];
  assign b2 = B[2];
  assign b3 = B[3];
  assign c0 = C[0];
  assign c1 = C[1];
  assign c2 = C[2];
  assign c3 = C[3];
  alu_1b_final alu_1b_final_i0 (
    .OPCODE( lutB ),
    .A( a0 ),
    .B( b0 ),
    .C( c0 ),
    .MUX_OUT( x0 )
  );
  alu_1b_final alu_1b_final_i1 (
    .OPCODE( lutB ),
    .A( a2 ),
    .B( b2 ),
    .C( c2 ),
    .MUX_OUT( x2 )
  );
  alu_1b_final alu_1b_final_i2 (
    .OPCODE( lutB ),
    .A( a1 ),
    .B( b1 ),
    .C( c1 ),
    .MUX_OUT( x1 )
  );
  alu_1b_final alu_1b_final_i3 (
    .OPCODE( lutB ),
    .A( a3 ),
    .B( b3 ),
    .C( c3 ),
    .MUX_OUT( aeff3_temp )
  );
  alu_1b_final alu_1b_final_i4 (
    .OPCODE( lutA ),
    .A( a0 ),
    .B( b0 ),
    .C( c0 ),
    .MUX_OUT( y0 )
  );
  alu_1b_final alu_1b_final_i5 (
    .OPCODE( lutA ),
    .A( a2 ),
    .B( b2 ),
    .C( c2 ),
    .MUX_OUT( y2 )
  );
  alu_1b_final alu_1b_final_i6 (
    .OPCODE( lutA ),
    .A( a1 ),
    .B( b1 ),
    .C( c1 ),
    .MUX_OUT( y1 )
  );
  alu_1b_final alu_1b_final_i7 (
    .OPCODE( lutA ),
    .A( a3 ),
    .B( b3 ),
    .C( c3 ),
    .MUX_OUT( beff3_temp )
  );
  \74283  \74283_i8 (
    .B2( y1 ),
    .A2( x1 ),
    .A1( x0 ),
    .B1( y0 ),
    .C0( cin ),
    .GND( 1'b0 ),
    .B4( beff3_temp ),
    .A4( aeff3_temp ),
    .A3( x2 ),
    .B3( y2 ),
    .VCC( 1'b1 ),
    .S2( out1 ),
    .S1( out0 ),
    .C4( cout ),
    .S4( out3 ),
    .S3( out2 )
  );
  assign Out[0] = out0;
  assign Out[1] = out1;
  assign Out[2] = out2;
  assign Out[3] = out3;
  assign aeff3 = aeff3_temp;
  assign beff3 = beff3_temp;
endmodule

// quad 2-input NAND gate
module \7400  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = ~ (\1A  & \1B );
  assign \2Y  = ~ (\2A  & \2B );
  assign \3Y  = ~ (\3A  & \3B );
  assign \4Y  = ~ (\4A  & \4B );
endmodule

// 3-line to 8-line data selectors/multiplexers
module \74151  (
  input A,
  input C,
  input B,
  input S,
  input D0,
  input D1,
  input D2,
  input D3,
  input D4,
  input D5,
  input D6,
  input D7,
  input VCC,
  input GND,
  output Y,
  output W
);
  wire [2:0] s0;
  wire s1;
  wire Y_temp;
  assign s0[0] = A;
  assign s0[1] = B;
  assign s0[2] = C;
  Mux_8x1 Mux_8x1_i0 (
    .sel( s0 ),
    .in_0( D0 ),
    .in_1( D1 ),
    .in_2( D2 ),
    .in_3( D3 ),
    .in_4( D4 ),
    .in_5( D5 ),
    .in_6( D6 ),
    .in_7( D7 ),
    .out( s1 )
  );
  assign Y_temp = (~ S & s1);
  assign W = ~ Y_temp;
  assign Y = Y_temp;
endmodule

// 8-bit identity comparator
module \74688  (
  input P_0,
  input Q_0,
  input P_1,
  input Q_1,
  input P_2,
  input Q_2,
  input P_3,
  input Q_3,
  input P_4,
  input Q_4,
  input P_5,
  input Q_5,
  input P_6,
  input Q_6,
  input P_7,
  input Q_7,
  input \~OE ,
  input VCC,
  input GND,
  output \~EQ 
);
  assign \~EQ  = ~ (~ \~OE  & ~ ((P_0 ^ Q_0) | (P_1 ^ Q_1) | (P_2 ^ Q_2)) & ~ ((P_3 ^ Q_3) | (P_4 ^ Q_4) | (P_5 ^ Q_5)) & ~ ((P_6 ^ Q_6) | (P_7 ^ Q_7)));
endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


// Octal D Flip-Flop with enable
module \74377  (
  input D0,
  input VCC,
  input GND,
  input D1,
  input D2,
  input D3,
  input \~E ,
  input D4,
  input D5,
  input D6,
  input D7,
  input CLK,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7
);
  wire s0;
  wire s1;
  wire Q0_temp;
  wire s2;
  wire Q1_temp;
  wire s3;
  wire Q2_temp;
  wire s4;
  wire Q3_temp;
  wire s5;
  wire Q4_temp;
  wire s6;
  wire Q5_temp;
  wire s7;
  wire Q6_temp;
  wire s8;
  wire Q7_temp;
  assign s1 = ~ \~E ;
  assign s0 = ((Q0_temp & \~E ) | (D0 & s1));
  assign s2 = ((Q1_temp & \~E ) | (D1 & s1));
  assign s3 = ((Q2_temp & \~E ) | (D2 & s1));
  assign s4 = ((Q3_temp & \~E ) | (D3 & s1));
  assign s5 = ((Q4_temp & \~E ) | (D4 & s1));
  assign s6 = ((Q5_temp & \~E ) | (D5 & s1));
  assign s7 = ((Q6_temp & \~E ) | (D6 & s1));
  assign s8 = ((Q7_temp & \~E ) | (D7 & s1));
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( s0 ),
    .C( CLK ),
    .Q( Q0_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s2 ),
    .C( CLK ),
    .Q( Q1_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s3 ),
    .C( CLK ),
    .Q( Q2_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s4 ),
    .C( CLK ),
    .Q( Q3_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s5 ),
    .C( CLK ),
    .Q( Q4_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( s6 ),
    .C( CLK ),
    .Q( Q5_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s7 ),
    .C( CLK ),
    .Q( Q6_temp )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( s8 ),
    .C( CLK ),
    .Q( Q7_temp )
  );
  assign Q0 = Q0_temp;
  assign Q1 = Q1_temp;
  assign Q2 = Q2_temp;
  assign Q3 = Q3_temp;
  assign Q4 = Q4_temp;
  assign Q5 = Q5_temp;
  assign Q6 = Q6_temp;
  assign Q7 = Q7_temp;
endmodule

// quad 2-input XOR gate
module \7486  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = (\1A  ^ \1B );
  assign \2Y  = (\2A  ^ \2B );
  assign \3Y  = (\3A  ^ \3B );
  assign \4Y  = (\4A  ^ \4B );
endmodule

module alu_8b_final (
  input [7:0] lutA,
  input [7:0] A,
  input [7:0] B,
  input [7:0] C,
  input [7:0] lutB,
  input zin,
  input FLAG_WE,
  input [2:0] csel,
  input CLK,
  output [7:0] out,
  output [7:0] csr_flg,
  output zout,
  output cout
);
  wire [3:0] \A[3..0] ;
  wire [3:0] \A[7..4] ;
  wire [7:0] out_temp;
  wire [3:0] OUT_4;
  wire [3:0] OUT_8;
  wire [3:0] \B[3..0] ;
  wire [3:0] \C[3..0] ;
  wire \CIN-MAIN ;
  wire c0;
  wire [3:0] \B[7..4] ;
  wire [3:0] \C[7..4] ;
  wire cout_temp;
  wire Aeff;
  wire Beff;
  wire \~zin ;
  wire out0;
  wire out1;
  wire out2;
  wire out3;
  wire out4;
  wire out5;
  wire out6;
  wire out7;
  wire \~Zout ;
  wire zout_temp;
  wire \~flagWE ;
  wire flag_z;
  wire flag_z_b;
  wire flag_n;
  wire flag_c;
  wire flag_v;
  wire V_out;
  wire LT_sign;
  wire flag_lt;
  wire flag_gt;
  wire GT_sign;
  wire GTE_sign;
  wire flag_gte;
  wire cin_SEL_2;
  wire cin_SEL_1;
  wire cin_SEL_0;
  wire s0;
  wire s1;
  wire j1;
  wire j0;
  assign \A[3..0]  = A[3:0];
  assign \A[7..4]  = A[7:4];
  assign \B[3..0]  = B[3:0];
  assign \B[7..4]  = B[7:4];
  assign \C[3..0]  = C[3:0];
  assign \C[7..4]  = C[7:4];
  assign cin_SEL_0 = csel[0];
  assign cin_SEL_1 = csel[1];
  assign cin_SEL_2 = csel[2];
  alu_4b_final alu_4b_final_i0 (
    .A( \A[3..0]  ),
    .B( \B[3..0]  ),
    .lutA( lutA ),
    .C( \C[3..0]  ),
    .cin( \CIN-MAIN  ),
    .lutB( lutB ),
    .Out( OUT_4 ),
    .cout( c0 )
  );
  alu_4b_final alu_4b_final_i1 (
    .A( \A[7..4]  ),
    .B( \B[7..4]  ),
    .lutA( lutA ),
    .C( \C[7..4]  ),
    .cin( c0 ),
    .lutB( lutB ),
    .Out( OUT_8 ),
    .cout( cout_temp ),
    .aeff3( Aeff ),
    .beff3( Beff )
  );
  \7400  \7400_i2 (
    .\1A ( \~Zout  ),
    .\1B ( \~Zout  ),
    .\2A ( zin ),
    .\2B ( zin ),
    .GND( 1'b0 ),
    .\3A ( FLAG_WE ),
    .\3B ( FLAG_WE ),
    .\4A ( 1'b0 ),
    .\4B ( 1'b0 ),
    .VCC( 1'b1 ),
    .\1Y ( zout_temp ),
    .\2Y ( \~zin  ),
    .\3Y ( \~flagWE  )
  );
  \74151  \74151_i3 (
    .D3( flag_z ),
    .D2( flag_n ),
    .D1( 1'b1 ),
    .D0( 1'b0 ),
    .S( 1'b0 ),
    .GND( 1'b0 ),
    .C( cin_SEL_2 ),
    .B( cin_SEL_1 ),
    .A( cin_SEL_0 ),
    .D7( flag_v ),
    .D6( flag_lt ),
    .D5( flag_gt ),
    .D4( flag_c ),
    .VCC( 1'b1 ),
    .Y( \CIN-MAIN  )
  );
  assign out_temp[3:0] = OUT_4;
  assign out_temp[7:4] = OUT_8;
  assign out0 = out_temp[0];
  assign out1 = out_temp[1];
  assign out2 = out_temp[2];
  assign out3 = out_temp[3];
  assign out4 = out_temp[4];
  assign out5 = out_temp[5];
  assign out6 = out_temp[6];
  assign out7 = out_temp[7];
  \74688  \74688_i4 (
    .\~OE ( \~zin  ),
    .P_0( out0 ),
    .Q_0( 1'b0 ),
    .P_1( out1 ),
    .Q_1( 1'b0 ),
    .P_2( out2 ),
    .Q_2( 1'b0 ),
    .P_3( out3 ),
    .Q_3( 1'b0 ),
    .GND( 1'b0 ),
    .P_4( out4 ),
    .Q_4( 1'b0 ),
    .P_5( out5 ),
    .Q_5( 1'b0 ),
    .P_6( out6 ),
    .Q_6( 1'b0 ),
    .P_7( out7 ),
    .Q_7( 1'b0 ),
    .VCC( 1'b1 ),
    .\~EQ ( \~Zout  )
  );
  \74377  \74377_i5 (
    .\~E ( \~flagWE  ),
    .D0( zout_temp ),
    .D1( \~Zout  ),
    .D2( out7 ),
    .D3( cout_temp ),
    .GND( 1'b0 ),
    .CLK( CLK ),
    .D4( V_out ),
    .D5( LT_sign ),
    .D6( GT_sign ),
    .D7( GTE_sign ),
    .VCC( 1'b1 ),
    .Q0( flag_z ),
    .Q1( flag_z_b ),
    .Q2( flag_n ),
    .Q3( flag_c ),
    .Q4( flag_v ),
    .Q5( flag_lt ),
    .Q6( flag_gt ),
    .Q7( flag_gte )
  );
  \7400  \7400_i6 (
    .\1A ( \~Zout  ),
    .\1B ( GTE_sign ),
    .\2A ( s0 ),
    .\2B ( s0 ),
    .GND( 1'b0 ),
    .\3A ( s1 ),
    .\3B ( s1 ),
    .\4A ( j1 ),
    .\4B ( j0 ),
    .VCC( 1'b1 ),
    .\1Y ( s0 ),
    .\2Y ( GT_sign ),
    .\3Y ( V_out ),
    .\4Y ( s1 )
  );
  \7486  \7486_i7 (
    .\1A ( Aeff ),
    .\1B ( out7 ),
    .\2A ( out7 ),
    .\2B ( Beff ),
    .GND( 1'b0 ),
    .\3A ( 1'b1 ),
    .\3B ( LT_sign ),
    .\4A ( V_out ),
    .\4B ( out7 ),
    .VCC( 1'b1 ),
    .\1Y ( j0 ),
    .\2Y ( j1 ),
    .\3Y ( GTE_sign ),
    .\4Y ( LT_sign )
  );
  assign csr_flg[0] = flag_z;
  assign csr_flg[1] = flag_z_b;
  assign csr_flg[2] = flag_n;
  assign csr_flg[3] = flag_c;
  assign csr_flg[4] = flag_v;
  assign csr_flg[5] = flag_lt;
  assign csr_flg[6] = flag_gt;
  assign csr_flg[7] = flag_gte;
  assign out = out_temp;
  assign zout = zout_temp;
  assign cout = cout_temp;
endmodule

module \alu-32b-final  (
  input [7:0] lutA,
  input [7:0] lutB,
  input [31:0] A,
  input [31:0] B,
  input [31:0] C,
  input [2:0] csel,
  input FLAG_WE,
  input CLK,
  output [31:0] OUT,
  output [7:0] csr
);
  wire cout0;
  wire [2:0] cin1;
  wire cout1;
  wire [2:0] cin2;
  wire cout2;
  wire [2:0] cin3;
  wire [7:0] \A[7..0] ;
  wire [7:0] \B[7..0] ;
  wire [7:0] \C[7..0] ;
  wire [7:0] \OUT[7..0] ;
  wire \zout[7..0] ;
  wire [7:0] \A[15..8] ;
  wire [7:0] \B[15..8] ;
  wire [7:0] \C[15..8] ;
  wire [7:0] \OUT[15..8] ;
  wire \zout[15..8] ;
  wire [7:0] \A[23..16] ;
  wire [7:0] \B[23..16] ;
  wire [7:0] \C[23..16] ;
  wire [7:0] \OUT[23..16] ;
  wire \zout[23..16] ;
  wire [7:0] \A[31..24] ;
  wire [7:0] \B[31..24] ;
  wire [7:0] \C[31..24] ;
  wire [7:0] \OUT[31..24] ;
  wire \zout[31..24] ;
  wire cout3;
  assign \A[7..0]  = A[7:0];
  assign \A[15..8]  = A[15:8];
  assign \A[23..16]  = A[23:16];
  assign \A[31..24]  = A[31:24];
  assign \B[7..0]  = B[7:0];
  assign \B[15..8]  = B[15:8];
  assign \B[23..16]  = B[23:16];
  assign \B[31..24]  = B[31:24];
  assign \C[7..0]  = C[7:0];
  assign \C[15..8]  = C[15:8];
  assign \C[23..16]  = C[23:16];
  assign \C[31..24]  = C[31:24];
  alu_8b_final alu_8b_final_i0 (
    .lutA( lutA ),
    .A( \A[7..0]  ),
    .B( \B[7..0]  ),
    .C( \C[7..0]  ),
    .lutB( lutB ),
    .zin( 1'b0 ),
    .FLAG_WE( 1'b0 ),
    .csel( csel ),
    .CLK( CLK ),
    .out( \OUT[7..0]  ),
    .zout( \zout[7..0]  ),
    .cout( cout0 )
  );
  assign cin1[0] = cout0;
  assign cin1[2:1] = 2'b0;
  alu_8b_final alu_8b_final_i1 (
    .lutA( lutA ),
    .A( \A[15..8]  ),
    .B( \B[15..8]  ),
    .C( \C[15..8]  ),
    .lutB( lutB ),
    .zin( \zout[7..0]  ),
    .FLAG_WE( 1'b0 ),
    .csel( cin1 ),
    .CLK( CLK ),
    .out( \OUT[15..8]  ),
    .zout( \zout[15..8]  ),
    .cout( cout1 )
  );
  assign cin2[0] = cout1;
  assign cin2[2:1] = 2'b0;
  alu_8b_final alu_8b_final_i2 (
    .lutA( lutA ),
    .A( \A[23..16]  ),
    .B( \B[23..16]  ),
    .C( \C[23..16]  ),
    .lutB( lutB ),
    .zin( \zout[15..8]  ),
    .FLAG_WE( 1'b0 ),
    .csel( cin2 ),
    .CLK( CLK ),
    .out( \OUT[23..16]  ),
    .zout( \zout[23..16]  ),
    .cout( cout2 )
  );
  assign cin3[0] = cout2;
  assign cin3[2:1] = 2'b0;
  alu_8b_final alu_8b_final_i3 (
    .lutA( lutA ),
    .A( \A[31..24]  ),
    .B( \B[31..24]  ),
    .C( \C[31..24]  ),
    .lutB( lutB ),
    .zin( \zout[23..16]  ),
    .FLAG_WE( FLAG_WE ),
    .csel( cin3 ),
    .CLK( CLK ),
    .out( \OUT[31..24]  ),
    .csr_flg( csr ),
    .zout( \zout[31..24]  ),
    .cout( cout3 )
  );
  assign OUT[7:0] = \OUT[7..0] ;
  assign OUT[15:8] = \OUT[15..8] ;
  assign OUT[23:16] = \OUT[23..16] ;
  assign OUT[31:24] = \OUT[31..24] ;
endmodule
