#!/usr/bin/env python3
"""Extract directed ALU vectors from Digital-exported testbenches.

The three source testbenches under directed/ have Digital module names with
spaces, so Icarus cannot compile them directly. This script parses every
``patterns[N] = 144'b...;`` line and emits directed/run_extracted_tb.v — a
self-checking Icarus testbench that replays the stimulus through
alu_32b_dut_wrap and compares Out against alu_ref.v's alu_predict_out().

Packing (MSB first): A[143:112] B[111:80] C[79:48] Opcode[47:40]
control[39:36] csel[35:34] CLK[33] (ignored — the TB pulses its own clock)
FLAG_WE[32] expected-Out[31:0] (unused; the compare is against the golden
model, exactly like the UVM directed sequence).

Vectors whose expected-Out field contains x are flag-only stimulus: they are
still *applied* (they advance the flag latches, in source order) but not
*checked*. The emitted table order matches uvm/common/directed_vectors_pkg.sv
so the two stays in lockstep — see SOURCES below.

Usage:
    make -C verification generate     # (re)build directed/run_extracted_tb.v
    python3 scripts/generate.py       # same, from verification/
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRECTED = ROOT / "directed"
OUT = DIRECTED / "run_extracted_tb.v"

# (filename, usable vectors when this shipped). The flagc-carry bench holds
# 15 pattern lines, 6 of which are flag-only (x in expected-Out) → 9 usable.
SOURCES = [
    ("alu-32b-final_Exhaustive 91 Ops Test_tb.v", 455),
    ("alu-32b-final_alu-comb-flags_tb.v", 12),
    ("alu-32b-final_alu-flagc-carry_tb.v", 9),
]

PATTERN = re.compile(r"patterns\[(\d+)\]\s*=\s*144'b([01xX_]+)\s*;")

TB_TEMPLATE = """\
// Auto-generated by scripts/generate.py — do not edit.
// Sources:{sources}
// {nstim} stimulus rows applied in order, {ncheck} checked
// (flag-only rows with x in expected-Out advance the latches, unchecked).
//
// Golden model alu_predict_out() comes from alu_ref.v, compiled on the same
// iverilog command line (one compilation unit) — no `include needed here.
`timescale 1ns/1ps
`default_nettype none

module run_extracted_tb;
  localparam int NSTIM = {nstim};

  reg [143:0] stim [0:NSTIM-1];
  reg         check[0:NSTIM-1];

  reg [31:0] a, b, c;
  reg [7:0]  opcode;
  reg [3:0]  control;
  reg [1:0]  csel;
  reg        clk, flag_we, flag_a_is_zero_n;
  wire [31:0] out;
  wire [12:0] csr_flag;

  integer i, ncheck, nfail;
  reg [143:0] v;
  reg [31:0] got, exp0;

  alu_32b_dut_wrap dut (
    .a(a), .b(b), .c(c),
    .opcode(opcode), .control(control), .csel(csel),
    .clk(clk), .flag_we(flag_we),
    .flag_a_is_zero_n(flag_a_is_zero_n),
    .out(out), .csr_flag(csr_flag)
  );

  initial begin
{stim_init}{check_init}
    clk = 1'b0;
    flag_a_is_zero_n = 1'b1;
    ncheck = 0;
    nfail = 0;
    for (i = 0; i < NSTIM; i = i + 1) begin
      v = stim[i];
      a = v[143:112]; b = v[111:80]; c = v[79:48];
      opcode = v[47:40]; control = v[39:36]; csel = v[35:34];
      flag_we = v[32];
      #10 clk = 1'b1;   // let FLAG_WE latch, exactly once per vector
      #10 clk = 1'b0;
      #10;
      if (check[i]) begin
        ncheck = ncheck + 1;
        got = out;
        // flag_c for csel=10 is the live latch bit, like the DUT sees it.
        exp0 = alu_predict_out(a, b, c, opcode, control, csel, csr_flag[4]);
        if ((got !== exp0) && (csel == 2'b10))
          exp0 = alu_predict_out(a, b, c, opcode, control, csel, 1'b1);
        if (got !== exp0) begin
          nfail = nfail + 1;
          $display("FAIL vec=%0d csel=%b got=%h exp=%h flags=%h",
                   i, csel, got, exp0, csr_flag);
        end
      end
    end
    $display("directed: %0d/%0d checked vectors pass", ncheck - nfail, ncheck);
    if (nfail != 0)
      $fatal(1, "directed: %0d mismatches", nfail);
    else
      $display("PASS: directed %0d/%0d", ncheck, ncheck);
    $finish;
  end
endmodule
"""


def parse_tb(path: Path) -> list[tuple[int, str]]:
    rows: dict[int, str] = {}
    for line in path.read_text().splitlines():
        m = PATTERN.search(line)
        if m:
            rows[int(m.group(1))] = m.group(2).replace("_", "")
    return [(idx, rows[idx]) for idx in sorted(rows)]


def main() -> int:
    stim: list[str] = []
    checks: list[int] = []
    notes: list[str] = []
    for name, _want in SOURCES:
        rows = parse_tb(DIRECTED / name)
        usable = 0
        for _idx, bits in rows:
            if len(bits) != 144 or any(ch not in "01xX" for ch in bits):
                print(f"error: {name}: bad 144-bit row: {bits[:48]}...", file=sys.stderr)
                return 1
            has_x = "x" in bits.lower()
            stim.append(bits.lower().replace("x", "0"))
            checks.append(0 if has_x else 1)
            usable += 0 if has_x else 1
        notes.append(f"\n//   {name}: {usable} usable / {len(rows)} rows")
        print(f"{name}: {usable} usable / {len(rows)} rows")

    nstim, ncheck = len(stim), sum(checks)
    stim_init = "".join(f"    stim[{i}] = 144'h{int(b, 2):036x};\n" for i, b in enumerate(stim))
    check_init = "".join(f"    check[{i}] = 1'b{c};\n" for i, c in enumerate(checks))
    OUT.write_text(
        TB_TEMPLATE.format(
            sources="".join(notes),
            nstim=nstim,
            ncheck=ncheck,
            stim_init=stim_init,
            check_init=check_init,
        )
    )
    print(f"wrote {OUT} ({nstim} stimulus, {ncheck} checked)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
