#!/usr/bin/env python3
"""Recount formal assert/cover statements → formal/PROPERTY_INVENTORY.md"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FORMAL = ROOT / "formal"
BINDS = [
    ("alu_1b_verify_bind.v", 1),
    ("alu_8b_verify_bind.v", 8),
    ("alu_32b_verify_bind.v", 1),
    ("alu_32b_equiv_verify_bind.v", 1),
    ("alu_32b_flags_verify_bind.v", 1),
]
JOBS = [
    ("alu_1b_verify.sby", "prove"),
    ("alu_8b_verify.sby", "prove"),
    ("alu_32b_verify.sby", "prove"),
    ("alu_32b_equiv_verify.sby", "prove"),
    ("alu_32b_flags_verify.sby", "cover"),
]


def main() -> int:
    rows = []
    ta = tc = ea = ec = 0
    for name, mult in BINDS:
        text = (FORMAL / name).read_text()
        a = len(re.findall(r"\bassert\s*\(", text))
        c = len(re.findall(r"\bcover\s*\(", text))
        rows.append((name, a, c, a * mult, c * mult))
        ta += a
        tc += c
        ea += a * mult
        ec += c * mult

    lines = [
        "# Formal property inventory (ALU only)",
        "",
        "Generated by `verification/scripts/inventory_formal.py`.",
        "These properties cover the **ALU netlist**, not the full Tomato CPU / ISA / memory system.",
        "",
        "## Jobs (5/5 documented PASS)",
        "",
        "| Job | Mode |",
        "|-----|------|",
    ]
    for j, m in JOBS:
        lines.append(f"| `{j}` | {m} |")
    lines += [
        "",
        "## Bind statement counts",
        "",
        "| Bind file | Source assert | Source cover | Elaborated assert | Elaborated cover |",
        "|-----------|---------------|--------------|-------------------|------------------|",
    ]
    for name, a, c, ela, elc in rows:
        lines.append(f"| `{name}` | {a} | {c} | {ela} | {elc} |")
    lines += [
        f"| **Total** | **{ta}** | **{tc}** | **{ea}** | **{ec}** |",
        "",
        f"**Headline:** ALU formal suite = **5/5 jobs**, **{ta} assert + {tc} cover** "
        f"source (**{ea} + {ec}** after 8b generate).",
        "",
        "```bash",
        "make -C verification formal_inventory",
        "make -C verification formal_full   # requires sby",
        "```",
        "",
    ]
    out = FORMAL / "PROPERTY_INVENTORY.md"
    out.write_text("\n".join(lines))
    print(out)
    print(f"jobs=5/5 assert={ta} cover={tc} elab_assert={ea} elab_cover={ec}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
