#!/usr/bin/env python3
"""Burn Tomato microcode + boot programs into synthesizable Verilog includes.

Emits hardware/fpga/tomato/rtl/burn/*.vh so Vivado only needs rtl/*.v
(+ `include burn/). No external $readmemh paths required for FPGA.

Usage:
  python3 tools/gen_fpga_burn.py              # microcode + default OS boot
  python3 tools/gen_fpga_burn.py --boot snake # select dmem image
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FPGA = ROOT / "hardware/fpga/tomato"
MEM = FPGA / "tb/mem"
BURN = FPGA / "rtl/burn"

MC_ROMS = [
    "alu_shift_control",
    "alu_control_1",
    "alu_lut_b",
    "ir_reg_control",
    "mem_io_control",
    "mem_bus_control",
    "pc_control",
    "pc_sp_mul_control",
]

BOOT_IMAGES = [
    "counter",
    "tomato_os",
    "snake",
    "bounce",
    "sudoku",
    "tetris",
    "shooter",
]


def read_memh(path: Path) -> list[int]:
    words: list[int] = []
    for line in path.read_text().splitlines():
        s = line.split("//")[0].strip()
        if not s:
            continue
        words.append(int(s, 16))
    return words


def emit_rom_vh(name: str, words: list[int]) -> None:
    """512×8 microcode ROM as mem[i] = 8'hXX;"""
    if len(words) < 512:
        words = words + [0] * (512 - len(words))
    words = words[:512]
    lines = [
        f"// AUTO-GENERATED by tools/gen_fpga_burn.py — {name}",
        f"// Do not edit. Source: tb/mem/{name}.mem",
    ]
    for i, w in enumerate(words):
        lines.append(f"mem[{i}] = 8'h{w & 0xFF:02X};")
    (BURN / f"mc_{name}.vh").write_text("\n".join(lines) + "\n")


def emit_dmem_vh(name: str, words: list[int]) -> None:
    """Sparse dmem[addr] = 32'h...; (zeros omitted)."""
    lines = [
        f"// AUTO-GENERATED by tools/gen_fpga_burn.py — boot image '{name}'",
        f"// Do not edit. Source: tb/mem/{name}.mem ({len(words)} words)",
    ]
    for i, w in enumerate(words):
        if w != 0:
            lines.append(f"dmem[{i}] = 32'h{w & 0xFFFFFFFF:08X};")
    if len(lines) == 2:
        lines.append("// (image is all zeros)")
    (BURN / f"dmem_{name}.vh").write_text("\n".join(lines) + "\n")


def emit_boot_images_v() -> None:
    """Single module with all boot images for SW-select copy (optional)."""
    chunks: list[str] = []
    chunks.append("""\
// AUTO-GENERATED by tools/gen_fpga_burn.py — do not edit
// Multi-image boot ROM: sel picks which program is copied into dmem.
module tomato_boot_rom (
    input  [3:0]  sel,
    input  [13:0] addr,
    output [31:0] data,
    output [13:0] len
);
    reg [31:0] data_r;
    reg [13:0] len_r;
    assign data = data_r;
    assign len  = len_r;
""")
    # emit arrays
    for idx, name in enumerate(BOOT_IMAGES):
        path = MEM / f"{name}.mem"
        words = read_memh(path)
        n = len(words)
        chunks.append(f"    // ---- {name} ({n} words) sel={idx} ----")
        chunks.append(f"    reg [31:0] img_{name} [0:{max(n - 1, 0)}];")
        chunks.append("    initial begin")
        for i, w in enumerate(words):
            chunks.append(f"        img_{name}[{i}] = 32'h{w & 0xFFFFFFFF:08X};")
        if n == 0:
            chunks.append("        img_%s[0] = 32'h0;" % name)
        chunks.append("    end")
        chunks.append("")

    chunks.append("    always @(*) begin")
    chunks.append("        data_r = 32'h0;")
    chunks.append("        len_r  = 14'd0;")
    chunks.append("        case (sel)")
    for idx, name in enumerate(BOOT_IMAGES):
        path = MEM / f"{name}.mem"
        n = len(read_memh(path))
        chunks.append(f"            4'd{idx}: begin")
        chunks.append(f"                len_r = 14'd{n};")
        chunks.append(f"                if (addr < 14'd{n})")
        chunks.append(f"                    data_r = img_{name}[addr];")
        chunks.append("            end")
    chunks.append("            default: begin")
    chunks.append("                len_r = 14'd0;")
    chunks.append("                data_r = 32'h0;")
    chunks.append("            end")
    chunks.append("        endcase")
    chunks.append("    end")
    chunks.append("endmodule")
    # Sit next to other rtl/*.v so Vivado "add rtl folder" picks it up
    (FPGA / "rtl/tomato_boot_rom.v").write_text("\n".join(chunks) + "\n")


def emit_dmem_init_select(boot: str) -> None:
    """Active include used by main.v — inlined selected image (no nested include)."""
    if boot not in BOOT_IMAGES:
        raise SystemExit(f"unknown boot '{boot}', choose from {BOOT_IMAGES}")
    src = BURN / f"dmem_{boot}.vh"
    body = src.read_text()
    text = (
        f"// ACTIVE FPGA dmem burn — boot={boot}\n"
        f"// Rewrite: python3 tools/gen_fpga_burn.py --boot {boot}\n"
        f"{body}"
    )
    (BURN / "dmem_init.vh").write_text(text)
    (BURN / "BOOT.txt").write_text(
        f"active_boot={boot}\n"
        f"images={','.join(BOOT_IMAGES)}\n"
        f"microcode_roms={len(MC_ROMS)}\n"
        "vivado_top=nexys_top\n"
        "vivado_include_dir=rtl/\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--boot",
        default="tomato_os",
        choices=BOOT_IMAGES,
        help="program image burned into dmem for FPGA (default: tomato_os)",
    )
    args = ap.parse_args()

    BURN.mkdir(parents=True, exist_ok=True)

    for name in MC_ROMS:
        path = MEM / f"{name}.mem"
        if not path.exists():
            raise SystemExit(f"missing microcode image: {path} (run make microcode)")
        emit_rom_vh(name, read_memh(path))

    for name in BOOT_IMAGES:
        path = MEM / f"{name}.mem"
        if not path.exists():
            raise SystemExit(f"missing program image: {path} (run make asm)")
        emit_dmem_vh(name, read_memh(path))

    emit_boot_images_v()
    emit_dmem_init_select(args.boot)

    print(f"burned microcode: {len(MC_ROMS)} ROMs → {BURN}/mc_*.vh")
    print(f"burned programs:  {', '.join(BOOT_IMAGES)} → dmem_*.vh")
    print(f"active FPGA boot: {args.boot} → dmem_init.vh + tomato_boot_rom.v")


if __name__ == "__main__":
    main()
